# Partie E · S'exprimer (B1), leçons 66 à 90
def L(n, title, obj, scene, dia, ce, voc, gt, gex, gq, grule, co, ant, ee, task, cult=None):
    d = {"n": n, "title": title, "obj": obj, "scene": scene, "dia": dia, "ce": ce, "voc": voc,
         "gram": {"t": gt, "ex": gex, "q": gq, "rule": grule}, "co": co, "ant": ant, "ee": ee, "task": task}
    if cult:
        d["cult"] = cult
    return d

LESSONS = [
L(66, "Je pense que…", "Donner ton avis sur un film ou un livre, et demander celui des autres.", "Noy et Clara sortent du cinéma.",
  [("N", "ເຈົ້າ|ຄິດ|ວ່າ|ໜັງ|ເລື່ອງ|ນີ້|ເປັນ|ແນວໃດ|?", "Tu as trouvé ce film comment ?"),
   ("C", "ຂ້ອຍ|ຄິດ|ວ່າ|ມ່ວນ|ດີ|,|ແຕ່|ຍາວ|ໂພດ|.", "Je pense qu'il était bien, mais trop long."),
   ("N", "ຂ້ອຍ|ເຫັນ|ວ່າ|ຕອນ|ຈົບ|ເສົ້າ|ຫຼາຍ|.", "Moi, je trouve que la fin était très triste."),
   ("C", "ແມ່ນ|.|ຂ້ອຍ|ເກືອບ|ຮ້ອງໄຫ້|.", "C'est vrai. J'ai failli pleurer."),
   ("N", "ໂດຍ|ລວມ|ແລ້ວ|ໃຫ້|ຈັກ|ຄະແນນ|?", "Au final, tu lui donnes combien ?"),
   ("C", "ແປດ|ເຕັມ|ສິບ|.", "Huit sur dix.")],
  [("Qu'a pensé Clara du film ?", "Bien mais trop long."), ("Qu'est-ce qui a ému Noy ?", "La fin, très triste."), ("Quelle note donne Clara ?", "8/10.")],
  [("ຄິດ|ວ່າ", "penser que"), ("ເຫັນ|ວ່າ", "trouver que, estimer"), ("ຕາມ|ຄວາມ|ຄິດ|ຂອງ|ຂ້ອຍ", "à mon avis"), ("ເລື່ອງ", "histoire ; classif. des films"), ("ຕອນ|ຈົບ", "la fin"),
   ("ເສົ້າ", "triste"), ("ເກືອບ", "presque, faillir"), ("ໂດຍ|ລວມ|ແລ້ວ", "dans l'ensemble"), ("ຄະແນນ", "note, points"), ("ເຕັມ", "plein, sur (note)")],
  "exprimer une opinion", [("ຂ້ອຍ|ຄິດ|ວ່າ|…", "je pense que…"), ("ຕາມ|ຄວາມ|ຄິດ|ຂອງ|ຂ້ອຍ|…", "à mon avis…"), ("ເຈົ້າ|ຄິດ|ແນວໃດ|?", "qu'en penses-tu ?")],
  ["Quelle différence de nuance entre ຄິດວ່າ et ເຫັນວ່າ ?"], "ຄິດວ່າ = penser (opinion), ເຫັນວ່າ = trouver, estimer (jugement à partir de ce qu'on a vu). On demande l'avis avec ຄິດແນວໃດ ?",
  "les introductions d'opinion.",
  [("Qu'en penses-tu ?", "ເຈົ້າ|ຄິດ|ແນວໃດ|?"), ("À mon avis, c'était trop long.", "ຕາມ|ຄວາມ|ຄິດ|ຂອງ|ຂ້ອຍ|ຍາວ|ໂພດ|."), ("J'ai failli pleurer.", "ຂ້ອຍ|ເກືອບ|ຮ້ອງໄຫ້|.")],
  ["Écris une critique de 8 phrases d'un film que tu as vu."], "Donne ton avis sur un film ou une série à un natif et demande le sien."),
L(67, "D'accord, pas d'accord", "Exprimer ton accord et ton désaccord sans froisser.", "La famille discute d'un projet de voyage.",
  [("S", "ປີໜ້າ|ເຮົາ|ໄປ|ທ່ຽວ|ທະເລ|ເນາະ|.", "L'an prochain, on va à la mer, d'accord ?"),
   ("B", "ຂ້ອຍ|ເຫັນດີ|.", "Je suis d'accord."),
   ("K", "ຂ້ອຍ|ບໍ່|ຄ່ອຍ|ເຫັນດີ|ປານໃດ|.|ໄປ|ພູ|ດີ|ກວ່າ|.", "Je ne suis pas trop d'accord. La montagne, c'est mieux."),
   ("N", "ກໍ|ມີ|ເຫດຜົນ|ເນາະ|,|ແຕ່|ທະເລ|ມ່ວນ|ກວ່າ|.", "Ce n'est pas faux, mais la mer c'est plus sympa."),
   ("S", "ໂອເຄ|,|ຂໍ|ຄິດ|ເບິ່ງ|ກ່ອນ|.", "OK, laissez-moi réfléchir.")],
  [("Qui n'est pas d'accord ?", "Kèo."), ("Que propose-t-il ?", "La montagne plutôt que la mer.")],
  [("ເຫັນດີ", "être d'accord"), ("ບໍ່|ເຫັນດີ", "ne pas être d'accord"), ("ບໍ່|ຄ່ອຍ|ເຫັນດີ|ປານໃດ", "pas vraiment d'accord"), ("ມີ|ເຫດຜົນ", "c'est logique, ça se tient"),
   ("ແມ່ນ|ຢູ່|,|ແຕ່", "c'est vrai, mais…"), ("ຂໍ|ຄິດ|ເບິ່ງ|ກ່ອນ", "laisse-moi réfléchir"), ("ດີ|ກວ່າ", "mieux")],
  "adoucir le désaccord", [("ແມ່ນ|ຢູ່|,|ແຕ່|…", "c'est vrai, mais…"), ("ບໍ່|ຄ່ອຍ|…|ປານໃດ", "pas trop…")],
  ["Pourquoi Kèo ne dit-il pas simplement ບໍ່ເຫັນດີ ?"], "On adoucit le désaccord : on reconnaît d'abord l'autre (ແມ່ນຢູ່, ມີເຫດຜົນ), puis on nuance avec ແຕ່ ou ບໍ່ຄ່ອຍ…ປານໃດ.",
  "les formules qui adoucissent.",
  [("Je suis d'accord.", "ຂ້ອຍ|ເຫັນດີ|."), ("C'est vrai, mais…", "ແມ່ນ|ຢູ່|,|ແຕ່|…"), ("Laisse-moi réfléchir.", "ຂໍ|ຄິດ|ເບິ່ງ|ກ່ອນ|.")],
  ["Écris 3 désaccords polis sur des sujets du quotidien."], "Débats d'un petit sujet (vacances, repas) avec un natif en restant poli."),
L(68, "Raconter une histoire", "Raconter un souvenir avec un début, un milieu et une fin.", "Mme Boua raconte son mariage.",
  [("B", "ຕອນ|ນັ້ນ|ຂ້ອຍ|ອາຍຸ|ຊາວ|ປີ|.", "À l'époque, j'avais vingt ans."),
   ("B", "ມື້|ໜຶ່ງ|ພໍ່|ສົມສັກ|ມາ|ຂໍ|ຂ້ອຍ|ແຕ່ງງານ|.", "Un jour, Somsak est venu demander ma main."),
   ("C", "ແລ້ວ|ແມ່|ຕອບ|ວ່າ|ແນວໃດ|?", "Et vous avez répondu quoi ?"),
   ("B", "ທຳອິດ|ຂ້ອຍ|ອາຍ|,|ບໍ່|ກ້າ|ຕອບ|.", "D'abord, j'étais timide, je n'osais pas répondre."),
   ("B", "ແຕ່|ສຸດທ້າຍ|ກໍ|ຕົກລົງ|.|ແລະ|ຢູ່|ນຳ|ກັນ|ມາ|ສາມສິບ|ປີ|ແລ້ວ|.", "Mais finalement j'ai accepté. Et ça fait trente ans qu'on est ensemble.")],
  [("Quel âge avait Mme Boua ?", "Vingt ans."), ("Comment a-t-elle réagi d'abord ?", "Elle était timide, n'osait pas répondre.")],
  [("ຕອນ|ນັ້ນ", "à l'époque, à ce moment-là"), ("ມື້|ໜຶ່ງ", "un jour"), ("ຂໍ|ແຕ່ງງານ", "demander en mariage"), ("ອາຍ", "timide, gêné"), ("ກ້າ", "oser"),
   ("ສຸດທ້າຍ", "finalement"), ("ຫຼັງຈາກ|ນັ້ນ", "après ça"), ("ທັນໃດ|ນັ້ນ", "soudain")],
  "les connecteurs du récit", [("ມື້|ໜຶ່ງ|…", "un jour…"), ("ຫຼັງຈາກ|ນັ້ນ|…", "après ça…"), ("ທັນໃດ|ນັ້ນ|…", "soudain…")],
  ["Quels mots marquent les étapes de l'histoire ?"], "Un récit se structure avec : ຕອນນັ້ນ (cadre), ມື້ໜຶ່ງ (déclencheur), ທັນໃດນັ້ນ (événement), ຫຼັງຈາກນັ້ນ (suite), ສຸດທ້າຍ (fin).",
  "les connecteurs temporels.",
  [("Un jour…", "ມື້|ໜຶ່ງ|…"), ("Je n'osais pas répondre.", "ຂ້ອຍ|ບໍ່|ກ້າ|ຕອບ|."), ("Finalement, j'ai accepté.", "ສຸດທ້າຍ|ກໍ|ຕົກລົງ|.")],
  ["Raconte un souvenir marquant en 10 phrases avec les connecteurs."], "Demande à un aîné lao de te raconter un souvenir, puis raconte-le à ton tour."),
L(69, "Mon enfance", "Comparer ta vie d'avant et celle d'aujourd'hui.", "M. Somsak parle du Vientiane d'autrefois.",
  [("S", "ແຕ່ກ່ອນ|ວຽງຈັນ|ບໍ່|ມີ|ລົດ|ຫຼາຍ|ຄື|ດຽວນີ້|.", "Avant, à Vientiane, il n'y avait pas autant de voitures qu'aujourd'hui."),
   ("S", "ພວກເຮົາ|ຂີ່|ລົດຖີບ|ໄປ|ໂຮງຮຽນ|.", "On allait à l'école à vélo."),
   ("C", "ດຽວນີ້|ປ່ຽນ|ໄປ|ຫຼາຍ|ບໍ|?", "Ça a beaucoup changé ?"),
   ("S", "ປ່ຽນ|ຫຼາຍ|.|ແຕ່|ຄົນ|ຍັງ|ໃຈດີ|ຄື|ເກົ່າ|.", "Énormément. Mais les gens sont toujours aussi gentils.")],
  [("Comment allait-on à l'école ?", "À vélo."), ("Qu'est-ce qui n'a pas changé ?", "La gentillesse des gens.")],
  [("ແຕ່ກ່ອນ", "avant, autrefois"), ("ດຽວນີ້", "maintenant"), ("ຕອນ|ເປັນ|ເດັກນ້ອຍ", "quand j'étais enfant"), ("ປ່ຽນ", "changer"), ("ຄື|ເກົ່າ", "comme avant"),
   ("ລົດຖີບ", "vélo"), ("ບໍ່|…|ຄື", "pas autant que")],
  "avant et maintenant", [("ແຕ່ກ່ອນ|…|ດຽວນີ້|…", "avant… maintenant…"), ("ຍັງ|…|ຄື|ເກົ່າ", "toujours… comme avant")],
  ["Comment opposes-tu avant et maintenant ?"], "ແຕ່ກ່ອນ (avant) s'oppose à ດຽວນີ້ (maintenant). ຍັງ…ຄືເກົ່າ = toujours comme avant.",
  "l'opposition passé / présent.",
  [("Quand j'étais enfant…", "ຕອນ|ເປັນ|ເດັກນ້ອຍ|…"), ("Ça a beaucoup changé.", "ປ່ຽນ|ໄປ|ຫຼາຍ|."), ("Comme avant.", "ຄື|ເກົ່າ|.")],
  ["Compare ton enfance et ta vie actuelle en 8 phrases."], "Demande à un natif âgé comment était sa ville avant."),
L(70, "Un problème", "Expliquer une panne ou un souci et demander de l'aide.", "La clim de Clara est en panne.",
  [("C", "ແອ|ເສຍ|ແລ້ວ|.|ຊ່ວຍ|ມາ|ເບິ່ງ|ໃຫ້|ແດ່|ໄດ້|ບໍ|?", "La clim est en panne. Vous pouvez venir voir ?"),
   ("W", "ເປັນ|ແນວໃດ|?", "Qu'est-ce qu'elle a ?"),
   ("C", "ເປີດ|ແລ້ວ|ແຕ່|ບໍ່|ເຢັນ|.", "Elle s'allume mais ne refroidit pas."),
   ("W", "ມື້ອື່ນ|ຈະ|ໃຫ້|ຊ່າງ|ໄປ|ສ້ອມ|ໃຫ້|.", "Demain, j'enverrai un technicien la réparer.")],
  [("Quel est le problème ?", "La clim s'allume mais ne refroidit pas."), ("Quelle solution ?", "Un technicien demain.")],
  [("ເສຍ", "être en panne, cassé"), ("ສ້ອມ", "réparer"), ("ຊ່າງ", "technicien, artisan"), ("ໃຫ້|…|ໄປ", "faire aller, envoyer"), ("ບັນຫາ", "problème"), ("ຊ່ວຍ|…|ໃຫ້|ແດ່", "aide-moi à…")],
  "le causatif avec ໃຫ້", [("ໃຫ້|ຊ່າງ|ສ້ອມ", "faire réparer par un technicien"), ("ແມ່|ໃຫ້|ຂ້ອຍ|ໄປ|ຕະຫຼາດ", "maman m'envoie au marché")],
  ["Que fait ໃຫ້ entre deux éléments ?"], "ໃຫ້ + personne + verbe = faire faire quelque chose à quelqu'un. Après un verbe, ໃຫ້ = pour (le bénéficiaire).",
  "ໃຫ້ et ses deux sens.",
  [("La clim est en panne.", "ແອ|ເສຍ|ແລ້ວ|."), ("Vous pouvez venir voir ?", "ມາ|ເບິ່ງ|ໃຫ້|ແດ່|ໄດ້|ບໍ|?"), ("Je vais la faire réparer.", "ຈະ|ໃຫ້|ຊ່າງ|ສ້ອມ|.")],
  ["Écris un message à un propriétaire pour signaler 2 problèmes."], "Joue avec un natif l'appel à un réparateur."),
L(71, "Réclamer", "Faire une réclamation polie et comprendre le passif.", "Clara a été facturée deux fois.",
  [("C", "ຂໍໂທດ|,|ຂ້ອຍ|ຖືກ|ເກັບ|ເງິນ|ສອງ|ເທື່ອ|.", "Excusez-moi, on m'a fait payer deux fois."),
   ("W", "ແທ້|ບໍ|?|ຂໍ|ເບິ່ງ|ໃບບິນ|ແດ່|.", "Vraiment ? Montrez-moi le ticket, s'il vous plaît."),
   ("W", "ແມ່ນ|ແລ້ວ|,|ຂໍ|ອະໄພ|.|ຈະ|ຄືນ|ເງິນ|ໃຫ້|.", "En effet, désolé. Je vous rembourse."),
   ("C", "ຂອບໃຈ|ທີ່|ເຂົ້າໃຈ|.", "Merci de votre compréhension.")],
  [("Quel est le problème ?", "Clara a payé deux fois."), ("Que fait l'employé ?", "Il vérifie et rembourse.")],
  [("ຖືກ", "(passif) subir"), ("ໂດນ", "(passif familier) se faire"), ("ເກັບ|ເງິນ", "encaisser"), ("ໃບບິນ", "ticket, facture"), ("ຄືນ|ເງິນ", "rembourser"), ("ຮ້ອງຮຽນ", "se plaindre")],
  "le passif avec ຖືກ et ໂດນ", [("ຖືກ|ເກັບ|ເງິນ", "se faire encaisser"), ("ໂດນ|ຂີ້ລັກ", "se faire voler"), ("ຖືກ|ຕຳຫຼວດ|ຈັບ", "se faire arrêter par la police")],
  ["Le passif lao est-il positif ou négatif en général ?"], "ຖືກ / ໂດນ + (agent) + verbe = subir une action, souvent désagréable. ໂດນ est plus familier.",
  "ຖືກ et ໂດນ.",
  [("On m'a fait payer deux fois.", "ຂ້ອຍ|ຖືກ|ເກັບ|ເງິນ|ສອງ|ເທື່ອ|."), ("Vous pouvez me rembourser ?", "ຄືນ|ເງິນ|ໃຫ້|ໄດ້|ບໍ|?"), ("Merci de votre compréhension.", "ຂອບໃຈ|ທີ່|ເຂົ້າໃຈ|.")],
  ["Écris une réclamation polie de 5 phrases."], "Joue une réclamation au magasin avec un natif."),
L(72, "Il a dit que…", "Rapporter une conversation entière.", "Noy raconte sa dispute avec son copain.",
  [("N", "ແຟນ|ຂ້ອຍ|ບອກ|ວ່າ|ລາວ|ຫຍຸ້ງ|ຫຼາຍ|.", "Mon copain m'a dit qu'il était très occupé."),
   ("N", "ແລ້ວ|ລາວ|ຖາມ|ວ່າ|ຂ້ອຍ|ໃຈຮ້າຍ|ບໍ|.", "Puis il m'a demandé si j'étais fâchée."),
   ("C", "ແລ້ວ|ເຈົ້າ|ຕອບ|ວ່າ|ແນວໃດ|?", "Et tu as répondu quoi ?"),
   ("N", "ຂ້ອຍ|ບອກ|ວ່າ|ບໍ່|,|ແຕ່|ຂ້ອຍ|ໃຈຮ້າຍ|ແທ້|!", "Je lui ai dit non, mais j'étais vraiment fâchée !")],
  [("Qu'a dit le copain ?", "Qu'il était très occupé."), ("Qu'a répondu Noy ?", "Non, alors qu'elle était fâchée.")],
  [("ບອກ|ວ່າ", "dire que"), ("ຖາມ|ວ່າ|…|ບໍ", "demander si"), ("ຕອບ|ວ່າ", "répondre que"), ("ຫຍຸ້ງ", "occupé"), ("ແຟນ", "petit(e) ami(e)"), ("ລົມ", "discuter")],
  "le discours rapporté complet", [("ລາວ|ຖາມ|ວ່າ|ຂ້ອຍ|ໄປ|ບໍ", "il a demandé si j'y allais"), ("ລາວ|ບອກ|ໃຫ້|ຂ້ອຍ|ລໍ", "il m'a dit d'attendre")],
  ["Comment rapporte-t-on une question ? Un ordre ?"], "Affirmation : ບອກວ່າ + phrase. Question : ຖາມວ່າ + phrase + ບໍ. Ordre : ບອກໃຫ້ + personne + verbe. Les pronoms changent comme en français.",
  "ວ່າ après chaque verbe de parole.",
  [("Il m'a dit qu'il était occupé.", "ລາວ|ບອກ|ວ່າ|ລາວ|ຫຍຸ້ງ|."), ("Il m'a demandé si j'étais fâchée.", "ລາວ|ຖາມ|ວ່າ|ຂ້ອຍ|ໃຈຮ້າຍ|ບໍ|."), ("Il m'a dit d'attendre.", "ລາວ|ບອກ|ໃຫ້|ຂ້ອຍ|ລໍ|.")],
  ["Rapporte une conversation récente en 8 phrases."], "Raconte à un natif une discussion que tu as eue avec quelqu'un d'autre."),
L(73, "Conseiller", "Donner et demander un conseil.", "Kèo hésite sur ses études.",
  [("K", "ຂ້ອຍ|ບໍ່|ຮູ້|ວ່າ|ຈະ|ຮຽນ|ຫຍັງ|ດີ|.", "Je ne sais pas quoi étudier."),
   ("C", "ເຈົ້າ|ມັກ|ຫຍັງ|?", "Qu'est-ce que tu aimes ?"),
   ("K", "ມັກ|ຄອມພິວເຕີ|.", "J'aime l'informatique."),
   ("C", "ເຈົ້າ|ຄວນ|ຮຽນ|ສິ່ງ|ທີ່|ເຈົ້າ|ມັກ|.", "Tu devrais étudier ce que tu aimes."),
   ("K", "ແຕ່|ພໍ່|ຢາກ|ໃຫ້|ຂ້ອຍ|ເປັນ|ທ່ານໝໍ|.", "Mais papa veut que je sois médecin."),
   ("C", "ລອງ|ລົມ|ກັບ|ພໍ່|ເບິ່ງ|.", "Essaie d'en parler avec lui.")],
  [("Qu'aime Kèo ?", "L'informatique."), ("Que conseille Clara ?", "D'étudier ce qu'il aime et d'en parler à son père.")],
  [("ຄວນ", "devoir (conseil), il faudrait"), ("ບໍ່|ຄວນ", "il ne faudrait pas"), ("ລອງ|…|ເບິ່ງ", "essaie de…"), ("ດີ|ກວ່າ", "il vaut mieux"), ("ສິ່ງ|ທີ່", "ce que"), ("ແນະນຳ", "conseiller, recommander")],
  "donner un conseil", [("ເຈົ້າ|ຄວນ|…", "tu devrais…"), ("ລອງ|ລົມ|ເບິ່ງ", "essaie d'en parler"), ("ໄປ|ຫາ|ທ່ານໝໍ|ດີ|ກວ່າ", "il vaut mieux aller voir un médecin")],
  ["Quelles structures servent à conseiller ?"], "ຄວນ + verbe (tu devrais), ລອງ + verbe + ເບິ່ງ (essaie de), … ດີກວ່າ (il vaut mieux).",
  "ຄວນ et ລອງ…ເບິ່ງ.",
  [("Tu devrais te reposer.", "ເຈົ້າ|ຄວນ|ພັກຜ່ອນ|."), ("Essaie d'en parler.", "ລອງ|ລົມ|ເບິ່ງ|."), ("Il vaut mieux y aller.", "ໄປ|ດີ|ກວ່າ|.")],
  ["Donne 5 conseils à un ami qui arrive au Laos."], "Demande un conseil à un natif sur un vrai problème et discutez-en."),
L(74, "Hypothèses", "Dire ce que tu ferais si…", "Rêves de loterie au café.",
  [("N", "ຖ້າ|ຖືກ|ເລກ|,|ເຈົ້າ|ຈະ|ເຮັດ|ຫຍັງ|?", "Si tu gagnais à la loterie, tu ferais quoi ?"),
   ("C", "ຖ້າ|ຂ້ອຍ|ມີ|ເງິນ|ຫຼາຍ|,|ຂ້ອຍ|ຈະ|ຊື້|ເຮືອນ|ຢູ່|ລາວ|.", "Si j'avais beaucoup d'argent, j'achèterais une maison au Laos."),
   ("N", "ຂ້ອຍ|ຈະ|ພາ|ພໍ່|ແມ່|ໄປ|ທ່ຽວ|ຮອບ|ໂລກ|.", "Moi, j'emmènerais mes parents faire le tour du monde."),
   ("C", "ສົມມຸດ|ວ່າ|ເຮົາ|ໄປ|ນຳ|ກັນ|ເດ|?", "Et si on partait ensemble ?")],
  [("Que ferait Clara ?", "Acheter une maison au Laos."), ("Et Noy ?", "Emmener ses parents faire le tour du monde.")],
  [("ຖ້າ|…|ຈະ", "si… alors (hypothèse)"), ("ສົມມຸດ|ວ່າ", "supposons que"), ("ຖືກ|ເລກ", "gagner à la loterie"), ("ພາ", "emmener"), ("ຮອບ|ໂລກ", "tour du monde"), ("ຝັນ", "rêver")],
  "les hypothèses", [("ຖ້າ|ມີ|ເງິນ|ຈະ|ຊື້|ເຮືອນ", "si j'avais de l'argent, j'achèterais une maison"), ("ສົມມຸດ|ວ່າ|…", "supposons que…")],
  ["Le lao distingue-t-il « si j'ai » et « si j'avais » ?"], "Le lao n'a pas de conditionnel : ຖ້າ… ຈະ… couvre le réel et l'hypothétique. Le contexte (ou ສົມມຸດວ່າ) montre que c'est imaginaire.",
  "ຖ້າ et ຈະ.",
  [("Si j'avais de l'argent…", "ຖ້າ|ຂ້ອຍ|ມີ|ເງິນ|…"), ("J'achèterais une maison.", "ຂ້ອຍ|ຈະ|ຊື້|ເຮືອນ|."), ("Supposons que…", "ສົມມຸດ|ວ່າ|…")],
  ["Écris 5 phrases « Si j'étais… je… »."], "Joue avec un natif à « Qu'est-ce que tu ferais si… »."),
L(75, "Relations", "Parler d'amitié, de couple et de conflits.", "Noy parle de son couple.",
  [("C", "ເຈົ້າ|ກັບ|ແຟນ|ຄືນດີ|ກັນ|ແລ້ວ|ບໍ|?", "Toi et ton copain, vous vous êtes réconciliés ?"),
   ("N", "ຄືນດີ|ແລ້ວ|.|ພວກເຮົາ|ລົມ|ກັນ|ດົນ|.", "Oui. On a longtemps parlé."),
   ("C", "ດີ|ແລ້ວ|.|ຄວາມ|ເຂົ້າໃຈ|ກັນ|ສຳຄັນ|.", "Tant mieux. Se comprendre, c'est important."),
   ("N", "ແມ່ນ|.|ລາວ|ເປັນ|ຄົນ|ດີ|.", "Oui. C'est quelqu'un de bien.")],
  [("Noy et son copain se sont-ils réconciliés ?", "Oui, après une longue discussion.")],
  [("ຄືນດີ", "se réconcilier"), ("ຜິດ|ກັນ", "se disputer, être en froid"), ("ຄວາມ|ເຂົ້າໃຈ", "compréhension"), ("ໄວ້ໃຈ", "faire confiance"), ("ເພື່ອນ|ສະໜິດ", "ami proche"), ("ສຳຄັນ", "important"),
   ("ກັນ", "(réciproque) l'un l'autre")],
  "ກັນ réciproque et ຄວາມ + verbe", [("ລົມ|ກັນ", "se parler"), ("ຮັກ|ກັນ", "s'aimer"), ("ຄວາມ|ຮັກ", "l'amour"), ("ຄວາມ|ສຸກ", "le bonheur")],
  ["Que fait ກັນ après un verbe ? Et ຄວາມ devant un verbe ?"], "Verbe + ກັນ = action réciproque (se parler). ຄວາມ + verbe/adjectif = nom abstrait (ຄວາມຮັກ = l'amour).",
  "ກັນ et ຄວາມ.",
  [("Vous vous êtes réconciliés ?", "ຄືນດີ|ກັນ|ແລ້ວ|ບໍ|?"), ("Se comprendre, c'est important.", "ຄວາມ|ເຂົ້າໃຈ|ກັນ|ສຳຄັນ|."), ("C'est quelqu'un de bien.", "ລາວ|ເປັນ|ຄົນ|ດີ|.")],
  ["Écris 6 noms abstraits avec ຄວາມ et utilise-les dans des phrases."], "Parle à un natif de ce qui fait une bonne amitié pour vous."),
L(76, "La pagode", "Se comporter et parler correctement à la pagode.", "Mme Boua emmène Clara au temple.",
  [("B", "ກ່ອນ|ເຂົ້າ|ໄປ|ຕ້ອງ|ຖອດ|ເກີບ|.", "Avant d'entrer, il faut enlever ses chaussures."),
   ("B", "ນຸ່ງ|ສິ້ນ|ແລະ|ເສື້ອ|ແຂນ|ຍາວ|.", "On porte un sinh et des manches longues."),
   ("C", "ຂ້ອຍ|ຕ້ອງ|ກາບ|ພະ|ບໍ|?", "Je dois me prosterner devant le Bouddha ?"),
   ("B", "ກາບ|ສາມ|ເທື່ອ|.|ແລ້ວ|ນັ່ງ|ພັບ|ພຽບ|.", "Trois fois. Puis on s'assoit les jambes repliées sur le côté.")],
  [("Que faut-il faire avant d'entrer ?", "Enlever ses chaussures."), ("Combien de fois se prosterne-t-on ?", "Trois fois.")],
  [("ວັດ", "pagode, temple"), ("ພະ", "Bouddha ; moine"), ("ຖອດ|ເກີບ", "enlever ses chaussures"), ("ກາບ", "se prosterner"), ("ນັ່ງ|ພັບ|ພຽບ", "s'asseoir jambes repliées", "[À VÉRIFIER]"),
   ("ທຳບຸນ", "faire des mérites"), ("ໃສ່ບາດ", "faire l'offrande aux moines"), ("ນຸ່ງ", "porter (vêtement)")],
  "les consignes avec ຕ້ອງ et ຫ້າມ", [("ຕ້ອງ|ຖອດ|ເກີບ", "il faut enlever ses chaussures"), ("ຫ້າມ|ຊີ້|ຕີນ|ໃສ່|ພະ", "interdit de pointer les pieds vers le Bouddha")],
  [], "ຕ້ອງ = obligation, ຫ້າມ = interdiction. À la pagode : pas de pieds pointés vers le Bouddha ou les moines, tête toujours plus basse qu'eux.",
  "les consignes.",
  [("Il faut enlever ses chaussures.", "ຕ້ອງ|ຖອດ|ເກີບ|."), ("Je dois me prosterner ?", "ຕ້ອງ|ກາບ|ບໍ|?"), ("Je vais faire des mérites.", "ຂ້ອຍ|ຈະ|ໄປ|ທຳບຸນ|.")],
  ["Écris les 5 règles de comportement à la pagode."], "Visite une pagode lao (en France il y en a) ou explique les règles à un natif pour vérification.",
  cult="Les femmes ne doivent jamais toucher un moine ni lui tendre directement un objet : on le pose devant lui ou on passe par un homme."),
L(77, "S'adresser à un moine", "Saluer, offrir et remercier un moine avec le vocabulaire approprié.", "Clara fait l'offrande du matin.",
  [("B", "ຕອນເຊົ້າ|ພະ|ຈະ|ຍ່າງ|ມາ|ບິນທະບາດ|.", "Le matin, les moines passent pour l'aumône."),
   ("B", "ເຮົາ|ຄຸເຂົ່າ|ແລ້ວ|ໃສ່|ເຂົ້າໜຽວ|ໃສ່|ບາດ|.", "On s'agenouille et on met du riz gluant dans le bol."),
   ("C", "ຕ້ອງ|ເວົ້າ|ຫຍັງ|ບໍ|?", "Il faut dire quelque chose ?"),
   ("B", "ບໍ່|ຕ້ອງ|ເວົ້າ|.|ພະ|ຈະ|ໃຫ້|ພອນ|.", "Pas besoin de parler. Le moine donne sa bénédiction.")],
  [("Que fait-on le matin ?", "L'offrande de riz gluant aux moines."), ("Faut-il parler ?", "Non, le moine bénit.")],
  [("ພະສົງ", "moine (collectif)"), ("ບິນທະບາດ", "quête de l'aumône", "[À VÉRIFIER]"), ("ໃສ່ບາດ", "donner l'aumône"), ("ຄຸເຂົ່າ", "s'agenouiller"), ("ໃຫ້|ພອນ", "bénir"),
   ("ສາທຸ", "« sathou » (amen)"), ("ຈັງຫັນ", "repas (d'un moine)", "[À VÉRIFIER]"), ("ຈຳວັດ", "résider (moine)", "[À VÉRIFIER]")],
  "le vocabulaire réservé aux moines", [("ພະ|ຈັງຫັນ", "le moine mange"), ("ພະ|ຈຳວັດ|ຢູ່|ວັດ|ນີ້", "le moine réside dans ce temple")],
  ["Pourquoi utilise-t-on d'autres verbes pour les moines ?"], "Pour les moines, certains verbes courants sont remplacés par des verbes respectueux (ຈັງຫັນ pour manger, ຈຳວັດ pour résider…). On dit ສາທຸ en réponse à une bénédiction. [À VÉRIFIER entièrement avec un natif pratiquant]",
  "ສາທຸ en fin de bénédiction.",
  [("Le moine donne sa bénédiction.", "ພະ|ໃຫ້|ພອນ|."), ("Sathou.", "ສາທຸ|."), ("On s'agenouille.", "ຄຸເຂົ່າ|.")],
  ["Décris le déroulé de l'offrande du matin en 6 phrases."], "Demande à un aîné lao comment il parle aux moines et compare avec la leçon."),
L(78, "Travail (2)", "Passer un entretien simple : compétences et expériences.", "Clara postule dans une école.",
  [("W", "ເລົ່າ|ກ່ຽວກັບ|ຕົວເອງ|ແດ່|.", "Parlez-moi de vous."),
   ("C", "ຂ້ອຍ|ເປັນ|ຄູ|ມາ|ຫ້າ|ປີ|ແລ້ວ|.", "Je suis enseignante depuis cinq ans."),
   ("W", "ເປັນ|ຫຍັງ|ຢາກ|ເຮັດວຽກ|ຢູ່|ນີ້|?", "Pourquoi voulez-vous travailler ici ?"),
   ("C", "ເພາະວ່າ|ໂຮງຮຽນ|ນີ້|ມີ|ຊື່ສຽງ|ດີ|.", "Parce que cette école a une bonne réputation."),
   ("W", "ເຈົ້າ|ມີ|ຈຸດ|ອ່ອນ|ຫຍັງ|ບໍ|?", "Quels sont vos points faibles ?")],
  [("Depuis quand Clara enseigne-t-elle ?", "Cinq ans."), ("Pourquoi veut-elle cette école ?", "Bonne réputation.")],
  [("ສະໝັກ|ວຽກ", "postuler"), ("ປະສົບການ", "expérience"), ("ຄວາມ|ສາມາດ", "compétence"), ("ຊື່ສຽງ", "réputation"), ("ຈຸດ|ແຂງ", "point fort"), ("ຈຸດ|ອ່ອນ", "point faible"),
   ("ເງິນເດືອນ", "salaire"), ("ຕົວເອງ", "soi-même")],
  "parler de soi au travail", [("ຂ້ອຍ|ມີ|ປະສົບການ|…|ປີ", "j'ai… ans d'expérience"), ("ຈຸດ|ແຂງ|ຂອງ|ຂ້ອຍ|ແມ່ນ|…", "mon point fort est…")],
  [], "Pour un entretien : présenter son expérience (ມາ…ປີແລ້ວ), ses points forts et ses motivations (ເພາະວ່າ).",
  "les questions classiques d'entretien.",
  [("Je suis enseignante depuis cinq ans.", "ຂ້ອຍ|ເປັນ|ຄູ|ມາ|ຫ້າ|ປີ|ແລ້ວ|."), ("Mon point fort, c'est la patience.", "ຈຸດ|ແຂງ|ຂອງ|ຂ້ອຍ|ແມ່ນ|ຄວາມ|ອົດທົນ|."), ("Parlez-moi de vous.", "ເລົ່າ|ກ່ຽວກັບ|ຕົວເອງ|ແດ່|.")],
  ["Prépare tes réponses à 5 questions d'entretien."], "Fais un faux entretien d'embauche avec un natif."),
L(79, "L'argent", "Gérer une situation à la banque : ouvrir un compte, retirer, changer.", "Clara à la banque.",
  [("C", "ຂ້ອຍ|ຢາກ|ເປີດ|ບັນຊີ|.", "Je voudrais ouvrir un compte."),
   ("W", "ມີ|ໜັງສືຜ່ານແດນ|ບໍ|?", "Vous avez votre passeport ?"),
   ("C", "ມີ|.|ແລ້ວ|ແລກ|ເງິນ|ເອີໂຣ|ໄດ້|ບໍ|?", "Oui. Et je peux changer des euros ?"),
   ("W", "ໄດ້|.|ອັດຕາ|ມື້ນີ້|ຢູ່|ໜ້າ|ຈໍ|.", "Oui. Le taux du jour est à l'écran.")],
  [("Que veut faire Clara ?", "Ouvrir un compte et changer des euros.")],
  [("ບັນຊີ", "compte"), ("ເປີດ|ບັນຊີ", "ouvrir un compte"), ("ຖອນ|ເງິນ", "retirer de l'argent"), ("ຝາກ|ເງິນ", "déposer de l'argent"), ("ແລກ|ເງິນ", "changer de l'argent"),
   ("ອັດຕາ", "taux"), ("ໜັງສືຜ່ານແດນ", "passeport"), ("ບັດ", "carte")],
  "le vocabulaire administratif", [("ຂໍ|ເປີດ|ບັນຊີ", "demander l'ouverture d'un compte"), ("ຕ້ອງ|ໃຊ້|ເອກະສານ|ຫຍັງ|ແດ່|?", "il faut quels documents ?")],
  [], "Dans l'administration, on utilise des mots plus formels (ເອກະສານ, ໜັງສືຜ່ານແດນ) et la demande polie ຂໍ.",
  "les mots de la banque.",
  [("Je voudrais ouvrir un compte.", "ຂ້ອຍ|ຢາກ|ເປີດ|ບັນຊີ|."), ("Il faut quels documents ?", "ຕ້ອງ|ໃຊ້|ເອກະສານ|ຫຍັງ|ແດ່|?"), ("Je voudrais changer des euros.", "ຂ້ອຍ|ຢາກ|ແລກ|ເງິນ|ເອີໂຣ|.")],
  ["Écris le dialogue d'un retrait d'argent qui pose problème."], "Joue une scène à la banque avec un natif."),
L(80, "La ville et la campagne", "Comparer deux modes de vie de façon nuancée.", "Week-end au village de M. Somsak.",
  [("C", "ຢູ່|ບ້ານ|ນອກ|ງຽບ|ກວ່າ|ໃນ|ເມືອງ|ຫຼາຍ|.", "Au village, c'est bien plus calme qu'en ville."),
   ("S", "ແມ່ນ|,|ອາກາດ|ກໍ|ດີ|ກວ່າ|.|ແຕ່|ບໍ່|ສະດວກ|ເທົ່າ|.", "Oui, et l'air est meilleur. Mais c'est moins pratique."),
   ("C", "ຄົນ|ໜຸ່ມ|ຍ້າຍ|ໄປ|ເມືອງ|ຫຼາຍ|ບໍ|?", "Beaucoup de jeunes partent en ville ?"),
   ("S", "ຫຼາຍ|.|ເພາະ|ໃນ|ເມືອງ|ມີ|ວຽກ|ຫຼາຍ|ກວ່າ|.", "Beaucoup. Parce qu'en ville il y a plus de travail.")],
  [("Qu'est-ce qui est mieux à la campagne ?", "Le calme et l'air."), ("Pourquoi les jeunes partent-ils ?", "Plus de travail en ville.")],
  [("ບ້ານ|ນອກ", "campagne, village"), ("ໃນ|ເມືອງ", "en ville"), ("ງຽບ", "calme, silencieux"), ("ສະດວກ", "pratique"), ("ບໍ່|…|ເທົ່າ", "moins… que"), ("ຍ້າຍ", "déménager"),
   ("ຄົນ|ໜຸ່ມ", "les jeunes")],
  "comparaisons nuancées", [("ງຽບ|ກວ່າ|ຫຼາຍ", "beaucoup plus calme"), ("ບໍ່|ສະດວກ|ເທົ່າ", "pas aussi pratique"), ("ດີ|ເທົ່າ|ກັນ", "aussi bien l'un que l'autre")],
  ["Comment dit-on « moins… que » et « aussi… que » ?"], "Adj + ກວ່າ (plus), ບໍ່ + adj + ເທົ່າ (moins / pas autant), adj + ເທົ່າກັນ (autant). ຫຼາຍ après ກວ່າ = beaucoup plus.",
  "ກວ່າ, ເທົ່າ, ເທົ່າກັນ.",
  [("C'est bien plus calme.", "ງຽບ|ກວ່າ|ຫຼາຍ|."), ("C'est moins pratique.", "ບໍ່|ສະດວກ|ເທົ່າ|."), ("Il y a plus de travail en ville.", "ໃນ|ເມືອງ|ມີ|ວຽກ|ຫຼາຍ|ກວ່າ|.")],
  ["Compare deux villes que tu connais en 8 phrases nuancées."], "Discute avec un natif : ville ou campagne ?"),
L(81, "Les particules d'attitude", "Faire passer une émotion par la fin de phrase.", "Une soirée entre amis.",
  [("N", "ມ່ວນ|ແທ້|ນໍ|!", "Qu'est-ce qu'on s'amuse !"),
   ("K", "ເອົາ|ອີກ|ຈອກ|ບໍ|ເດ້|?", "Allez, encore un verre ?"),
   ("C", "ພໍ|ແລ້ວ|ແຫຼະ|.", "Ça suffit, vraiment."),
   ("K", "ໂອ້ຍ|,|ອີກ|ຈອກ|ດຽວ|ສາ|!", "Oh, juste un dernier quoi !")],
  [("Clara veut-elle encore boire ?", "Non, elle dit que ça suffit.")],
  [("ນໍ", "(exclamation, enthousiasme)", "[À VÉRIFIER]"), ("ເດ້", "(insistance, invitation)"), ("ແຫຼະ", "(affirmation ferme)"), ("ສາ", "(impatience, insistance)"), ("ເນາະ", "(connivence)"), ("ພໍ|ແລ້ວ", "ça suffit")],
  "les particules expressives", [("ມ່ວນ|ແທ້|ນໍ", "c'est vraiment génial !"), ("ພໍ|ແລ້ວ|ແຫຼະ", "ça suffit, je t'assure")],
  ["Quelle émotion porte chaque particule ?"], "Les particules donnent la couleur émotionnelle : enthousiasme, insistance, fermeté, impatience. Elles sont typiques de l'oral. [À VÉRIFIER : nuances régionales]",
  "l'intonation des particules.",
  [("Ça suffit, vraiment.", "ພໍ|ແລ້ວ|ແຫຼະ|."), ("Encore un verre ?", "ເອົາ|ອີກ|ຈອກ|ບໍ|?"), ("C'est génial !", "ມ່ວນ|ແທ້|ນໍ|!")],
  ["Réécris 5 phrases neutres avec une particule expressive."], "Note toutes les particules dans 10 minutes d'une vidéo lao et demande leur sens à un natif."),
L(82, "Écouter une chanson", "Comprendre et chanter le refrain d'une chanson lao.", "Kèo fait écouter une chanson à Clara.",
  [("K", "ເພງ|ນີ້|ດັງ|ຫຼາຍ|ຢູ່|ລາວ|.", "Cette chanson est très connue au Laos."),
   ("C", "ເວົ້າ|ກ່ຽວກັບ|ຫຍັງ|?", "Elle parle de quoi ?"),
   ("K", "ກ່ຽວກັບ|ຄວາມ|ຮັກ|ແລະ|ການ|ຄິດຮອດ|ບ້ານ|.", "D'amour et du mal du pays."),
   ("C", "ສອນ|ຂ້ອຍ|ຮ້ອງ|ແດ່|!", "Apprends-moi à la chanter !")],
  [("De quoi parle la chanson ?", "D'amour et du mal du pays.")],
  [("ເພງ", "chanson"), ("ຮ້ອງເພງ", "chanter"), ("ນັກຮ້ອງ", "chanteur"), ("ດັງ", "célèbre ; fort (son)"), ("ເນື້ອ|ເພງ", "paroles"), ("ຄິດຮອດ|ບ້ານ", "avoir le mal du pays"),
   ("ທຳນອງ", "mélodie")],
  "ການ + verbe", [("ການ|ຄິດຮອດ|ບ້ານ", "le mal du pays"), ("ການ|ຮຽນ", "l'apprentissage, les études")],
  ["Quelle différence entre ການ et ຄວາມ ?"], "ການ + verbe = l'action (ການຮຽນ = les études) ; ຄວາມ + verbe/adjectif = l'état, le sentiment (ຄວາມຮັກ = l'amour).",
  "les paroles du refrain.",
  [("Elle parle de quoi ?", "ເວົ້າ|ກ່ຽວກັບ|ຫຍັງ|?"), ("Apprends-moi à la chanter.", "ສອນ|ຂ້ອຍ|ຮ້ອງ|ແດ່|."), ("Cette chanson est très connue.", "ເພງ|ນີ້|ດັງ|ຫຼາຍ|.")],
  ["Recopie le refrain d'une chanson lao et traduis-le."], "Choisis une chanson lao populaire, apprends le refrain et chante-le à un natif."),
L(83, "Regarder une vidéo", "Résumer une courte vidéo lao.", "Clara regarde une vidéo de cuisine.",
  [("N", "ເບິ່ງ|ວິດີໂອ|ນີ້|ແລ້ວ|ເລົ່າ|ໃຫ້|ຟັງ|ແດ່|.", "Regarde cette vidéo et raconte-la-moi."),
   ("C", "ເຂົາ|ສອນ|ເຮັດ|ຕຳໝາກຫຸ່ງ|.", "Ils apprennent à faire une salade de papaye."),
   ("C", "ທຳອິດ|ຕຳ|ໝາກເຜັດ|ກັບ|ກະທຽມ|,|ແລ້ວ|ໃສ່|ໝາກຫຸ່ງ|.", "D'abord on pile le piment avec l'ail, puis on ajoute la papaye."),
   ("N", "ເກັ່ງ|!|ເຂົ້າໃຈ|ໝົດ|ເລີຍ|.", "Bravo ! Tu as tout compris.")],
  [("Que montre la vidéo ?", "Comment faire une salade de papaye.")],
  [("ວິດີໂອ", "vidéo"), ("ເລົ່າ|ໃຫ້|ຟັງ", "raconter (à quelqu'un)"), ("ສະຫຼຸບ", "résumer"), ("ຕຳ", "piler"), ("ກະທຽມ", "ail"), ("ເຂົ້າໃຈ|ໝົດ", "tout comprendre")],
  "résumer", [("ສະຫຼຸບ|ແລ້ວ|…", "en résumé…"), ("ເລື່ອງ|ນີ້|ເວົ້າ|ກ່ຽວກັບ|…", "cette histoire parle de…")],
  [], "Pour résumer : sujet (ເວົ້າກ່ຽວກັບ), étapes principales (ທຳອິດ, ແລ້ວ), conclusion (ສະຫຼຸບແລ້ວ).",
  "les mots-clés et les étapes, pas chaque mot.",
  [("En résumé…", "ສະຫຼຸບ|ແລ້ວ|…"), ("Elle parle de cuisine.", "ເວົ້າ|ກ່ຽວກັບ|ອາຫານ|."), ("J'ai tout compris.", "ເຂົ້າໃຈ|ໝົດ|ເລີຍ|.")],
  ["Résume par écrit une vidéo lao de 3 minutes."], "Regarde une vidéo lao et résume-la oralement à un natif."),
L(84, "Lire un article simple", "Comprendre et résumer un article de presse facile.", "M. Somsak lit le journal.",
  [("S", "ມື້ນີ້|ໜັງສືພິມ|ລົງ|ຂ່າວ|ກ່ຽວກັບ|ລົດໄຟ|ລາວ|-|ຈີນ|.", "Aujourd'hui, le journal parle du train Laos-Chine."),
   ("C", "ຂ່າວ|ເວົ້າ|ວ່າ|ແນວໃດ|?", "Que dit l'article ?"),
   ("S", "ນັກທ່ອງທ່ຽວ|ເພີ່ມ|ຂຶ້ນ|ຫຼາຍ|.", "Le nombre de touristes a beaucoup augmenté."),
   ("C", "ດີ|ສຳລັບ|ເສດຖະກິດ|ເນາະ|.", "C'est bien pour l'économie.")],
  [("De quoi parle l'article ?", "Du train Laos-Chine et de la hausse du tourisme.")],
  [("ໜັງສືພິມ", "journal"), ("ຂ່າວ", "nouvelle, info"), ("ລົງ|ຂ່າວ", "publier une info"), ("ເພີ່ມ|ຂຶ້ນ", "augmenter"), ("ຫຼຸດ|ລົງ", "diminuer"), ("ເສດຖະກິດ", "économie"),
   ("ນັກທ່ອງທ່ຽວ", "touriste")],
  "augmenter, diminuer", [("ເພີ່ມ|ຂຶ້ນ", "augmenter"), ("ຫຼຸດ|ລົງ", "diminuer"), ("ລາຄາ|ສູງ|ຂຶ້ນ", "les prix montent")],
  ["Quel rôle jouent ຂຶ້ນ et ລົງ ?"], "ຂຶ້ນ (monter) et ລົງ (descendre) après un verbe indiquent une hausse ou une baisse.",
  "les chiffres et les verbes de tendance.",
  [("Les prix augmentent.", "ລາຄາ|ສູງ|ຂຶ້ນ|."), ("Que dit l'article ?", "ຂ່າວ|ເວົ້າ|ວ່າ|ແນວໃດ|?"), ("C'est bien pour l'économie.", "ດີ|ສຳລັບ|ເສດຖະກິດ|.")],
  ["Lis un article lao simple en ligne et écris un résumé de 5 phrases."], "Explique un article lao à un natif et discutez-en."),
L(85, "Écrire un message formel", "Écrire à une administration ou à un professeur.", "Clara écrit pour un visa.",
  [("C", "ຮຽນ|ເຖິງ|ຫົວໜ້າ|ພະແນກ|.", "À l'attention du chef de service."),
   ("C", "ຂ້າພະເຈົ້າ|ຂໍ|ສະເໜີ|ຕໍ່|ວີຊາ|ຕື່ມ|ອີກ|ໜຶ່ງ|ປີ|.", "Je sollicite le renouvellement de mon visa pour un an."),
   ("C", "ຂໍ|ສະແດງ|ຄວາມ|ນັບຖື|.", "Veuillez agréer mes respectueuses salutations.")],
  [("Que demande Clara ?", "Le renouvellement de son visa pour un an.")],
  [("ຮຽນ|ເຖິງ", "à l'attention de"), ("ຂ້າພະເຈົ້າ", "je (formel, écrit)"), ("ສະເໜີ", "proposer, solliciter"), ("ຕໍ່|ວີຊາ", "renouveler un visa"), ("ຫົວໜ້າ", "chef"),
   ("ພະແນກ", "service, département"), ("ຂໍ|ສະແດງ|ຄວາມ|ນັບຖື", "salutations respectueuses")],
  "le registre écrit formel", [("ຂ້າພະເຈົ້າ", "je (formel)"), ("ຮຽນ|ເຖິງ", "à l'attention de")],
  [], "À l'écrit officiel, ຂ້ອຍ devient ຂ້າພະເຈົ້າ, on ouvre par ຮຽນເຖິງ et on clôt par ຂໍສະແດງຄວາມນັບຖື. [À VÉRIFIER avec un modèle officiel]",
  "les formules d'ouverture et de clôture.",
  [("À l'attention du directeur.", "ຮຽນ|ເຖິງ|ຫົວໜ້າ|."), ("Je sollicite…", "ຂ້າພະເຈົ້າ|ຂໍ|ສະເໜີ|…"), ("Salutations respectueuses.", "ຂໍ|ສະແດງ|ຄວາມ|ນັບຖື|.")],
  ["Écris une lettre formelle de 8 lignes pour une demande administrative."], "Fais corriger ta lettre formelle par un natif."),
L(86, "L'histoire du Laos", "Présenter un fait historique simple.", "Visite du That Luang avec M. Somsak.",
  [("S", "ທາດຫຼວງ|ສ້າງ|ຂຶ້ນ|ຫຼາຍ|ຮ້ອຍ|ປີ|ມາ|ແລ້ວ|.", "Le That Luang a été construit il y a plusieurs siècles."),
   ("S", "ເປັນ|ສັນຍາລັກ|ຂອງ|ຊາດ|ລາວ|.", "C'est le symbole de la nation lao."),
   ("C", "ໃຜ|ເປັນ|ຄົນ|ສ້າງ|?", "Qui l'a fait construire ?"),
   ("S", "ພະເຈົ້າ|ໄຊເສດຖາ|ໃຫ້|ສ້າງ|.", "Le roi Setthathirath.")],
  [("Qu'est-ce que le That Luang ?", "Le symbole de la nation lao."), ("Qui l'a fait construire ?", "Le roi Setthathirath.")],
  [("ປະຫວັດສາດ", "histoire (discipline)"), ("ສ້າງ", "construire"), ("ສັນຍາລັກ", "symbole"), ("ຊາດ", "nation"), ("ພະເຈົ້າ|ແຜ່ນດິນ", "roi"), ("ສະຕະວັດ", "siècle"),
   ("ອານາຈັກ", "royaume"), ("ລ້ານຊ້າງ", "Lane Xang (royaume)")],
  "le récit au passé lointain", [("…|ມາ|ແລ້ວ", "il y a…"), ("ໃນ|ສະຕະວັດ|ທີ|ສິບຫົກ", "au XVIe siècle")],
  [], "Le passé lointain s'exprime avec la date ou la durée (ຫຼາຍຮ້ອຍປີມາແລ້ວ) ; le verbe ne change pas. [Faits historiques À VÉRIFIER]",
  "les dates et les noms propres.",
  [("Il a été construit il y a des siècles.", "ສ້າງ|ຂຶ້ນ|ຫຼາຍ|ຮ້ອຍ|ປີ|ມາ|ແລ້ວ|."), ("C'est le symbole de la nation.", "ເປັນ|ສັນຍາລັກ|ຂອງ|ຊາດ|."), ("Qui l'a construit ?", "ໃຜ|ສ້າງ|?")],
  ["Présente un monument lao en 6 phrases."], "Demande à un natif de te raconter un épisode de l'histoire du Laos."),
L(87, "Géographie et régions", "Présenter une région du Laos.", "Clara prépare un voyage dans le Sud.",
  [("C", "ພາກໃຕ້|ມີ|ຫຍັງ|ໜ້າ|ທ່ຽວ|?", "Qu'y a-t-il à voir dans le Sud ?"),
   ("N", "ມີ|ສີ່ພັນ|ດອນ|ແລະ|ນ້ຳຕົກ|ງາມ|ໆ|.", "Il y a les 4 000 îles et de belles cascades."),
   ("C", "ອາກາດ|ເປັນ|ແນວໃດ|?", "Et le climat ?"),
   ("N", "ຮ້ອນ|ກວ່າ|ພາກເໜືອ|.|ພາກເໜືອ|ມີ|ພູ|ຫຼາຍ|.", "Plus chaud que le Nord. Le Nord est montagneux.")],
  [("Qu'y a-t-il à voir dans le Sud ?", "Les 4 000 îles et des cascades."), ("Comment est le Nord ?", "Montagneux et plus frais.")],
  [("ພາກເໜືອ", "le Nord"), ("ພາກໃຕ້", "le Sud"), ("ພາກກາງ", "le Centre"), ("ແຂວງ", "province"), ("ນ້ຳຕົກ", "cascade"), ("ໜ້າ|ທ່ຽວ", "qui vaut le détour"), ("ດອນ", "île (de fleuve)")],
  "ໜ້າ + verbe", [("ໜ້າ|ທ່ຽວ", "à visiter"), ("ໜ້າ|ກິນ", "appétissant"), ("ໜ້າ|ຮັກ", "mignon (à aimer)")],
  ["Que signifie ໜ້າ devant un verbe ?"], "ໜ້າ + verbe = qui donne envie de… (ໜ້າທ່ຽວ, ໜ້າກິນ, ໜ້າຮັກ).",
  "les noms de régions.",
  [("Qu'y a-t-il à voir ?", "ມີ|ຫຍັງ|ໜ້າ|ທ່ຽວ|?"), ("Le Nord est montagneux.", "ພາກເໜືອ|ມີ|ພູ|ຫຼາຍ|."), ("C'est plus chaud.", "ຮ້ອນ|ກວ່າ|.")],
  ["Présente une province lao en 8 phrases."], "Présente à un natif la région du Laos que tu aimerais visiter."),
L(88, "Lao et thaï", "Repérer les mots proches et les faux amis entre lao et thaï.", "Kèo regarde une série thaïe.",
  [("C", "ເຈົ້າ|ເຂົ້າໃຈ|ພາສາໄທ|ບໍ|?", "Tu comprends le thaï ?"),
   ("K", "ເຂົ້າໃຈ|ເກືອບ|ໝົດ|.|ຄ້າຍ|ກັນ|ຫຼາຍ|.", "Presque tout. Ça se ressemble beaucoup."),
   ("C", "ມີ|ຄຳ|ທີ່|ຕ່າງ|ກັນ|ບໍ|?", "Il y a des mots différents ?"),
   ("K", "ມີ|.|ເຊັ່ນ|ຄຳ|ວ່າ|«|ບໍ່|»|ພາສາໄທ|ແມ່ນ|«|ໄມ່|»|.", "Oui. Par exemple « non » se dit autrement en thaï.")],
  [("Kèo comprend-il le thaï ?", "Presque tout.")],
  [("ພາສາໄທ", "thaï (langue)"), ("ຄ້າຍ|ກັນ", "se ressembler"), ("ຕ່າງ|ກັນ", "être différent"), ("ເຊັ່ນ", "par exemple"), ("ຄຳ|ຢືມ", "mot emprunté")],
  "ressemblances et différences", [("ຄ້າຍ|ກັນ|ຫຼາຍ", "très proches"), ("ຕ່າງ|ກັນ|ໜ້ອຍ|ໜຶ່ງ", "un peu différents")],
  [], "Le lao et le thaï sont très proches à l'oral, avec des alphabets différents et de nombreux mots courants distincts. Ne remplace jamais un mot lao par sa forme thaïe. [Exemples À VÉRIFIER]",
  "les mots proches entre lao et thaï.",
  [("Ça se ressemble beaucoup.", "ຄ້າຍ|ກັນ|ຫຼາຍ|."), ("C'est différent.", "ຕ່າງ|ກັນ|."), ("Par exemple…", "ເຊັ່ນ|…")],
  ["Fais une liste de 10 mots qui diffèrent entre lao et thaï avec un natif."], "Regarde 5 minutes d'une série thaïe avec un natif lao et note les différences qu'il relève."),
L(89, "Improviser", "Tenir 10 minutes sur un sujet tiré au hasard, avec des stratégies pour gagner du temps.", "Jeu de conversation entre amis.",
  [("N", "ຫົວຂໍ້|ແມ່ນ|«|ອາຫານ|»|.|ເວົ້າ|ສາມ|ນາທີ|!", "Le sujet, c'est « la nourriture ». Parle trois minutes !"),
   ("C", "ເອີ|…|ຂໍ|ຄິດ|ແປັບ|ໜຶ່ງ|.", "Euh… laisse-moi réfléchir un instant."),
   ("C", "ຄື|ວ່າ|…|ສຳລັບ|ຂ້ອຍ|,|ອາຫານ|ລາວ|ແມ່ນ|…", "Disons que… pour moi, la cuisine lao, c'est…"),
   ("N", "ສືບຕໍ່|!", "Continue !")],
  [("Quel est le sujet ?", "La nourriture."), ("Comment Clara gagne-t-elle du temps ?", "Avec ເອີ, ຂໍຄິດແປັບໜຶ່ງ, ຄືວ່າ.")],
  [("ຫົວຂໍ້", "sujet, thème"), ("ເອີ", "euh"), ("ຂໍ|ຄິດ|ແປັບ|ໜຶ່ງ", "laisse-moi réfléchir"), ("ຄື|ວ່າ", "c'est-à-dire, disons que"), ("ສຳລັບ|ຂ້ອຍ", "pour moi"), ("ສືບຕໍ່", "continuer"),
   ("ອີກ|ຢ່າງ|ໜຶ່ງ", "autre chose"), ("ເວົ້າ|ງ່າຍໆ", "pour faire simple")],
  "les mots pour gagner du temps", [("ເອີ|…", "euh…"), ("ຄື|ວ່າ|…", "disons que…"), ("ເວົ້າ|ງ່າຍໆ|…", "pour faire simple…")],
  [], "Les « mots de remplissage » te donnent du temps sans silence : ເອີ, ຄືວ່າ, ຂໍຄິດແປັບໜຶ່ງ, ເວົ້າງ່າຍໆ, ອີກຢ່າງໜຶ່ງ.",
  "les hésitations naturelles des natifs.",
  [("Laisse-moi réfléchir.", "ຂໍ|ຄິດ|ແປັບ|ໜຶ່ງ|."), ("Disons que…", "ຄື|ວ່າ|…"), ("Pour moi…", "ສຳລັບ|ຂ້ອຍ|…")],
  ["Prépare 5 sujets et écris pour chacun 3 idées en lao."], "Joue avec un natif : chacun tire un sujet et parle 5 minutes sans s'arrêter."),
L(90, "Bilan B1", "Faire le point sur les 4 compétences du niveau B1.", "Clara fait un bilan d'un an au Laos.",
  [("N", "ໜຶ່ງ|ປີ|ແລ້ວ|.|ຄິດ|ວ່າ|ພາສາລາວ|ຂອງ|ເຈົ້າ|ເປັນ|ແນວໃດ|?", "Un an déjà. Tu en es où en lao, à ton avis ?"),
   ("C", "ຂ້ອຍ|ເຂົ້າໃຈ|ຫຼາຍ|ຂຶ້ນ|,|ແຕ່|ຍັງ|ເວົ້າ|ຊ້າ|ຢູ່|.", "Je comprends de plus en plus, mais je parle encore lentement."),
   ("N", "ບໍ່|ເປັນ|ຫຍັງ|.|ເຈົ້າ|ເກັ່ງ|ຂຶ້ນ|ແທ້|.", "Pas grave. Tu as vraiment progressé.")],
  [("Comment Clara juge-t-elle son niveau ?", "Elle comprend mieux mais parle encore lentement.")],
  [("ຫຼາຍ|ຂຶ້ນ", "de plus en plus"), ("ເກັ່ງ|ຂຶ້ນ", "progresser"), ("ລະດັບ", "niveau")],
  "révision B1", [("ຄິດ|ວ່າ|…", "opinion"), ("ຖືກ|…", "passif"), ("ໃຫ້|…", "causatif"), ("ຖ້າ|…|ຈະ", "hypothèse")],
  [], "Bilan B1 : opinion, accord et désaccord, récit, passif, causatif, discours rapporté, hypothèses, registres. Fais le test /test dans le projet.",
  "une conversation entière à vitesse normale.",
  [("Je comprends de plus en plus.", "ຂ້ອຍ|ເຂົ້າໃຈ|ຫຼາຍ|ຂຶ້ນ|."), ("J'ai progressé.", "ຂ້ອຍ|ເກັ່ງ|ຂຶ້ນ|.")],
  ["Écris un texte de 20 phrases sur ton parcours en lao, avec opinion et hypothèses."], "Fais le test de fin de niveau B1 et une conversation de 20 minutes avec un natif."),
]
