# Partie C · Vie courante (A1), leçons 21 à 40
LESSONS = [
{
 "n": 21, "title": "Les nombres 0 à 100",
 "obj": "Compter de 0 à 100 et donner un numéro de téléphone.",
 "scene": "Noy demande le numéro de Clara.",
 "dia": [
  ("N", "ເບີໂທ|ຂອງ|ເຈົ້າ|ແມ່ນ|ຫຍັງ|?", "C'est quoi ton numéro ?"),
  ("C", "ສູນ|ຊາວ|,|ຫ້າ|ສີ່|,|ສາມ|ສອງ|.", "Zéro vingt, cinq quatre, trois deux."),
  ("N", "ເວົ້າ|ຊ້າໆ|ແດ່|.", "Plus lentement, s'il te plaît."),
  ("C", "ສູນ|,|ສອງ|,|ສູນ|,|ຫ້າ|,|ສີ່|,|ສາມ|,|ສອງ|.", "Zéro, deux, zéro, cinq, quatre, trois, deux."),
  ("N", "ໄດ້|ແລ້ວ|.|ຂອບໃຈ|.", "C'est bon. Merci."),
 ],
 "ce": [("Que demande Noy ?", "Le numéro de téléphone de Clara."), ("Pourquoi Clara répète-t-elle ?", "Noy lui demande de parler plus lentement.")],
 "voc": [("ສູນ", "zéro"), ("ໜຶ່ງ", "un"), ("ສອງ", "deux"), ("ສາມ", "trois"), ("ສີ່", "quatre"), ("ຫ້າ", "cinq"), ("ຫົກ", "six"), ("ເຈັດ", "sept"),
         ("ແປດ", "huit"), ("ເກົ້າ", "neuf"), ("ສິບ", "dix"), ("ຊາວ", "vingt", "irrégulier"), ("ຮ້ອຍ", "cent"), ("ເບີໂທ", "numéro de téléphone")],
 "gram": {"t": "former les nombres", "ex": [("ສິບເອັດ", "11 (ເອັດ = 1 à la fin)"), ("ຊາວ", "20"), ("ຊາວຫ້າ", "25"), ("ສາມສິບ", "30"), ("ສອງຮ້ອຍ", "200")],
          "q": ["Comment dit-on 11 ? Et 21 ?", "Quel nombre est irrégulier ?"],
          "rule": "Dizaines = chiffre + ສິບ (ສາມສິບ = 30), sauf 20 = ຊາວ. Le 1 final se dit ເອັດ (ສິບເອັດ = 11, ຊາວເອັດ = 21). On a aussi des chiffres lao : ໐ ໑ ໒ ໓ ໔ ໕ ໖ ໗ ໘ ໙."},
 "co": "les nombres qui se ressemblent : ສີ່ (4) et ສິບ (10).",
 "ant": [("C'est quoi ton numéro ?", "ເບີໂທ|ຂອງ|ເຈົ້າ|ແມ່ນ|ຫຍັງ|?"), ("Plus lentement, s'il te plaît.", "ເວົ້າ|ຊ້າໆ|ແດ່|."), ("Vingt-cinq.", "ຊາວຫ້າ"), ("Trente.", "ສາມສິບ")],
 "ee": ["Écris en lettres lao : 7, 12, 20, 35, 99.", "Écris ton numéro de téléphone en chiffres lao."],
 "task": "Donne ton numéro de téléphone en lao à un natif, puis note le sien.",
},
{
 "n": 22, "title": "Combien ça coûte ?",
 "obj": "Demander un prix, comprendre les grands nombres en kips et payer.",
 "scene": "Clara achète un sac au marché.",
 "dia": [
  ("C", "ກະເປົາ|ນີ້|ເທົ່າໃດ|?", "Combien coûte ce sac ?"),
  ("V", "ຫ້າສິບພັນ|ກີບ|.", "Cinquante mille kips."),
  ("C", "ແພງ|ໂພດ|!|ຫຼຸດ|ໄດ້|ບໍ|?", "C'est trop cher ! Vous pouvez baisser ?"),
  ("V", "ສີ່ສິບ|ພັນ|ກໍ|ໄດ້|.", "Quarante mille, d'accord."),
  ("C", "ໂອເຄ|,|ເອົາ|.", "OK, je le prends."),
  ("V", "ຂອບໃຈ|ເດີ|ເອື້ອຍ|.", "Merci !"),
 ],
 "ce": [("Quel est le premier prix ?", "50 000 kips."), ("Quel est le prix final ?", "40 000 kips.")],
 "voc": [("ເທົ່າໃດ", "combien ?"), ("ພັນ", "mille"), ("ສິບພັນ", "dix mille", "on compte en milliers"), ("ແສນ", "cent mille"), ("ລ້ານ", "million"), ("ກີບ", "kip"),
         ("ແພງ", "cher"), ("ຖືກ", "bon marché"), ("ຫຼຸດ", "baisser (le prix)"), ("ກະເປົາ", "sac"), ("ຈ່າຍ", "payer")],
 "cult": "Au marché, négocier est normal pour les objets et les vêtements, beaucoup moins pour la nourriture. Souris, reste léger.",
 "gram": {"t": "les grands nombres", "ex": [("ຫ້າພັນ", "5 000"), ("ສິບພັນ", "10 000"), ("ຫ້າສິບພັນ", "50 000"), ("ແສນ", "100 000")],
          "q": ["Comment dit-on 50 000 ? Le lao a-t-il un mot pour 100 000 ?"],
          "rule": "Le lao compte avec ພັນ (1 000), ໝື່ນ (10 000), ແສນ (100 000) et ລ້ານ (1 000 000). À l'oral, on dit souvent ສິບພັນ plutôt que ໜຶ່ງໝື່ນ."},
 "co": "les mots ພັນ et ແສນ dans les prix.",
 "ant": [("Combien ça coûte ?", "ເທົ່າໃດ|?"), ("C'est trop cher !", "ແພງ|ໂພດ|!"), ("Vous pouvez baisser ?", "ຫຼຸດ|ໄດ້|ບໍ|?"), ("Je le prends.", "ເອົາ|.")],
 "ee": ["Écris 5 prix en kips en lettres lao.", "Écris un mini-dialogue de marchandage."],
 "task": "Joue une négociation complète avec un natif pour un objet de ton choix.",
},
{
 "n": 23, "title": "Les classificateurs",
 "obj": "Compter les choses avec le bon classificateur et commander des quantités.",
 "scene": "Au café, Clara commande pour la famille.",
 "dia": [
  ("C", "ຂໍ|ກາເຟ|ສອງ|ຈອກ|,|ແລະ|ເຝີ|ສາມ|ຖ້ວຍ|.", "Deux cafés et trois bols de pho, s'il vous plaît."),
  ("V", "ມີ|ຈັກ|ຄົນ|?", "Vous êtes combien ?"),
  ("C", "ສີ່|ຄົນ|.", "Quatre."),
  ("V", "ເອົາ|ນ້ຳ|ຈັກ|ແກ້ວ_|?", "Combien de verres d'eau ?"),
  ("C", "ສີ່|ແກ້ວ_|.|ຂອບໃຈ|.", "Quatre verres. Merci."),
 ],
 "ce": [("Combien sont-ils ?", "Quatre personnes."), ("Que commande Clara ?", "2 cafés, 3 pho, 4 verres d'eau.")],
 "voc": [("ຄົນ", "personne (classif.)"), ("ໂຕ", "animal ; vêtement (classif.)"), ("ອັນ", "objet (classif. général)"), ("ຈອກ", "verre, tasse"), ("ຖ້ວຍ", "bol"),
         ("ຈານ", "assiette"), ("ແກ້ວ_", "verre"), ("ໜ່ວຍ", "fruit, objet rond (classif.)"), ("ຫົວ", "livre (classif.) ; tête"), ("ຄັນ", "véhicule (classif.)"), ("ຈັກ", "combien ? (petit nombre)")],
 "gram": {"t": "nom + nombre + classificateur", "ex": [("ກາເຟ|ສອງ|ຈອກ", "deux cafés"), ("ໝາ|ສາມ|ໂຕ", "trois chiens"), ("ລົດ|ໜຶ່ງ|ຄັນ", "une voiture"), ("ຈັກ|ຄົນ|?", "combien de personnes ?")],
          "q": ["Dans quel ordre viennent le nom, le nombre et le classificateur ?"],
          "rule": "Pour compter, on dit : nom + nombre + classificateur (ກາເຟ ສອງ ຈອກ). Le classificateur dépend de la forme ou du type de la chose. Si tu hésites, ອັນ marche pour beaucoup d'objets. [À VÉRIFIER : classificateurs exacts]"},
 "co": "le classificateur après chaque nombre.",
 "ant": [("Deux cafés, s'il vous plaît.", "ຂໍ|ກາເຟ|ສອງ|ຈອກ|."), ("Vous êtes combien ?", "ມີ|ຈັກ|ຄົນ|?"), ("Quatre personnes.", "ສີ່|ຄົນ|."), ("Trois chiens.", "ໝາ|ສາມ|ໂຕ")],
 "ee": ["Écris 6 groupes nom + nombre + classificateur pour des objets chez toi."],
 "task": "Commande pour plusieurs personnes au restaurant (vrai ou jeu de rôle).",
},
{
 "n": 24, "title": "Au restaurant",
 "obj": "Commander un repas complet, demander ce qu'on te conseille et payer.",
 "scene": "Clara déjeune seule dans un petit restaurant.",
 "dia": [
  ("V", "ກິນ|ຫຍັງ|ດີ|ເອື້ອຍ|?", "Qu'est-ce que tu manges ?"),
  ("C", "ມີ|ຫຍັງ|ແຊບ|?", "Qu'est-ce qui est bon ?"),
  ("V", "ປີ້ງໄກ່|ແຊບ|ຫຼາຍ|.", "Le poulet grillé est très bon."),
  ("C", "ເອົາ|ປີ້ງໄກ່|ໜຶ່ງ|ຈານ|ແລະ|ເຂົ້າໜຽວ|.", "Un poulet grillé et du riz gluant."),
  ("V", "ເອົາ|ເຜັດ|ບໍ|?", "Pimenté ?"),
  ("C", "ເຜັດ|ໜ້ອຍ|ໜຶ່ງ|.", "Un peu pimenté."),
  ("C", "ນ້ອງ|,|ໄລ່ເງິນ|ແດ່|.", "L'addition, s'il vous plaît."),
 ],
 "ce": [("Que conseille la serveuse ?", "Le poulet grillé."), ("Comment Clara veut-elle son plat ?", "Un peu pimenté.")],
 "voc": [("ຂໍ", "je voudrais (poli)"), ("ເອົາ", "je prends"), ("ປີ້ງໄກ່", "poulet grillé"), ("ເມນູ", "menu"), ("ແຊບ", "bon, délicieux"), ("ເຜັດ", "pimenté"),
         ("ເຜັດ|ໜ້ອຍ|ໜຶ່ງ", "un peu pimenté"), ("ບໍ່|ໃສ່|ໝາກເຜັດ", "sans piment"), ("ໄລ່ເງິນ", "l'addition"), ("ເຝີ", "soupe pho")],
 "gram": {"t": "la demande polie avec ຂໍ", "ex": [("ຂໍ|ນ້ຳ|ແດ່", "de l'eau, s'il vous plaît"), ("ຂໍ|ເມນູ|ແດ່", "le menu, s'il vous plaît"), ("ຂໍ|ໂທດ", "pardon (litt. je demande la faute)")],
          "q": ["Où se place ແດ່ ? Qu'apporte-t-il ?"],
          "rule": "ຂໍ + chose (+ ແດ່) = « je voudrais…, s'il vous plaît ». ແດ່ en fin de phrase adoucit la demande."},
 "co": "les mots ຂໍ et ແດ່ qui encadrent la demande.",
 "ant": [("Qu'est-ce qui est bon ?", "ມີ|ຫຍັງ|ແຊບ|?"), ("Le menu, s'il vous plaît.", "ຂໍ|ເມນູ|ແດ່|."), ("Sans piment.", "ບໍ່|ໃສ່|ໝາກເຜັດ|."), ("L'addition, s'il vous plaît.", "ໄລ່ເງິນ|ແດ່|.")],
 "ee": ["Écris ta commande idéale au restaurant lao en 4 phrases."],
 "task": "Commande un repas complet dans un restaurant lao ou asiatique, en lao.",
},
{
 "n": 25, "title": "Goûts et préférences",
 "obj": "Dire ce que tu aimes, ce que tu n'aimes pas, et nuancer (beaucoup, pas trop, vraiment).",
 "scene": "Noy et Clara parlent de nourriture.",
 "dia": [
  ("N", "ເຈົ້າ|ມັກ|ອາຫານ|ລາວ|ບໍ|?", "Tu aimes la cuisine lao ?"),
  ("C", "ມັກ|ຫຼາຍ|!|ໂດຍສະເພາະ|ລາບ|.", "Beaucoup ! Surtout le larb."),
  ("N", "ມັກ|ປາແດກ|ບໍ|?", "Tu aimes le padèk ?"),
  ("C", "ບໍ່|ມັກ|ປານໃດ|.|ມັນ|ເຄັມ|ໂພດ|.", "Pas trop. C'est trop salé."),
  ("N", "ຂ້ອຍ|ມັກ|ແທ້|!", "Moi, j'adore !"),
 ],
 "ce": [("Que préfère Clara ?", "Le larb."), ("Qu'en pense-t-elle, du padèk ?", "Elle n'aime pas trop, c'est trop salé.")],
 "voc": [("ມັກ", "aimer"), ("ບໍ່|ມັກ", "ne pas aimer"), ("ມັກ|ຫຼາຍ", "aimer beaucoup"), ("ບໍ່|ມັກ|ປານໃດ", "pas trop aimer"), ("ໂດຍສະເພາະ", "surtout"),
         ("ປາແດກ", "padèk (poisson fermenté)"), ("ເຄັມ", "salé"), ("ຫວານ", "sucré"), ("ສົ້ມ", "acide"), ("ໂພດ", "trop", "[À VÉRIFIER]"), ("ມັນ", "il, ça (chose)")],
 "gram": {"t": "les intensifs", "ex": [("ແຊບ|ຫຼາຍ", "très bon"), ("ແຊບ|ແທ້", "vraiment bon"), ("ເຄັມ|ໂພດ", "trop salé"), ("ບໍ່|ຫວານ|ປານໃດ", "pas très sucré")],
          "q": ["Où se placent les intensifs par rapport à l'adjectif ?"],
          "rule": "Les intensifs se placent après l'adjectif ou le verbe : ຫຼາຍ (très), ແທ້ (vraiment), ໂພດ (trop). ບໍ່…ປານໃດ = pas très."},
 "co": "les petits mots après les adjectifs : ຫຼາຍ, ແທ້, ໂພດ.",
 "ant": [("J'aime beaucoup la cuisine lao.", "ຂ້ອຍ|ມັກ|ອາຫານ|ລາວ|ຫຼາຍ|."), ("Pas trop.", "ບໍ່|ປານໃດ|."), ("C'est trop salé.", "ເຄັມ|ໂພດ|."), ("Vraiment bon !", "ແຊບ|ແທ້|!")],
 "ee": ["Écris 5 phrases sur tes goûts alimentaires avec des intensifs."],
 "task": "Discute 3 minutes avec un natif de ce que vous aimez manger.",
},
{
 "n": 26, "title": "La famille (1)",
 "obj": "Présenter ta famille proche avec les termes d'aîné et de cadet.",
 "scene": "Clara montre une photo de sa famille à Noy.",
 "dia": [
  ("N", "ນີ້|ແມ່ນ|ຄອບຄົວ|ຂອງ|ເຈົ້າ|ບໍ|?", "C'est ta famille ?"),
  ("C", "ແມ່ນ|.|ນີ້|ແມ່ນ|ພໍ່|ແລະ|ແມ່|.", "Oui. Voici mon père et ma mère."),
  ("N", "ເຈົ້າ|ມີ|ອ້າຍເອື້ອຍ|ນ້ອງ|ບໍ|?", "Tu as des frères et sœurs ?"),
  ("C", "ມີ|ອ້າຍ|ໜຶ່ງ|ຄົນ|ແລະ|ນ້ອງສາວ|ໜຶ່ງ|ຄົນ|.", "J'ai un grand frère et une petite sœur."),
  ("N", "ເຈົ້າ|ເປັນ|ລູກ|ທີ|ສອງ|.", "Tu es la deuxième enfant."),
 ],
 "ce": [("Combien de frères et sœurs a Clara ?", "Un grand frère et une petite sœur.")],
 "voc": [("ຄອບຄົວ", "famille"), ("ພໍ່", "père"), ("ແມ່", "mère"), ("ອ້າຍ", "grand frère"), ("ເອື້ອຍ", "grande sœur"), ("ນ້ອງຊາຍ", "petit frère"), ("ນ້ອງສາວ", "petite sœur"),
         ("ລູກ", "enfant (de qqn)"), ("ລູກຊາຍ", "fils"), ("ລູກສາວ", "fille"), ("ພີ່ນ້ອງ", "frères et sœurs ; parenté")],
 "cult": "Le lao n'a pas de mot neutre pour « frère » ou « sœur » : on précise toujours aîné (ອ້າຍ, ເອື້ອຍ) ou cadet (ນ້ອງ). L'âge structure toute la relation.",
 "gram": {"t": "aîné ou cadet", "ex": [("ອ້າຍ", "frère aîné"), ("ເອື້ອຍ", "sœur aînée"), ("ນ້ອງ|ຊາຍ", "cadet + homme"), ("ນ້ອງ|ສາວ", "cadette + femme")],
          "q": ["Comment précise-t-on le sexe d'un cadet ?"],
          "rule": "Pour les aînés, un mot différent par sexe (ອ້າຍ, ເອື້ອຍ). Pour les cadets, ນ້ອງ + ຊາຍ (homme) ou ສາວ (femme)."},
 "co": "la différence entre ອ້າຍ, ເອື້ອຍ et ນ້ອງ.",
 "ant": [("Tu as des frères et sœurs ?", "ເຈົ້າ|ມີ|ອ້າຍເອື້ອຍ|ນ້ອງ|ບໍ|?"), ("J'ai une petite sœur.", "ຂ້ອຍ|ມີ|ນ້ອງສາວ|ໜຶ່ງ|ຄົນ|."), ("Voici mon père.", "ນີ້|ແມ່ນ|ພໍ່|ຂອງ|ຂ້ອຍ|."), ("C'est ta famille ?", "ນີ້|ແມ່ນ|ຄອບຄົວ|ຂອງ|ເຈົ້າ|ບໍ|?")],
 "ee": ["Dessine ton arbre familial proche et écris les termes lao."],
 "task": "Présente ta famille proche à un natif avec une photo.",
},
{
 "n": 27, "title": "La famille (2)",
 "obj": "Parler des grands-parents, oncles et tantes en distinguant côté père et côté mère.",
 "scene": "Mme Boua explique la famille élargie à Clara.",
 "dia": [
  ("B", "ນີ້|ແມ່ນ|ປູ່|ແລະ|ຍ່າ|ຂອງ|ນ້ອຍ|.", "Voici les grands-parents paternels de Noy."),
  ("C", "ແລ້ວ|ພໍ່|ແມ່|ຂອງ|ແມ່|ເດ|?", "Et les parents de sa mère ?"),
  ("B", "ແມ່ນ|ຕາ|ແລະ|ຍາຍ|.", "Ce sont « ta » et « yay »."),
  ("C", "ໂອ້|,|ຍາກ|ເນາະ|!", "Oh, c'est compliqué !"),
  ("B", "ບໍ່|ຍາກ|ດອກ|.|ຈື່|ໄວ້|ເດີ|.", "Mais non. Retiens-le bien."),
 ],
 "ce": [("Comment appelle-t-on les grands-parents côté père ?", "ປູ່ et ຍ່າ."), ("Et côté mère ?", "ຕາ et ຍາຍ.")],
 "voc": [("ປູ່", "grand-père paternel"), ("ຍ່າ", "grand-mère paternelle"), ("ຕາ", "grand-père maternel"), ("ຍາຍ", "grand-mère maternelle"), ("ລຸງ", "oncle (aîné des parents)"),
         ("ປ້າ", "tante (aînée des parents)"), ("ອາ", "oncle, tante (cadet du père)"), ("ນ້າ", "oncle, tante (cadet de la mère)"), ("ຫຼານ", "petit-enfant ; neveu"), ("ຍາກ", "difficile")],
 "gram": {"t": "côté père, côté mère", "ex": [("ປູ່|ຍ່າ", "grands-parents côté père"), ("ຕາ|ຍາຍ", "grands-parents côté mère"), ("ອາ", "cadet(te) du père"), ("ນ້າ", "cadet(te) de la mère")],
          "q": ["Pourquoi a-t-on besoin de 4 mots pour les grands-parents ?"],
          "rule": "Le lao distingue la lignée paternelle et maternelle, et l'âge relatif aux parents : ລຸງ/ປ້າ (plus âgés que le parent), ອາ (cadets du père), ນ້າ (cadets de la mère). [À VÉRIFIER : usages régionaux]"},
 "co": "les 4 mots des grands-parents.",
 "ant": [("Voici mes grands-parents paternels.", "ນີ້|ແມ່ນ|ປູ່|ແລະ|ຍ່າ|ຂອງ|ຂ້ອຍ|."), ("C'est compliqué !", "ຍາກ|ເນາະ|!"), ("C'est mon oncle.", "ນີ້|ແມ່ນ|ລຸງ|ຂອງ|ຂ້ອຍ|.")],
 "ee": ["Complète ton arbre familial avec grands-parents, oncles et tantes."],
 "task": "Explique à un natif qui est qui dans ta famille élargie et vérifie les termes avec lui.",
},
{
 "n": 28, "title": "L'âge et la hiérarchie",
 "obj": "Demander l'âge poliment et t'adresser à quelqu'un avec le bon terme selon son âge.",
 "scene": "Clara rencontre une voisine âgée.",
 "dia": [
  ("C", "ສະບາຍດີ|ແມ່ຕູ້|.", "Bonjour grand-mère."),
  ("X", "ສະບາຍດີ|ລູກ|.|ລູກ|ອາຍຸ|ຈັກ|ປີ|ແລ້ວ|?", "Bonjour mon enfant. Tu as quel âge ?"),
  ("C", "ຊາວ|ແປດ|ປີ|ເຈົ້າ|.", "Vingt-huit ans."),
  ("X", "ຍັງ|ໜຸ່ມ|ຢູ່|.|ແຕ່ງງານ|ແລ້ວ|ບໍ|?", "Tu es encore jeune. Tu es mariée ?"),
  ("C", "ຍັງ|ເທື່ອ|ເຈົ້າ|.", "Pas encore."),
 ],
 "ce": [("Comment Clara appelle-t-elle la voisine ?", "ແມ່ຕູ້ — grand-mère (terme respectueux)."), ("Quelle question personnelle pose la voisine ?", "Si Clara est mariée.")],
 "voc": [("ອາຍຸ", "âge"), ("ຈັກ|ປີ", "combien d'années ?"), ("ປີ", "an, année"), ("ແມ່ຕູ້", "grand-mère (adresse respectueuse)", "[À VÉRIFIER]"), ("ພໍ່ຕູ້", "grand-père (adresse)", "[À VÉRIFIER]"),
         ("ໜຸ່ມ", "jeune"), ("ເຖົ້າ", "vieux, âgé"), ("ແຕ່ງງານ", "se marier"), ("ລູກ", "mon enfant (adresse d'un aîné)")],
 "cult": "Les questions sur l'âge, le mariage ou le salaire sont normales au Laos : elles servent à situer la relation. Tu peux répondre vaguement.",
 "gram": {"t": "les termes d'adresse", "ex": [("ແມ່ຕູ້", "femme âgée"), ("ລຸງ", "homme plus âgé que tes parents"), ("ອ້າຍ", "homme un peu plus âgé"), ("ນ້ອງ", "plus jeune")],
          "q": ["Comment choisir le bon terme pour un inconnu ?"],
          "rule": "On s'adresse aux inconnus avec un terme de parenté adapté à leur âge apparent : ນ້ອງ (plus jeune), ອ້າຍ/ເອື້ອຍ (un peu plus âgé), ລຸງ/ປ້າ (âge des parents), ພໍ່ຕູ້/ແມ່ຕູ້ (âge des grands-parents)."},
 "co": "la question ອາຍຸຈັກປີ.",
 "ant": [("Tu as quel âge ?", "ອາຍຸ|ຈັກ|ປີ|?"), ("J'ai vingt-huit ans.", "ຂ້ອຍ|ອາຍຸ|ຊາວ|ແປດ|ປີ|."), ("Pas encore.", "ຍັງ|ເທື່ອ|."), ("Bonjour grand-mère.", "ສະບາຍດີ|ແມ່ຕູ້|.")],
 "ee": ["Pour 5 personnes de ton entourage, écris le terme d'adresse lao que tu utiliserais."],
 "task": "Demande son âge à un natif et utilise le bon terme d'adresse pendant toute la conversation.",
},
{
 "n": 29, "title": "L'heure",
 "obj": "Dire et demander l'heure et fixer un rendez-vous.",
 "scene": "Noy et Clara fixent un rendez-vous.",
 "dia": [
  ("C", "ຕອນນີ້|ຈັກ|ໂມງ|ແລ້ວ|?", "Il est quelle heure ?"),
  ("N", "ສາມ|ໂມງ|ແລງ|.", "Trois heures de l'après-midi."),
  ("C", "ມື້ອື່ນ|ພົບ|ກັນ|ຈັກ|ໂມງ|?", "Demain, on se retrouve à quelle heure ?"),
  ("N", "ເກົ້າ|ໂມງ|ເຊົ້າ|ໄດ້|ບໍ|?", "Neuf heures du matin, ça va ?"),
  ("C", "ໄດ້|.|ຢ່າ|ມາ|ຊ້າ|ເດີ|!", "Oui. Ne sois pas en retard !"),
 ],
 "ce": [("Quelle heure est-il ?", "Trois heures de l'après-midi."), ("À quelle heure est le rendez-vous ?", "Neuf heures du matin, demain.")],
 "voc": [("ໂມງ", "heure"), ("ຈັກ|ໂມງ", "quelle heure ?"), ("ໂມງເຊົ້າ", "heure du matin"), ("ຕອນເຊົ້າ", "le matin"), ("ຕອນບ່າຍ", "l'après-midi"), ("ຕອນແລງ", "le soir"),
         ("ທຸ່ມ", "heure du soir (19 h-23 h)", "[À VÉRIFIER]"), ("ເຄິ່ງ", "demi"), ("ນາທີ", "minute"), ("ຊ້າ", "en retard ; lent"), ("ມື້ອື່ນ", "demain")],
 "gram": {"t": "le découpage lao de la journée", "ex": [("ເກົ້າ|ໂມງ|ເຊົ້າ", "9 h du matin"), ("ສາມ|ໂມງ|ແລງ", "15 h"), ("ສອງ|ທຸ່ມ", "20 h"), ("ສິບ|ໂມງ|ເຄິ່ງ", "10 h 30")],
          "q": ["Comment précise-t-on matin ou après-midi ?"],
          "rule": "À l'oral, on dit souvent le nombre + ໂມງ + le moment de la journée (ເຊົ້າ, ແລງ…). Le soir, on compte parfois en ທຸ່ມ. On peut aussi utiliser le système sur 24 heures. [À VÉRIFIER : usage exact de ທຸ່ມ à Vientiane]"},
 "co": "le moment de la journée après l'heure.",
 "ant": [("Il est quelle heure ?", "ຕອນນີ້|ຈັກ|ໂມງ|ແລ້ວ|?"), ("Neuf heures du matin.", "ເກົ້າ|ໂມງ|ເຊົ້າ|."), ("On se retrouve à quelle heure ?", "ພົບ|ກັນ|ຈັກ|ໂມງ|?"), ("Ne sois pas en retard !", "ຢ່າ|ມາ|ຊ້າ|ເດີ|!")],
 "ee": ["Écris ton emploi du temps d'une journée avec les heures en lao."],
 "task": "Fixe un vrai rendez-vous en lao avec un natif (jour et heure).",
},
{
 "n": 30, "title": "Jours, mois, dates",
 "obj": "Dire les jours, les mois et ta date de naissance.",
 "scene": "Kèo prépare son anniversaire.",
 "dia": [
  ("K", "ວັນເກີດ|ຂອງ|ຂ້ອຍ|ແມ່ນ|ວັນເສົາ|ໜ້າ|.", "Mon anniversaire, c'est samedi prochain."),
  ("C", "ວັນທີ|ເທົ່າໃດ|?", "Le combien ?"),
  ("K", "ວັນທີ|ສິບ|ຫ້າ|.", "Le quinze."),
  ("C", "ເຈົ້າ|ຈະ|ອາຍຸ|ຈັກ|ປີ|?", "Tu vas avoir quel âge ?"),
  ("K", "ສິບ|ແປດ|ປີ|!", "Dix-huit ans !"),
  ("C", "ສຸກສັນ|ວັນເກີດ|ລ່ວງໜ້າ|!", "Joyeux anniversaire en avance !"),
 ],
 "ce": [("Quand est l'anniversaire de Kèo ?", "Samedi prochain, le 15."), ("Quel âge va-t-il avoir ?", "18 ans.")],
 "voc": [("ວັນເກີດ", "anniversaire"), ("ວັນຈັນ", "lundi"), ("ວັນອັງຄານ", "mardi"), ("ວັນພຸດ", "mercredi"), ("ວັນພະຫັດ", "jeudi"), ("ວັນສຸກ", "vendredi"),
         ("ວັນເສົາ", "samedi"), ("ວັນອາທິດ", "dimanche"), ("ວັນທີ", "date (le…)"), ("ເດືອນ", "mois"), ("ສຸກສັນ|ວັນເກີດ", "joyeux anniversaire")],
 "gram": {"t": "les ordinaux et les dates", "ex": [("ວັນທີ|ສິບ|ຫ້າ", "le 15"), ("ທີໜຶ່ງ", "premier"), ("ລູກ|ທີ|ສອງ", "le deuxième enfant")],
          "q": ["Quel mot forme les ordinaux ?"],
          "rule": "ທີ + nombre = ordinal (ທີໜຶ່ງ = premier). Pour la date : ວັນທີ + nombre + ເດືອນ + mois. Les mois officiels finissent en -ກົມ (31 jours) ou -ຍົນ (30 jours). [À VÉRIFIER]"},
 "co": "les jours de la semaine.",
 "ant": [("C'est quand ton anniversaire ?", "ວັນເກີດ|ຂອງ|ເຈົ້າ|ແມ່ນ|ມື້ໃດ|?"), ("Le quinze.", "ວັນທີ|ສິບ|ຫ້າ|."), ("Joyeux anniversaire !", "ສຸກສັນ|ວັນເກີດ|!"), ("Samedi prochain.", "ວັນເສົາ|ໜ້າ|.")],
 "ee": ["Écris les 7 jours de la semaine.", "Écris ta date de naissance complète en lao."],
 "task": "Demande la date d'anniversaire de 3 personnes en lao et note-les.",
},
{
 "n": 31, "title": "Où est… ?",
 "obj": "Demander et indiquer un chemin simple.",
 "scene": "Clara se perd en ville.",
 "dia": [
  ("C", "ຂໍໂທດ|,|ທະນາຄານ|ຢູ່|ໃສ|?", "Pardon, où est la banque ?"),
  ("X", "ກົງໄປ|,|ແລ້ວ|ລ້ຽວ|ຊ້າຍ|.", "Tout droit, puis à gauche."),
  ("C", "ໄກ|ບໍ|?", "C'est loin ?"),
  ("X", "ບໍ່|ໄກ|.|ຍ່າງ|ຫ້າ|ນາທີ|.", "Non. Cinq minutes à pied."),
  ("C", "ຢູ່|ຂ້າງ|ຕະຫຼາດ|ບໍ|?", "C'est à côté du marché ?"),
  ("X", "ແມ່ນ|ແລ້ວ|.|ຢູ່|ຕໍ່ໜ້າ|ຕະຫຼາດ|.", "Oui. En face du marché."),
 ],
 "ce": [("Où va Clara ?", "À la banque."), ("C'est loin ?", "Non, 5 minutes à pied, en face du marché.")],
 "voc": [("ກົງໄປ", "tout droit"), ("ລ້ຽວ", "tourner"), ("ຊ້າຍ", "gauche"), ("ຂວາ", "droite"), ("ຂ້າງ", "à côté de"), ("ຕໍ່ໜ້າ", "en face de"),
         ("ທາງຫຼັງ", "derrière"), ("ຍ່າງ", "marcher"), ("ທະນາຄານ", "banque"), ("ນາທີ", "minute")],
 "gram": {"t": "les prépositions de lieu", "ex": [("ຢູ່|ຂ້າງ|ຕະຫຼາດ", "à côté du marché"), ("ຢູ່|ຕໍ່ໜ້າ|ວັດ", "en face du temple"), ("ຢູ່|ໃນ|ເຮືອນ", "dans la maison")],
          "q": ["Quel verbe précède la préposition ?"],
          "rule": "Pour situer : ຢູ່ + préposition + lieu. ຂ້າງ (à côté), ຕໍ່ໜ້າ (en face), ໃນ (dans), ເທິງ (sur), ກ້ອງ (sous)."},
 "co": "les directions : ຊ້າຍ, ຂວາ, ກົງໄປ.",
 "ant": [("Pardon, où est la banque ?", "ຂໍໂທດ|,|ທະນາຄານ|ຢູ່|ໃສ|?"), ("Tout droit, puis à gauche.", "ກົງໄປ|,|ແລ້ວ|ລ້ຽວ|ຊ້າຍ|."), ("C'est loin ?", "ໄກ|ບໍ|?"), ("En face du marché.", "ຢູ່|ຕໍ່ໜ້າ|ຕະຫຼາດ|.")],
 "ee": ["Écris le chemin de chez toi à un lieu proche en 4 phrases."],
 "task": "Explique en lao à un natif le chemin de chez toi à un commerce proche.",
},
{
 "n": 32, "title": "Les transports",
 "obj": "Prendre un tuk-tuk, donner ta destination et négocier le prix.",
 "scene": "Clara prend un tuk-tuk pour l'aéroport.",
 "dia": [
  ("C", "ໄປ|ສະໜາມບິນ|ເທົ່າໃດ|?", "Combien pour l'aéroport ?"),
  ("T", "ຫ້າສິບພັນ|.", "Cinquante mille."),
  ("C", "ສາມສິບ|ພັນ|ໄດ້|ບໍ|?", "Trente mille, c'est possible ?"),
  ("T", "ສີ່ສິບ|ພັນ|.|ຂຶ້ນ|ມາ|.", "Quarante mille. Montez."),
  ("C", "ໂອເຄ|.|ໄປ|ໄວ|ໆ|ແດ່|,|ຂ້ອຍ|ຟ້າວ|.", "OK. Allez vite, s'il vous plaît, je suis pressée."),
 ],
 "ce": [("Où va Clara ?", "À l'aéroport."), ("Quel est le prix final ?", "40 000 kips.")],
 "voc": [("ລົດຕຸກຕຸກ", "tuk-tuk"), ("ລົດເມ", "bus"), ("ລົດຈັກ", "moto"), ("ຍົນ", "avion"), ("ສະໜາມບິນ", "aéroport"), ("ຂຶ້ນ", "monter"), ("ລົງ", "descendre"),
         ("ຈອດ", "s'arrêter, se garer"), ("ຟ້າວ", "être pressé"), ("ຂີ່", "monter (à moto, à vélo)")],
 "gram": {"t": "les verbes en série", "ex": [("ຂຶ້ນ|ມາ", "monte (vers moi)"), ("ໄປ|ຊື້", "aller acheter"), ("ຍ່າງ|ໄປ", "aller à pied")],
          "q": ["Que montrent ມາ et ໄປ après un verbe ?"],
          "rule": "Le lao enchaîne les verbes sans mot de liaison. ມາ après un verbe = vers celui qui parle, ໄປ = en s'éloignant."},
 "co": "ມາ et ໄປ après les verbes.",
 "ant": [("Combien pour l'aéroport ?", "ໄປ|ສະໜາມບິນ|ເທົ່າໃດ|?"), ("Arrêtez-vous ici, s'il vous plaît.", "ຈອດ|ຢູ່ນີ້|ແດ່|."), ("Je suis pressée.", "ຂ້ອຍ|ຟ້າວ|."), ("Je vais à pied.", "ຂ້ອຍ|ຍ່າງ|ໄປ|.")],
 "ee": ["Écris un dialogue de 5 répliques avec un chauffeur de tuk-tuk."],
 "task": "Joue avec un natif une course en tuk-tuk : destination, prix, arrêt.",
},
{
 "n": 33, "title": "Ma journée",
 "obj": "Décrire ta routine quotidienne dans l'ordre.",
 "scene": "Noy raconte sa journée type.",
 "dia": [
  ("N", "ຕອນເຊົ້າ|ຂ້ອຍ|ຕື່ນ|ຫົກ|ໂມງ|.", "Le matin, je me lève à 6 h."),
  ("N", "ອາບນ້ຳ|,|ກິນເຂົ້າ|,|ແລ້ວ|ໄປ|ເຮັດວຽກ|.", "Je me douche, je mange, puis je vais travailler."),
  ("C", "ເລີກ|ວຽກ|ຈັກ|ໂມງ|?", "Tu finis le travail à quelle heure ?"),
  ("N", "ຫ້າ|ໂມງ|ແລງ|.|ແລ້ວ|ກັບ|ເຮືອນ|.", "À 17 h. Puis je rentre."),
  ("C", "ຕອນແລງ|ເຮັດ|ຫຍັງ|?", "Et le soir, tu fais quoi ?"),
  ("N", "ເບິ່ງ|ໜັງ|ແລ້ວ|ນອນ|.", "Je regarde un film puis je dors."),
 ],
 "ce": [("À quelle heure se lève Noy ?", "À 6 h."), ("Que fait-elle le soir ?", "Elle regarde un film puis dort.")],
 "voc": [("ຕື່ນ", "se réveiller"), ("ອາບນ້ຳ", "se doucher"), ("ເຮັດວຽກ", "travailler"), ("ເລີກ|ວຽກ", "finir le travail"), ("ກັບ|ເຮືອນ", "rentrer à la maison"),
         ("ເບິ່ງ", "regarder"), ("ໜັງ", "film"), ("ນອນ", "dormir"), ("ແຕ່ງໂຕ", "s'habiller"), ("ທຸກມື້", "tous les jours")],
 "gram": {"t": "enchaîner les actions avec ແລ້ວ", "ex": [("ອາບນ້ຳ|ແລ້ວ|ກິນເຂົ້າ", "je me douche puis je mange"), ("ເບິ່ງ|ໜັງ|ແລ້ວ|ນອນ", "je regarde un film puis je dors")],
          "q": ["Quel mot sert de « puis » ?"],
          "rule": "ແລ້ວ entre deux verbes = « puis, ensuite ». Pour une routine, on peut aussi juste aligner les verbes."},
 "co": "ແລ້ວ qui relie les actions.",
 "ant": [("Je me lève à 6 h.", "ຂ້ອຍ|ຕື່ນ|ຫົກ|ໂມງ|."), ("Puis je vais travailler.", "ແລ້ວ|ໄປ|ເຮັດວຽກ|."), ("Tu fais quoi le soir ?", "ຕອນແລງ|ເຮັດ|ຫຍັງ|?"), ("Je dors à 23 h.", "ຂ້ອຍ|ນອນ|ຫ້າ|ທຸ່ມ|.")],
 "ee": ["Écris ta journée type en 8 phrases."],
 "task": "Raconte ta journée type à un natif en 2 minutes.",
},
{
 "n": 34, "title": "À qui est-ce ?",
 "obj": "Exprimer la possession et parler de tes affaires.",
 "scene": "Kèo cherche son téléphone.",
 "dia": [
  ("K", "ໂທລະສັບ|ນີ້|ແມ່ນ|ຂອງ|ໃຜ|?", "À qui est ce téléphone ?"),
  ("C", "ບໍ່|ແມ່ນ|ຂອງ|ຂ້ອຍ|.", "Ce n'est pas le mien."),
  ("N", "ແມ່ນ|ຂອງ|ພໍ່|.", "C'est celui de papa."),
  ("K", "ແລ້ວ|ຂອງ|ຂ້ອຍ|ຢູ່|ໃສ|?", "Et le mien, il est où ?"),
  ("N", "ຢູ່|ເທິງ|ໂຕະ|ພຸ້ນ|.", "Sur la table, là-bas."),
 ],
 "ce": [("À qui est le téléphone ?", "Au père."), ("Où est celui de Kèo ?", "Sur la table, là-bas.")],
 "voc": [("ຂອງ", "de (possession) ; chose"), ("ຂອງ|ໃຜ", "à qui ?"), ("ຂອງ|ຂ້ອຍ", "à moi, le mien"), ("ໂທລະສັບ", "téléphone"), ("ກະເປົາ", "sac"), ("ກະແຈ", "clé"),
         ("ປຶ້ມ", "livre, cahier"), ("ເທິງ", "sur"), ("ພຸ້ນ", "là-bas (loin)"), ("ເຄື່ອງ", "affaires, objets")],
 "gram": {"t": "la possession avec ຂອງ", "ex": [("ກະເປົາ|ຂອງ|ຂ້ອຍ", "mon sac"), ("ຂອງ|ໃຜ|?", "à qui ?"), ("ແມ່ນ|ຂອງ|ພໍ່", "c'est à papa")],
          "q": ["Où se place le possesseur ?"],
          "rule": "Objet + ຂອງ + possesseur = l'objet de quelqu'un. ຂອງ peut être omis dans les relations proches : ແມ່ຂ້ອຍ = ma mère."},
 "co": "ຂອງ dans chaque phrase.",
 "ant": [("À qui est ce sac ?", "ກະເປົາ|ນີ້|ແມ່ນ|ຂອງ|ໃຜ|?"), ("C'est à moi.", "ແມ່ນ|ຂອງ|ຂ້ອຍ|."), ("Ce n'est pas le mien.", "ບໍ່|ແມ່ນ|ຂອງ|ຂ້ອຍ|."), ("Où sont mes clés ?", "ກະແຈ|ຂອງ|ຂ້ອຍ|ຢູ່|ໃສ|?")],
 "ee": ["Écris 5 phrases sur des objets qui appartiennent à des membres de ta famille."],
 "task": "Joue avec un natif à « à qui est-ce ? » avec 5 objets.",
},
{
 "n": 35, "title": "Décrire",
 "obj": "Décrire une personne et un lieu avec des adjectifs.",
 "scene": "Clara décrit son nouveau quartier.",
 "dia": [
  ("N", "ເຮືອນ|ໃໝ່|ຂອງ|ເຈົ້າ|ເປັນ|ແນວໃດ|?", "Ta nouvelle maison, elle est comment ?"),
  ("C", "ນ້ອຍ|_|ແຕ່|ງາມ|.|ມີ|ສວນ|ໃຫຍ່|.", "Petite mais jolie. Il y a un grand jardin."),
  ("N", "ເພື່ອນບ້ານ|ເປັນ|ແນວໃດ|?", "Et les voisins ?"),
  ("C", "ໃຈດີ|ຫຼາຍ|.|ແມ່ຕູ້|ຂ້າງ|ເຮືອນ|ເວົ້າ|ມ່ວນ|.", "Très gentils. La grand-mère d'à côté est drôle."),
 ],
 "ce": [("Comment est la maison de Clara ?", "Petite mais jolie, avec un grand jardin."), ("Comment sont les voisins ?", "Très gentils.")],
 "voc": [("ໃຫຍ່", "grand"), ("ນ້ອຍ_", "petit"), ("ງາມ", "beau, joli"), ("ໃໝ່", "neuf, nouveau"), ("ເກົ່າ", "vieux (objet)"), ("ໃຈດີ", "gentil"),
         ("ສວນ", "jardin"), ("ເພື່ອນບ້ານ", "voisin"), ("ເປັນ|ແນວໃດ", "comment est… ?"), ("ມ່ວນ", "amusant, sympa")],
 "gram": {"t": "l'adjectif après le nom", "ex": [("ເຮືອນ|ໃໝ່", "nouvelle maison"), ("ສວນ|ໃຫຍ່", "grand jardin"), ("ນ້ອຍ_|ໆ", "tout petit (redoublement)")],
          "q": ["Où se place l'adjectif ? Que fait le redoublement ?"],
          "rule": "L'adjectif suit le nom (ເຮືອນໃໝ່). Il sert aussi de verbe : ເຮືອນງາມ = la maison est belle, sans verbe « être ». Redoubler l'adjectif atténue ou intensifie selon le ton de voix."},
 "co": "les adjectifs après les noms.",
 "ant": [("Elle est comment, ta maison ?", "ເຮືອນ|ຂອງ|ເຈົ້າ|ເປັນ|ແນວໃດ|?"), ("Petite mais jolie.", "ນ້ອຍ_|ແຕ່|ງາມ|."), ("Les voisins sont gentils.", "ເພື່ອນບ້ານ|ໃຈດີ|."), ("Il y a un grand jardin.", "ມີ|ສວນ|ໃຫຍ່|.")],
 "ee": ["Décris ta maison et une personne de ta famille en 6 phrases."],
 "task": "Décris ton logement et un proche à un natif.",
},
{
 "n": 36, "title": "La météo",
 "obj": "Parler du temps qu'il fait et des saisons.",
 "scene": "Il commence à pleuvoir.",
 "dia": [
  ("C", "ຝົນ|ຈະ|ຕົກ|ບໍ|?", "Il va pleuvoir ?"),
  ("N", "ຄົງຈະ|ຕົກ|.|ຕອນນີ້|ແມ່ນ|ລະດູຝົນ|.", "Sûrement. C'est la saison des pluies."),
  ("C", "ມື້ວານ|ຮ້ອນ|ຫຼາຍ|.", "Hier, il faisait très chaud."),
  ("N", "ແມ່ນ|.|ເດືອນ|ທັນວາ|ຈະ|ໜາວ|ໜ້ອຍ|ໜຶ່ງ|.", "Oui. En décembre, il fera un peu froid."),
 ],
 "ce": [("Quelle saison est-ce ?", "La saison des pluies."), ("Quel temps faisait-il hier ?", "Très chaud.")],
 "voc": [("ອາກາດ", "temps, climat"), ("ຝົນຕົກ", "il pleut"), ("ຮ້ອນ", "chaud"), ("ໜາວ", "froid"), ("ແດດ", "soleil (rayons)"), ("ລົມ_", "vent"),
         ("ລະດູຝົນ", "saison des pluies"), ("ລະດູແລ້ງ", "saison sèche"), ("ຄົງຈະ", "sûrement"), ("ທັນວາ", "décembre")],
 "gram": {"t": "les phrases sans sujet", "ex": [("ຮ້ອນ|ຫຼາຍ", "il fait très chaud"), ("ຝົນ|ຕົກ", "il pleut"), ("ໜາວ|ໜ້ອຍ|ໜຶ່ງ", "il fait un peu froid")],
          "q": ["Y a-t-il un « il » comme en français ?"],
          "rule": "Le lao n'a pas de sujet impersonnel : ຮ້ອນ suffit pour « il fait chaud ». Le futur proche s'indique avec ຈະ (ຝົນຈະຕົກ)."},
 "co": "ຈະ devant les verbes au futur.",
 "ant": [("Il fait très chaud.", "ຮ້ອນ|ຫຼາຍ|."), ("Il va pleuvoir ?", "ຝົນ|ຈະ|ຕົກ|ບໍ|?"), ("C'est la saison des pluies.", "ແມ່ນ|ລະດູຝົນ|."), ("Il fait un peu froid.", "ໜາວ|ໜ້ອຍ|ໜຶ່ງ|.")],
 "ee": ["Écris la météo de ta ville aujourd'hui et demain."],
 "task": "Parle de la météo de ta ville avec un natif et compare avec le Laos.",
},
{
 "n": 37, "title": "Vêtements et couleurs",
 "obj": "Acheter un vêtement, demander une taille et une couleur, comparer.",
 "scene": "Clara achète un sinh (jupe traditionnelle).",
 "dia": [
  ("C", "ສິ້ນ|ນີ້|ມີ|ສີ|ອື່ນ|ບໍ|?", "Ce sinh existe en d'autres couleurs ?"),
  ("V", "ມີ|ສີ|ແດງ|ແລະ|ສີຟ້າ|.", "En rouge et en bleu."),
  ("C", "ລອງ|ໄດ້|ບໍ|?", "Je peux essayer ?"),
  ("V", "ໄດ້|.|ອັນ|ນີ້|ງາມ|ກວ່າ|.", "Oui. Celui-ci est plus joli."),
  ("C", "ແຕ່|ແພງ|ກວ່າ|.", "Mais plus cher."),
 ],
 "ce": [("Que veut Clara ?", "Un sinh d'une autre couleur."), ("Que dit la vendeuse ?", "Celui-ci est plus joli.")],
 "voc": [("ເສື້ອ", "chemise, haut"), ("ໂສ້ງ", "pantalon"), ("ສິ້ນ", "sinh (jupe lao)"), ("ເກີບ", "chaussures"), ("ລອງ", "essayer"), ("ຂະໜາດ", "taille"),
         ("ສີ|ອື່ນ", "autre couleur"), ("ກວ່າ", "plus… que"), ("ໃຫຍ່|ໂພດ", "trop grand"), ("ພໍດີ", "à la bonne taille")],
 "cult": "Le sinh est la jupe traditionnelle portée au travail, à l'école et à la pagode. Le porter est très apprécié.",
 "gram": {"t": "la comparaison avec ກວ່າ", "ex": [("ງາມ|ກວ່າ", "plus joli"), ("ແພງ|ກວ່າ", "plus cher"), ("ອັນ|ນີ້|ໃຫຍ່|ກວ່າ|ອັນ|ນັ້ນ", "celui-ci est plus grand que celui-là")],
          "q": ["Où se place ກວ່າ ?"],
          "rule": "Adjectif + ກວ່າ (+ élément comparé) = « plus… que »."},
 "co": "ກວ່າ dans les comparaisons.",
 "ant": [("Je peux essayer ?", "ລອງ|ໄດ້|ບໍ|?"), ("Vous l'avez dans une autre couleur ?", "ມີ|ສີ|ອື່ນ|ບໍ|?"), ("C'est trop grand.", "ໃຫຍ່|ໂພດ|."), ("Celui-ci est plus joli.", "ອັນ|ນີ້|ງາມ|ກວ່າ|.")],
 "ee": ["Décris ta tenue du jour en lao."],
 "task": "Joue un achat de vêtement avec un natif : couleur, taille, essayage, prix.",
},
{
 "n": 38, "title": "Le corps et la santé",
 "obj": "Dire où tu as mal et comment tu te sens.",
 "scene": "Clara ne se sent pas bien.",
 "dia": [
  ("N", "ເປັນ|ຫຍັງ|?|ໜ້າ|ບໍ່|ດີ|.", "Qu'est-ce qui ne va pas ? Tu n'as pas bonne mine."),
  ("C", "ຂ້ອຍ|ເຈັບຫົວ|ແລະ|ເຈັບທ້ອງ|.", "J'ai mal à la tête et au ventre."),
  ("N", "ເປັນໄຂ້|ບໍ|?", "Tu as de la fièvre ?"),
  ("C", "ໜ້ອຍ|ໜຶ່ງ|.", "Un peu."),
  ("N", "ກິນຢາ|ແລ້ວ|ພັກຜ່ອນ|ເດີ|.", "Prends un médicament et repose-toi."),
 ],
 "ce": [("Où Clara a-t-elle mal ?", "À la tête et au ventre."), ("Que conseille Noy ?", "Prendre un médicament et se reposer.")],
 "voc": [("ເຈັບ", "avoir mal"), ("ເຈັບຫົວ", "mal à la tête"), ("ເຈັບທ້ອງ", "mal au ventre"), ("ເປັນໄຂ້", "avoir de la fièvre"), ("ເປັນຫວັດ", "être enrhumé"),
         ("ຢາ", "médicament"), ("ກິນຢາ", "prendre un médicament"), ("ພັກຜ່ອນ", "se reposer"), ("ແຂນ", "bras"), ("ຂາ", "jambe")],
 "gram": {"t": "ເຈັບ + partie du corps", "ex": [("ເຈັບ|ຫົວ", "mal à la tête"), ("ເຈັບ|ແຂ້ວ", "mal aux dents"), ("ເຈັບ|ຫຼັງ", "mal au dos")],
          "q": ["Comment construis-tu « j'ai mal à… » ?"],
          "rule": "ເຈັບ + partie du corps = avoir mal à. ເປັນ + maladie = avoir une maladie (ເປັນໄຂ້)."},
 "co": "ເຈັບ suivi de la partie du corps.",
 "ant": [("J'ai mal à la tête.", "ຂ້ອຍ|ເຈັບຫົວ|."), ("Tu as de la fièvre ?", "ເປັນໄຂ້|ບໍ|?"), ("Repose-toi.", "ພັກຜ່ອນ|ເດີ|."), ("Qu'est-ce qui ne va pas ?", "ເປັນ|ຫຍັງ|?")],
 "ee": ["Écris 5 phrases « j'ai mal à… » avec différentes parties du corps."],
 "task": "Joue chez le pharmacien avec un natif : explique tes symptômes.",
},
{
 "n": 39, "title": "Au téléphone (1)",
 "obj": "Passer un appel simple, demander quelqu'un et laisser un message.",
 "scene": "Clara appelle chez Noy.",
 "dia": [
  ("B", "ຮັນໂລ|.", "Allô."),
  ("C", "ສະບາຍດີ|ແມ່|.|ນ້ອຍ|ຢູ່|ບໍ|?", "Bonjour madame. Noy est là ?"),
  ("B", "ບໍ່|ຢູ່|.|ອອກ|ໄປ|ແລ້ວ|.", "Non, elle est sortie."),
  ("C", "ບອກ|ລາວ|ໂທ|ຫາ|ຂ້ອຍ|ແດ່|.", "Dites-lui de me rappeler, s'il vous plaît."),
  ("B", "ໄດ້|.|ແມ່ນ|ໃຜ|ນໍ|?", "D'accord. C'est de la part de qui ?"),
  ("C", "ຄລາຣາ|ເຈົ້າ|.", "Clara."),
 ],
 "ce": [("Noy est-elle là ?", "Non, elle est sortie."), ("Quel message laisse Clara ?", "Que Noy la rappelle.")],
 "voc": [("ຮັນໂລ", "allô"), ("ໂທ", "téléphoner"), ("ໂທຫາ", "appeler quelqu'un"), ("ຢູ່|ບໍ", "est-ce que… est là ?"), ("ບໍ່|ຢູ່", "n'est pas là"),
         ("ອອກ|ໄປ", "sortir"), ("ບອກ", "dire à, prévenir"), ("ໂທ|ກັບ", "rappeler"), ("ແມ່ນ|ໃຜ", "c'est qui ?")],
 "gram": {"t": "faire faire avec ບອກ", "ex": [("ບອກ|ລາວ|ໂທ|ຫາ|ຂ້ອຍ", "dis-lui de m'appeler"), ("ບອກ|ແມ່|ແດ່", "préviens maman, s'il te plaît")],
          "q": ["Comment transmets-tu une demande à quelqu'un d'absent ?"],
          "rule": "ບອກ + personne + action = dire à quelqu'un de faire quelque chose."},
 "co": "les formules d'ouverture et de clôture d'un appel.",
 "ant": [("Allô.", "ຮັນໂລ|."), ("Noy est là ?", "ນ້ອຍ|ຢູ່|ບໍ|?"), ("Dites-lui de me rappeler.", "ບອກ|ລາວ|ໂທ|ຫາ|ຂ້ອຍ|ແດ່|."), ("C'est Clara.", "ແມ່ນ|ຄລາຣາ|.")],
 "ee": ["Écris le script d'un appel de 6 répliques."],
 "task": "Passe un vrai appel court en lao à un natif.",
},
{
 "n": 40, "title": "Bilan A1",
 "obj": "Faire le point sur les 4 compétences du niveau A1.",
 "scene": "Clara raconte sa vie à Vientiane à M. Somsak.",
 "dia": [
  ("S", "ຢູ່|ວຽງຈັນ|ເປັນ|ແນວໃດ|?", "Alors, la vie à Vientiane ?"),
  ("C", "ດີ|ຫຼາຍ|.|ຂ້ອຍ|ມັກ|ອາຫານ|ແລະ|ຄົນ|ລາວ|.", "Très bien. J'aime la cuisine et les gens."),
  ("S", "ເວົ້າລາວ|ເກັ່ງ|ຂຶ້ນ|ແລ້ວ|.", "Tu parles de mieux en mieux."),
  ("C", "ຂອບໃຈ|.|ຂ້ອຍ|ຮຽນ|ທຸກມື້|.", "Merci. J'étudie tous les jours."),
 ],
 "ce": [("Que pense Clara de Vientiane ?", "Elle aime la cuisine et les gens."), ("Pourquoi progresse-t-elle ?", "Elle étudie tous les jours.")],
 "voc": [("ຮຽນ", "étudier, apprendre"), ("ທຸກມື້", "tous les jours"), ("ເກັ່ງ|ຂຶ້ນ", "de mieux en mieux"), ("ຊີວິດ", "vie")],
 "gram": {"t": "révision A1", "ex": [("ເຈົ້າ|ຊື່|ຫຍັງ|?", "question avec mot interrogatif"), ("ກິນເຂົ້າ|ແລ້ວ|ບໍ|?", "question fermée"), ("ກາເຟ|ສອງ|ຈອກ", "classificateur"), ("ງາມ|ກວ່າ", "comparaison")],
          "q": ["Pour chaque exemple, rappelle la règle."],
          "rule": "Bilan : ordre sujet-verbe-complément, questions sans inversion, ບໍ / ບໍ່, classificateurs, ກວ່າ, ຈະ pour le futur, ແລ້ວ pour l'accompli. Fais le test dans le projet avec /test."},
 "co": "le dialogue d'une traite, sans pause.",
 "ant": [("J'étudie le lao tous les jours.", "ຂ້ອຍ|ຮຽນ|ພາສາລາວ|ທຸກມື້|."), ("J'aime la cuisine lao.", "ຂ້ອຍ|ມັກ|ອາຫານ|ລາວ|."), ("Je parle un peu lao.", "ຂ້ອຍ|ເວົ້າລາວ|ໄດ້|ໜ້ອຍ|ໜຶ່ງ|.")],
 "ee": ["Écris un texte de 10 phrases pour te présenter complètement."],
 "task": "Fais le test de fin de niveau A1 (commande /test dans le projet) et une conversation de 5 minutes avec un natif.",
},
]
