# Partie F · Argumenter (B2), leçons 91 à 115
def L(n, title, obj, scene, dia, ce, voc, gt, gex, gq, grule, co, ant, ee, task, cult=None):
    d = {"n": n, "title": title, "obj": obj, "scene": scene, "dia": dia, "ce": ce, "voc": voc,
         "gram": {"t": gt, "ex": gex, "q": gq, "rule": grule}, "co": co, "ant": ant, "ee": ee, "task": task}
    if cult:
        d["cult"] = cult
    return d

LESSONS = [
L(91, "Structurer un argument", "Défendre une position avec trois arguments organisés.", "Débat en famille : faut-il apprendre l'anglais à l'école primaire ?",
  [("K", "ຂ້ອຍ|ຄິດ|ວ່າ|ຄວນ|ຮຽນ|ພາສາອັງກິດ|ແຕ່|ນ້ອຍ|.", "Je pense qu'il faut apprendre l'anglais dès petit."),
   ("K", "ທຳອິດ|,|ມັນ|ຊ່ວຍ|ໃຫ້|ຫາ|ວຽກ|ງ່າຍ|.", "Premièrement, ça aide à trouver du travail."),
   ("K", "ອັນ|ທີ|ສອງ|,|ເດັກນ້ອຍ|ຮຽນ|ພາສາ|ໄວ|.", "Deuxièmement, les enfants apprennent vite les langues."),
   ("K", "ສຸດທ້າຍ|,|ໂລກ|ເຊື່ອມ|ຕໍ່|ກັນ|ຫຼາຍ|ຂຶ້ນ|.", "Enfin, le monde est de plus en plus connecté."),
   ("S", "ເຫດຜົນ|ດີ|.|ແຕ່|ພາສາລາວ|ກໍ|ສຳຄັນ|ເດີ|.", "Bons arguments. Mais le lao aussi est important.")],
  [("Quelle est la position de Kèo ?", "Apprendre l'anglais dès petit."), ("Quels sont ses trois arguments ?", "Travail, facilité d'apprentissage des enfants, monde connecté.")],
  [("ທຳອິດ", "premièrement"), ("ອັນ|ທີ|ສອງ", "deuxièmement"), ("ສຸດທ້າຍ", "enfin"), ("ສະຫຼຸບ|ແລ້ວ", "en conclusion"), ("ເຫດຜົນ", "raison, argument"),
   ("ຫຼັກຖານ", "preuve"), ("ເຊື່ອມ|ຕໍ່", "relier, connecter"), ("ຈຸດ|ຢືນ", "position, point de vue")],
  "organiser une argumentation", [("ທຳອິດ|…|ອັນ|ທີ|ສອງ|…|ສຸດທ້າຍ|…", "premièrement… deuxièmement… enfin…"), ("ສະຫຼຸບ|ແລ້ວ|…", "en conclusion…")],
  [], "Thèse (ຂ້ອຍຄິດວ່າ), arguments numérotés (ທຳອິດ, ອັນທີສອງ, ສຸດທ້າຍ), exemples (ເຊັ່ນ), conclusion (ສະຫຼຸບແລ້ວ).",
  "les mots qui annoncent chaque argument.",
  [("Premièrement…", "ທຳອິດ|…"), ("En conclusion…", "ສະຫຼຸບ|ແລ້ວ|…"), ("Bons arguments.", "ເຫດຜົນ|ດີ|.")],
  ["Écris un argumentaire de 150 mots sur un sujet de société."], "Défends une position pendant 5 minutes face à un natif."),
L(92, "Nuancer", "Exprimer le doute, la probabilité et la certitude.", "Discussion sur l'avenir de Kèo.",
  [("C", "ເຈົ້າ|ຈະ|ສອບ|ເສັງ|ຜ່ານ|ບໍ|?", "Tu vas réussir ton examen ?"),
   ("K", "ອາດຈະ|ຜ່ານ|,|ແຕ່|ບໍ່|ແນ່ໃຈ|.", "Peut-être, mais je ne suis pas sûr."),
   ("N", "ຂ້ອຍ|ແນ່ໃຈ|ວ່າ|ເຈົ້າ|ຜ່ານ|ແນ່ນອນ|.", "Moi, je suis sûre que tu vas réussir."),
   ("K", "ຄົງຈະ|ຍາກ|ຢູ່|ເດ|.", "Ça va sûrement être dur quand même.")],
  [("Kèo est-il confiant ?", "Pas vraiment : peut-être, il n'est pas sûr."), ("Et Noy ?", "Elle est certaine qu'il réussira.")],
  [("ອາດຈະ", "peut-être"), ("ຄົງຈະ", "sans doute, sûrement"), ("ແນ່ນອນ", "certainement"), ("ແນ່ໃຈ", "être sûr"), ("ບາງທີ", "parfois ; peut-être"), ("ເບິ່ງ|ຄື|ວ່າ", "il semble que"),
   ("ສອບ|ເສັງ", "passer un examen"), ("ຜ່ານ", "réussir, passer")],
  "les degrés de certitude", [("ອາດຈະ|ຝົນ|ຕົກ", "il pleuvra peut-être"), ("ຄົງຈະ|ຝົນ|ຕົກ", "il va sûrement pleuvoir"), ("ຝົນ|ຕົກ|ແນ່ນອນ", "il va pleuvoir, c'est certain")],
  ["Classe ces mots du moins sûr au plus sûr."], "Du moins au plus sûr : ອາດຈະ (peut-être), ຄົງຈະ (sans doute), ແນ່ນອນ (certainement). ເບິ່ງຄືວ່າ = il semble que.",
  "les mots de certitude.",
  [("Peut-être, mais je ne suis pas sûr.", "ອາດຈະ|,|ແຕ່|ບໍ່|ແນ່ໃຈ|."), ("C'est certain.", "ແນ່ນອນ|."), ("Il semble que…", "ເບິ່ງ|ຄື|ວ່າ|…")],
  ["Écris 6 prédictions pour l'année prochaine avec des degrés de certitude."], "Discute avec un natif de l'avenir (le tien, le Laos) en nuançant."),
L(93, "Concession et opposition", "Reconnaître un point puis le contester.", "Clara et M. Somsak parlent du tourisme.",
  [("S", "ເຖິງແມ່ນວ່າ|ນັກທ່ອງທ່ຽວ|ເອົາ|ເງິນ|ມາ|,|ແຕ່|ກໍ|ສ້າງ|ບັນຫາ|ຄືກັນ|.", "Même si les touristes apportent de l'argent, ils créent aussi des problèmes."),
   ("C", "ຂ້ອຍ|ເຂົ້າໃຈ|,|ເຖິງຢ່າງໃດກໍ່ຕາມ|ຊາວບ້ານ|ມີ|ວຽກ|ຫຼາຍ|ຂຶ້ນ|.", "Je comprends, pourtant les villageois ont plus de travail."),
   ("S", "ແມ່ນ|,|ແຕ່|ປະເພນີ|ກໍ|ປ່ຽນ|ໄປ|.", "Oui, mais les traditions changent.")],
  [("Quel problème soulève M. Somsak ?", "Le tourisme crée des problèmes et change les traditions."), ("Quel argument oppose Clara ?", "Plus de travail pour les villageois.")],
  [("ເຖິງແມ່ນວ່າ", "même si, bien que"), ("ເຖິງຢ່າງໃດກໍ່ຕາມ", "pourtant, cependant"), ("ໃນ|ທາງ|ກົງກັນຂ້າມ", "au contraire"), ("ຊາວບ້ານ", "villageois"), ("ປະເພນີ", "tradition"),
   ("ຂໍ້ດີ", "avantage"), ("ຂໍ້ເສຍ", "inconvénient")],
  "concéder puis opposer", [("ເຖິງແມ່ນວ່າ|…|ແຕ່|…", "même si… pourtant…"), ("ມີ|ທັງ|ຂໍ້ດີ|ແລະ|ຂໍ້ເສຍ", "il y a des avantages et des inconvénients")],
  ["Que doit-on mettre après une proposition en ເຖິງແມ່ນວ່າ ?"], "ເຖິງແມ່ນວ່າ + concession, puis ແຕ່ (ກໍ) + opposition. ເຖິງຢ່າງໃດກໍ່ຕາມ en début de phrase = pourtant.",
  "les concessions.",
  [("Même si c'est cher…", "ເຖິງແມ່ນວ່າ|ແພງ|…"), ("Il y a des avantages et des inconvénients.", "ມີ|ທັງ|ຂໍ້ດີ|ແລະ|ຂໍ້ເສຍ|."), ("Pourtant…", "ເຖິງຢ່າງໃດກໍ່ຕາມ|…")],
  ["Écris les avantages et inconvénients du tourisme en 10 phrases."], "Débats des avantages et inconvénients d'un sujet avec un natif."),
L(94, "Cause et conséquence", "Expliquer un phénomène de société avec une chaîne de causes.", "Discussion sur l'exode rural.",
  [("N", "ເປັນຫຍັງ|ຄົນ|ໜຸ່ມ|ຈຶ່ງ|ອອກ|ຈາກ|ບ້ານ|ນອກ|?", "Pourquoi les jeunes quittent-ils les villages ?"),
   ("S", "ຍ້ອນ|ບໍ່|ມີ|ວຽກ|,|ດັ່ງນັ້ນ|ພວກເຂົາ|ຈຶ່ງ|ໄປ|ຫາ|ວຽກ|ໃນ|ເມືອງ|.", "Faute de travail, ils vont donc en chercher en ville."),
   ("S", "ຜົນ|ທີ່|ຕາມ|ມາ|ແມ່ນ|ບ້ານ|ນອກ|ມີ|ແຕ່|ຄົນ|ເຖົ້າ|.", "Conséquence : il ne reste que les anciens dans les villages.")],
  [("Pourquoi les jeunes partent-ils ?", "Faute de travail."), ("Quelle conséquence ?", "Il ne reste que les anciens au village.")],
  [("ດັ່ງນັ້ນ", "donc, c'est pourquoi"), ("ຈຶ່ງ", "(c'est pour cela que)"), ("ຜົນ|ທີ່|ຕາມ|ມາ", "la conséquence"), ("ສາເຫດ", "cause"), ("ເຮັດ|ໃຫ້", "provoquer, faire que"), ("ມີ|ແຕ່", "il n'y a que")],
  "les chaînes causales", [("ຍ້ອນ|…|ດັ່ງນັ້ນ|…|ຈຶ່ງ|…", "à cause de… donc… c'est pourquoi…"), ("ຝົນ|ເຮັດ|ໃຫ້|ນ້ຳ|ຖ້ວມ", "la pluie provoque des inondations")],
  ["Que fait ຈຶ່ງ devant le verbe ?"], "ຈຶ່ງ (devant le verbe) souligne que l'action est la conséquence de ce qui précède. ເຮັດໃຫ້ = provoquer. ສາເຫດ = cause, ຜົນ = effet.",
  "ດັ່ງນັ້ນ et ຈຶ່ງ.",
  [("C'est pourquoi ils partent.", "ດັ່ງນັ້ນ|ພວກເຂົາ|ຈຶ່ງ|ໄປ|."), ("La cause principale…", "ສາເຫດ|ຫຼັກ|…"), ("Ça provoque des problèmes.", "ມັນ|ເຮັດ|ໃຫ້|ມີ|ບັນຫາ|.")],
  ["Explique un phénomène de société de ton pays en chaîne causale (8 phrases)."], "Explique à un natif un phénomène de société français et demande son équivalent au Laos."),
L(95, "L'actualité", "Commenter une information du jour.", "Au petit-déjeuner, on commente les nouvelles.",
  [("S", "ໄດ້|ຍິນ|ຂ່າວ|ບໍ|?|ລັດຖະບານ|ຈະ|ສ້າງ|ທາງ|ໃໝ່|.", "Tu as entendu ? Le gouvernement va construire une nouvelle route."),
   ("C", "ຂ່າວ|ດີ|.|ແຕ່|ຈະ|ສຳເລັດ|ເມື່ອໃດ|?", "Bonne nouvelle. Mais elle sera finie quand ?"),
   ("S", "ຕາມ|ຂ່າວ|ແມ່ນ|ພາຍໃນ|ສອງ|ປີ|.", "D'après les infos, d'ici deux ans."),
   ("C", "ຫວັງ|ວ່າ|ຈະ|ທັນ|ເວລາ|.", "J'espère que ce sera dans les temps.")],
  [("Quelle est la nouvelle ?", "Une nouvelle route sera construite."), ("Dans quel délai ?", "D'ici deux ans.")],
  [("ຂ່າວ", "nouvelle, info"), ("ຕາມ|ຂ່າວ", "d'après les infos"), ("ລັດຖະບານ", "gouvernement"), ("ສຳເລັດ", "achever, réussir"), ("ພາຍໃນ", "d'ici, en (délai)"), ("ຫວັງ|ວ່າ", "espérer que"),
   ("ເມື່ອໃດ", "quand ?"), ("ໂຄງການ", "projet")],
  "rapporter une information", [("ຕາມ|ຂ່າວ|…", "d'après les infos…"), ("ມີ|ລາຍງານ|ວ່າ|…", "on rapporte que…")],
  [], "Pour rapporter une info sans s'engager : ຕາມຂ່າວ…, ມີລາຍງານວ່າ…, ໄດ້ຍິນວ່າ… Pour réagir : ຫວັງວ່າ (j'espère), ເປັນຫ່ວງວ່າ (je crains que).",
  "la source de l'information.",
  [("Tu as entendu la nouvelle ?", "ໄດ້|ຍິນ|ຂ່າວ|ບໍ|?"), ("D'après les infos…", "ຕາມ|ຂ່າວ|…"), ("J'espère que…", "ຫວັງ|ວ່າ|…")],
  ["Résume et commente une actualité lao en 10 phrases."], "Commente une actualité du jour avec un natif."),
L(96, "La radio et la télé", "Comprendre un journal télévisé et ses chiffres.", "Le journal du soir.",
  [("X", "ສະບາຍດີ|ທ່ານ|ຜູ້|ຊົມ|.|ຂ່າວ|ມື້ນີ້|…", "Bonsoir chers téléspectateurs. Les nouvelles du jour…"),
   ("X", "ອຸນຫະພູມ|ມື້ອື່ນ|ຈະ|ສູງ|ເຖິງ|ສາມສິບ|ແປດ|ອົງສາ|.", "Demain, la température atteindra 38 degrés."),
   ("C", "ເວົ້າ|ໄວ|ແທ້|!", "Ils parlent vraiment vite !"),
   ("N", "ຟັງ|ແຕ່|ຄຳ|ສຳຄັນ|ກໍ|ພໍ|.", "Écoute juste les mots importants, ça suffit.")],
  [("Quelle température est annoncée ?", "38 degrés.")],
  [("ຜູ້|ຊົມ", "téléspectateur"), ("ຜູ້|ຟັງ", "auditeur"), ("ອຸນຫະພູມ", "température"), ("ອົງສາ", "degré"), ("ລາຍງານ", "rapport, reportage"), ("ຄຳ|ສຳຄັນ", "mot-clé"),
   ("ສະຖິຕິ", "statistique"), ("ເປີເຊັນ", "pour cent")],
  "la langue des médias", [("ທ່ານ|ຜູ້|ຊົມ", "chers téléspectateurs"), ("ສູງ|ເຖິງ|…", "atteindre…")],
  [], "Les médias utilisent un registre formel (ທ່ານ, ຜູ້…, mots savants). Écoute d'abord les chiffres et les noms propres.",
  "les chiffres et les noms propres.",
  [("Ils parlent vraiment vite !", "ເວົ້າ|ໄວ|ແທ້|!"), ("38 degrés.", "ສາມສິບ|ແປດ|ອົງສາ|."), ("Écoute juste les mots-clés.", "ຟັງ|ແຕ່|ຄຳ|ສຳຄັນ|.")],
  ["Regarde 5 minutes d'un journal lao et note tous les chiffres entendus."], "Regarde un journal télévisé lao avec un natif et résume-le."),
L(97, "Les expressions imagées (1)", "Comprendre et placer des expressions courantes avec ໃຈ.", "Noy décrit des collègues.",
  [("N", "ຫົວໜ້າ|ຂ້ອຍ|ໃຈ|ກວ້າງ|ຫຼາຍ|.", "Mon chef est très généreux (cœur large)."),
   ("N", "ແຕ່|ເພື່ອນ|ຮ່ວມ|ງານ|ຄົນ|ໜຶ່ງ|ໃຈ|ແຄບ|.", "Mais un collègue est mesquin (cœur étroit)."),
   ("C", "ແລ້ວ|ເຈົ້າ|ເດ|?", "Et toi ?"),
   ("N", "ຂ້ອຍ|ໃຈ|ເຢັນ|!", "Moi, je suis calme (cœur froid) !")],
  [("Comment est le chef de Noy ?", "Généreux : ໃຈກວ້າງ."), ("Et Noy ?", "Calme : ໃຈເຢັນ.")],
  [("ໃຈ|ກວ້າງ", "généreux (cœur large)"), ("ໃຈ|ແຄບ", "mesquin (cœur étroit)"), ("ໃຈ|ເຢັນ", "calme (cœur froid)"), ("ໃຈ|ຮ້ອນ", "impatient (cœur chaud)"), ("ໃຈ|ດີ", "gentil"),
   ("ໃຈ|ແຂງ", "ferme, dur"), ("ໃຈ|ອ່ອນ", "sensible, faible"), ("ເພື່ອນ|ຮ່ວມ|ງານ", "collègue")],
  "les expressions en ໃຈ", [("ໃຈ|ເຢັນ|ໆ", "calme-toi"), ("ເສຍ|ໃຈ|ນຳ", "toutes mes condoléances / désolé pour toi")],
  [], "Le cœur (ໃຈ) est au centre de la psychologie lao : ໃຈເຢັນ (calme) est une qualité très valorisée, ໃຈຮ້ອນ (impatient) un défaut.",
  "les adjectifs après ໃຈ.",
  [("Calme-toi.", "ໃຈ|ເຢັນ|ໆ|."), ("Il est très généreux.", "ລາວ|ໃຈ|ກວ້າງ|ຫຼາຍ|."), ("Ne sois pas impatient.", "ຢ່າ|ໃຈ|ຮ້ອນ|.")],
  ["Décris 5 personnes de ton entourage avec des expressions en ໃຈ."], "Demande à un natif 5 autres expressions en ໃຈ et leur sens."),
L(98, "Les expressions imagées (2)", "Comprendre des images tirées du corps et des animaux.", "Kèo et ses amis se taquinent.",
  [("K", "ໝູ່|ຂ້ອຍ|ປາກ|ຫວານ|ຫຼາຍ|.", "Mon pote est un beau parleur (bouche sucrée)."),
   ("C", "ໝາຍ|ຄວາມ|ວ່າ|ແນວໃດ|?", "Ça veut dire quoi ?"),
   ("K", "ເວົ້າ|ເກັ່ງ|,|ເວົ້າ|ໃຫ້|ຄົນ|ມັກ|.", "Il parle bien, il sait se faire aimer."),
   ("K", "ແຕ່|ລາວ|ຫົວ|ແຂງ|ໂພດ|.", "Mais il est trop têtu (tête dure).")],
  [("Que veut dire ປາກຫວານ ?", "Beau parleur."), ("Et ຫົວແຂງ ?", "Têtu.")],
  [("ປາກ|ຫວານ", "beau parleur"), ("ຫົວ|ແຂງ", "têtu"), ("ຫົວ|ອ່ອນ", "docile"), ("ໜ້າ|ໜາ", "effronté (visage épais)"), ("ຕາ|ໄວ", "observateur (œil rapide)"), ("ໝາຍ|ຄວາມ|ວ່າ", "signifier")],
  "les métaphores du corps", [("ປາກ|ຫວານ", "bouche + sucré"), ("ໜ້າ|ໜາ", "visage + épais")],
  [], "Beaucoup d'expressions lao combinent une partie du corps et un adjectif. Elles décrivent le caractère. [Sens À VÉRIFIER avec un natif]",
  "les expressions imagées.",
  [("Ça veut dire quoi ?", "ໝາຍ|ຄວາມ|ວ່າ|ແນວໃດ|?"), ("Il est têtu.", "ລາວ|ຫົວ|ແຂງ|."), ("Beau parleur !", "ປາກ|ຫວານ|!")],
  ["Crée un petit portrait de 5 phrases avec des expressions imagées."], "Fais deviner à un natif le sens d'expressions françaises et demande les lao équivalentes."),
L(99, "L'humour", "Comprendre une blague et un jeu de mots sur les tons.", "Kèo raconte une blague.",
  [("K", "ຮູ້|ບໍ|ວ່າ|ເປັນຫຍັງ|…", "Tu sais pourquoi…"),
   ("C", "ບໍ່|ຮູ້|,|ເປັນຫຍັງ|?", "Non, pourquoi ?"),
   ("K", "…|ຕະຫຼົກ|ບໍ|?", "… C'est drôle, non ?"),
   ("C", "ຂ້ອຍ|ບໍ່|ເຂົ້າໃຈ|ມຸກ|.|ອະທິບາຍ|ແດ່|.", "Je n'ai pas compris la blague. Explique-moi."),
   ("K", "ມັນ|ຫຼິ້ນ|ສຽງ|.|ສອງ|ຄຳ|ນີ້|ຕ່າງ|ກັນ|ແຕ່|ສຽງ|ວັນນະຍຸດ|.", "C'est un jeu sur les sons. Ces deux mots ne diffèrent que par le ton.")],
  [("Pourquoi Clara ne comprend-elle pas ?", "C'est un jeu de mots sur les tons.")],
  [("ຕະຫຼົກ", "drôle"), ("ມຸກ", "blague", "[À VÉRIFIER]"), ("ເລົ່າ|ເລື່ອງ|ຕະຫຼົກ", "raconter une blague"), ("ຫົວ", "rire"), ("ຫຼິ້ນ|ຄຳ", "jeu de mots"), ("ສຽງ|ວັນນະຍຸດ", "ton (linguistique)"),
   ("ອະທິບາຍ", "expliquer")],
  "les jeux sur les tons", [("ຂາ|/|ຂ້າ", "jambe / tuer"), ("ໝາ|/|ມາ", "chien / venir")],
  [], "L'humour lao joue beaucoup sur les mots qui ne diffèrent que par le ton. Comprendre une blague est un excellent test de ton oreille.",
  "les paires de mots qui ne diffèrent que par le ton.",
  [("C'est drôle !", "ຕະຫຼົກ|!"), ("Je n'ai pas compris la blague.", "ບໍ່|ເຂົ້າໃຈ|ມຸກ|."), ("Explique-moi.", "ອະທິບາຍ|ແດ່|.")],
  ["Trouve 5 paires de mots qui ne diffèrent que par le ton."], "Demande à un natif de te raconter une blague lao et de te l'expliquer."),
L(100, "Les sous-entendus", "Comprendre la politesse indirecte et les refus implicites.", "Clara invite un collègue.",
  [("C", "ວັນເສົາ|ມາ|ກິນເຂົ້າ|ນຳ|ກັນ|ບໍ|?", "Samedi, tu viens manger ?"),
   ("X", "ເອີ|…|ຂ້ອຍ|ຈະ|ລອງ|ເບິ່ງ|ເດີ|.", "Euh… je vais voir."),
   ("N", "ລາວ|ບໍ່|ມາ|ດອກ|.", "(Après) Il ne viendra pas."),
   ("C", "ແຕ່|ລາວ|ບໍ່|ໄດ້|ບອກ|ວ່າ|ບໍ່|ມາ|!", "Mais il n'a pas dit qu'il ne venait pas !"),
   ("N", "«|ລອງ|ເບິ່ງ|»|ສ່ວນຫຼາຍ|ແມ່ນ|ບໍ່|.", "« Je vais voir », la plupart du temps, ça veut dire non.")],
  [("Le collègue vient-il ?", "Non, très probablement."), ("Comment l'a-t-on compris ?", "« Je vais voir » est un refus poli.")],
  [("ລອງ|ເບິ່ງ", "je vais voir (refus poli)"), ("ບໍ່|ສະດວກ", "ce n'est pas pratique (refus)"), ("ເກງໃຈ", "être gêné de déranger", "valeur centrale"), ("ຮັກສາ|ໜ້າ", "sauver la face"), ("ທາງອ້ອມ", "indirect")],
  "le refus indirect", [("ຂ້ອຍ|ຈະ|ລອງ|ເບິ່ງ", "je vais voir (= probablement non)"), ("ບໍ່|ຄ່ອຍ|ສະດວກ", "ce n'est pas très pratique (= non)")],
  [], "Dire « non » directement fait perdre la face. On refuse avec des formules vagues. ເກງໃຈ, la peur de déranger, explique beaucoup de comportements.",
  "le ton hésitant des refus.",
  [("Je vais voir.", "ຂ້ອຍ|ຈະ|ລອງ|ເບິ່ງ|."), ("Ce n'est pas très pratique.", "ບໍ່|ຄ່ອຍ|ສະດວກ|."), ("Ne sois pas gêné.", "ບໍ່|ຕ້ອງ|ເກງໃຈ|.")],
  ["Liste 5 façons indirectes de refuser en lao."], "Demande à un natif comment il refuse une invitation sans vexer."),
L(101, "Parler vite", "Suivre une conversation à plusieurs et ses formes rapides.", "Dîner animé chez Noy.",
  [("K", "ເຈົ້າ|ໄປ|ໃສ|ມາ|?|ບໍ່|ເຫັນ|ໜ້າ|ເລີຍ|.", "T'étais où ? On ne te voit plus."),
   ("N", "ວຽກ|ຫຼາຍ|ແທ້|ເດ|.", "Trop de boulot."),
   ("S", "ກິນ|ໆ|ໄປ|ກ່ອນ|,|ເຢັນ|ໝົດ|ແລ້ວ|.", "Mangez, mangez, ça refroidit."),
   ("C", "ພວກເຈົ້າ|ເວົ້າ|ໄວ|ຫຼາຍ|,|ຂ້ອຍ|ຕາມ|ບໍ່|ທັນ|!", "Vous parlez trop vite, je n'arrive pas à suivre !")],
  [("Pourquoi Clara a-t-elle du mal ?", "Tout le monde parle vite à la fois.")],
  [("ຕາມ|ບໍ່|ທັນ", "ne pas arriver à suivre"), ("ບໍ່|ເຫັນ|ໜ້າ", "on ne te voit plus"), ("ກິນ|ໆ", "mange, mange"), ("ໄປ|ໃສ|ມາ", "t'étais où ?"), ("ເວົ້າ|ໄວ", "parler vite")],
  "les formes rapides de l'oral", [("ໄປ|ໃສ|ມາ|?", "t'étais où ?"), ("ກິນ|ໆ|ໄປ", "mange, vas-y")],
  [], "À l'oral rapide, les natifs avalent des syllabes, répètent les verbes (ກິນໆ) et laissent tomber les pronoms. Entraîne-toi au shadowing sur de vrais enregistrements.",
  "les syllabes avalées.",
  [("Je n'arrive pas à suivre !", "ຕາມ|ບໍ່|ທັນ|!"), ("T'étais où ?", "ໄປ|ໃສ|ມາ|?"), ("On ne te voit plus.", "ບໍ່|ເຫັນ|ໜ້າ|ເລີຍ|.")],
  ["Transcris 1 minute d'une conversation lao rapide."], "Participe à une conversation à 3 natifs ou plus pendant 15 minutes."),
L(102, "Les dialectes", "Reconnaître le lao de Luang Prabang et du Sud.", "Voyage à Luang Prabang.",
  [("C", "ຄົນ|ຫຼວງພະບາງ|ເວົ້າ|ຕ່າງ|ຈາກ|ວຽງຈັນ|ບໍ|?", "Les gens de Luang Prabang parlent différemment de Vientiane ?"),
   ("N", "ຕ່າງ|ໜ້ອຍ|ໜຶ່ງ|.|ສຽງ|ວັນນະຍຸດ|ບໍ່|ຄື|ກັນ|.", "Un peu. Les tons ne sont pas les mêmes."),
   ("N", "ພາກໃຕ້|ກໍ|ມີ|ສຳນຽງ|ຂອງ|ເຂົາ|ເອງ|.", "Le Sud aussi a son propre accent."),
   ("C", "ເຂົ້າໃຈ|ກັນ|ໄດ້|ບໍ|?", "On se comprend quand même ?"),
   ("N", "ໄດ້|ສະບາຍ|.", "Oui, sans problème.")],
  [("Qu'est-ce qui change entre les régions ?", "Les tons, l'accent, quelques mots.")],
  [("ສຳນຽງ", "accent"), ("ພາສາ|ທ້ອງຖິ່ນ", "dialecte, parler local"), ("ສຽງ|ວັນນະຍຸດ", "ton"), ("ຕ່າງ|ຈາກ", "différent de"), ("ພາສາ|ມາດຕະຖານ", "langue standard")],
  "parler des variations", [("ເວົ້າ|ສຳນຽງ|ຫຼວງພະບາງ", "parler avec l'accent de Luang Prabang")],
  [], "Le lao de Vientiane est la norme. Luang Prabang et le Sud (Pakse, Champassak) ont d'autres systèmes tonals et quelques mots propres. [Détails À VÉRIFIER]",
  "les différences de mélodie entre régions.",
  [("Ils parlent différemment ?", "ເວົ້າ|ຕ່າງ|ກັນ|ບໍ|?"), ("Chaque région a son accent.", "ແຕ່ລະ|ພາກ|ມີ|ສຳນຽງ|."), ("On se comprend.", "ເຂົ້າໃຈ|ກັນ|ໄດ້|.")],
  ["Écoute un locuteur du Nord et un du Sud, et note 3 différences."], "Demande à un natif de quelle région il vient et quelles différences il remarque."),
L(103, "L'Isan et le lao", "Comprendre un locuteur d'Isan (nord-est de la Thaïlande).", "Un ami d'Isan rend visite.",
  [("X", "ຂ້ອຍ|ມາ|ແຕ່|ອີສານ|.", "Je viens de l'Isan."),
   ("C", "ພາສາ|ອີສານ|ຄື|ພາສາລາວ|ບໍ|?", "La langue de l'Isan, c'est comme le lao ?"),
   ("X", "ເກືອບ|ຄື|ກັນ|.|ແຕ່|ພວກເຮົາ|ຂຽນ|ດ້ວຍ|ຕົວໜັງສື|ໄທ|.", "Presque. Mais on écrit en alphabet thaï."),
   ("C", "ໜ້າ|ສົນໃຈ|ຫຼາຍ|!", "C'est très intéressant !")],
  [("D'où vient l'ami ?", "De l'Isan."), ("Quelle différence avec le lao ?", "Il s'écrit en alphabet thaï.")],
  [("ອີສານ", "Isan (nord-est de la Thaïlande)"), ("ຄື|ກັນ", "pareil"), ("ເກືອບ|ຄື|ກັນ", "presque pareil"), ("ຕົວໜັງສື", "écriture, lettres"), ("ຊົນເຜົ່າ", "ethnie")],
  "pareil, presque, différent", [("ຄື|ກັນ", "pareil"), ("ເກືອບ|ຄື|ກັນ", "presque pareil"), ("ຕ່າງ|ກັນ|ຫຼາຍ", "très différent")],
  [], "La population d'Isan parle des variétés de lao, mais lit et écrit en thaï. Beaucoup de mots thaïs y sont mélangés. [À VÉRIFIER]",
  "les mots thaïs mélangés au lao.",
  [("C'est presque pareil.", "ເກືອບ|ຄື|ກັນ|."), ("C'est très intéressant.", "ໜ້າ|ສົນໃຈ|ຫຼາຍ|.")],
  ["Écris 5 phrases sur les liens entre le Laos et l'Isan."], "Écoute un chanteur de molam d'Isan et repère les mots lao."),
L(104, "Économie du quotidien", "Discuter de prix, de salaires et de commerce avec des chiffres.", "M. Somsak parle de son commerce.",
  [("S", "ປີນີ້|ຍອດ|ຂາຍ|ເພີ່ມ|ຂຶ້ນ|ສິບ|ເປີເຊັນ|.", "Cette année, les ventes ont augmenté de 10 %."),
   ("C", "ຍ້ອນ|ຫຍັງ|?", "Grâce à quoi ?"),
   ("S", "ນັກທ່ອງທ່ຽວ|ຫຼາຍ|ຂຶ້ນ|.|ແຕ່|ຕົ້ນທຶນ|ກໍ|ສູງ|ຂຶ້ນ|.", "Plus de touristes. Mais les coûts ont aussi augmenté."),
   ("C", "ເງິນເຟີ້|ສູງ|ບໍ|?", "L'inflation est forte ?"),
   ("S", "ສູງ|ຫຼາຍ|,|ເງິນ|ກີບ|ອ່ອນ|ຄ່າ|.", "Très, le kip a perdu de la valeur.")],
  [("De combien les ventes ont-elles augmenté ?", "10 %."), ("Quel problème ?", "L'inflation et la hausse des coûts.")],
  [("ຍອດ|ຂາຍ", "chiffre de ventes"), ("ເປີເຊັນ", "pour cent"), ("ຕົ້ນທຶນ", "coût"), ("ກຳໄລ", "bénéfice"), ("ເງິນເຟີ້", "inflation"), ("ອ່ອນ|ຄ່າ", "perdre de la valeur"),
   ("ລາຍໄດ້", "revenu"), ("ເງິນເດືອນ", "salaire")],
  "les chiffres et les tendances", [("ເພີ່ມ|ຂຶ້ນ|ສິບ|ເປີເຊັນ", "augmenter de 10 %"), ("ຫຼຸດ|ລົງ|ເຄິ່ງ|ໜຶ່ງ", "baisser de moitié")],
  [], "Verbe de tendance + ຂຶ້ນ / ລົງ + chiffre. ເຄິ່ງໜຶ່ງ = la moitié, ສອງເທົ່າ = le double.",
  "les pourcentages.",
  [("Les ventes ont augmenté de 10 %.", "ຍອດ|ຂາຍ|ເພີ່ມ|ຂຶ້ນ|ສິບ|ເປີເຊັນ|."), ("Les coûts ont augmenté.", "ຕົ້ນທຶນ|ສູງ|ຂຶ້ນ|."), ("L'inflation est forte.", "ເງິນເຟີ້|ສູງ|.")],
  ["Compare le coût de la vie en France et au Laos en 8 phrases avec des chiffres."], "Discute du coût de la vie avec un natif."),
L(105, "Environnement", "Débattre d'un sujet écologique avec du vocabulaire abstrait.", "Discussion sur les barrages du Mékong.",
  [("C", "ເຂື່ອນ|ໃນ|ແມ່ນ້ຳຂອງ|ມີ|ຜົນ|ກະທົບ|ແນວໃດ|?", "Quel impact ont les barrages sur le Mékong ?"),
   ("S", "ສ້າງ|ໄຟຟ້າ|ໄດ້|ຫຼາຍ|,|ແຕ່|ປາ|ກໍ|ຫຼຸດ|ລົງ|.", "Ils produisent beaucoup d'électricité, mais les poissons diminuent."),
   ("N", "ຕ້ອງ|ຊອກ|ຫາ|ຄວາມ|ສົມດຸນ|ລະຫວ່າງ|ການ|ພັດທະນາ|ແລະ|ທຳມະຊາດ|.", "Il faut trouver un équilibre entre développement et nature.")],
  [("Quel est l'avantage des barrages ?", "L'électricité."), ("L'inconvénient ?", "Moins de poissons.")],
  [("ສິ່ງແວດລ້ອມ", "environnement"), ("ເຂື່ອນ", "barrage"), ("ຜົນ|ກະທົບ", "impact"), ("ໄຟຟ້າ", "électricité"), ("ທຳມະຊາດ", "nature"), ("ການ|ພັດທະນາ", "le développement"),
   ("ຄວາມ|ສົມດຸນ", "l'équilibre"), ("ມົນລະພິດ", "pollution")],
  "les noms abstraits", [("ການ|ພັດທະນາ", "le développement"), ("ຄວາມ|ສົມດຸນ", "l'équilibre"), ("ຜົນ|ກະທົບ|ຕໍ່|…", "l'impact sur…")],
  [], "Le vocabulaire abstrait se forme souvent avec ການ (action) ou ຄວາມ (état), et emprunte au pali-sanskrit (ທຳມະຊາດ, ສິ່ງແວດລ້ອມ).",
  "les mots savants.",
  [("Quel est l'impact ?", "ມີ|ຜົນ|ກະທົບ|ແນວໃດ|?"), ("Il faut un équilibre.", "ຕ້ອງ|ມີ|ຄວາມ|ສົມດຸນ|."), ("La pollution augmente.", "ມົນລະພິດ|ເພີ່ມ|ຂຶ້ນ|.")],
  ["Écris un texte de 150 mots sur un problème environnemental."], "Débats d'un sujet écologique avec un natif."),
L(106, "Éducation", "Comparer deux systèmes scolaires de façon argumentée.", "Clara et Noy comparent l'école.",
  [("N", "ຢູ່|ຝຣັ່ງ|ເດັກ|ຮຽນ|ຈັກ|ໂມງ|ຕໍ່|ມື້|?", "En France, les enfants ont cours combien d'heures par jour ?"),
   ("C", "ປະມານ|ຫົກ|ຊົ່ວໂມງ|.|ແລ້ວ|ຢູ່|ລາວ|ເດ|?", "Environ six heures. Et au Laos ?"),
   ("N", "ຄ້າຍ|ກັນ|.|ແຕ່|ຫຼາຍ|ຄົນ|ຮຽນ|ພິເສດ|ຕອນແລງ|ອີກ|.", "Pareil. Mais beaucoup suivent des cours particuliers le soir.")],
  [("Combien d'heures de cours ?", "Environ six heures dans les deux pays."), ("Quelle différence ?", "Beaucoup d'élèves lao suivent des cours particuliers le soir.")],
  [("ການສຶກສາ", "éducation"), ("ໂຮງຮຽນ|ປະຖົມ", "école primaire"), ("ມັດທະຍົມ", "secondaire"), ("ມະຫາວິທະຍາໄລ", "université"), ("ຮຽນ|ພິເສດ", "cours particuliers"),
   ("ຕໍ່|ມື້", "par jour"), ("ຫຼັກສູດ", "programme scolaire")],
  "comparer argumenté", [("ທັງ|ສອງ|ປະເທດ|…", "dans les deux pays…"), ("ໃນ|ຂະນະ|ທີ່|…", "tandis que…")],
  [], "ໃນຂະນະທີ່ = tandis que, pour opposer deux faits. ທັງສອງ = les deux.",
  "les comparaisons.",
  [("Tandis qu'au Laos…", "ໃນ|ຂະນະ|ທີ່|ຢູ່|ລາວ|…"), ("Dans les deux pays.", "ທັງ|ສອງ|ປະເທດ|."), ("Des cours particuliers.", "ຮຽນ|ພິເສດ|.")],
  ["Compare l'école en France et au Laos en 10 phrases."], "Interroge un natif sur sa scolarité et compare avec la tienne."),
L(107, "Santé publique", "Expliquer un traitement ou une prévention.", "Campagne contre la dengue.",
  [("M", "ໄຂ້ຍຸງລາຍ|ແຜ່|ລະບາດ|ໃນ|ລະດູຝົນ|.", "La dengue se propage pendant la saison des pluies."),
   ("M", "ເພື່ອ|ປ້ອງກັນ|,|ຕ້ອງ|ເທ|ນ້ຳ|ທີ່|ຂັງ|ອອກ|.", "Pour la prévenir, il faut vider l'eau stagnante."),
   ("C", "ມີ|ວັກຊີນ|ບໍ|?", "Il y a un vaccin ?"),
   ("M", "ມີ|,|ແຕ່|ການ|ປ້ອງກັນ|ຍຸງ|ກັດ|ສຳຄັນ|ທີ່ສຸດ|.", "Oui, mais éviter les piqûres reste le plus important.")],
  [("Quand la dengue se propage-t-elle ?", "Pendant la saison des pluies."), ("Comment la prévenir ?", "Vider l'eau stagnante, éviter les piqûres.")],
  [("ໄຂ້ຍຸງລາຍ", "dengue"), ("ແຜ່|ລະບາດ", "se propager (épidémie)"), ("ປ້ອງກັນ", "prévenir, protéger"), ("ວັກຊີນ", "vaccin"), ("ຍຸງ|ກັດ", "piqûre de moustique"), ("ອາການ", "symptôme"),
   ("ປິ່ນປົວ", "soigner")],
  "expliquer un but et un moyen", [("ເພື່ອ|ປ້ອງກັນ|…|ຕ້ອງ|…", "pour prévenir…, il faut…"), ("ໂດຍ|ການ|…", "en (+ verbe)")],
  [], "ເພື່ອ + but, ຕ້ອງ + moyen. ໂດຍການ + verbe = en faisant (moyen).",
  "le vocabulaire médical.",
  [("Pour prévenir, il faut…", "ເພື່ອ|ປ້ອງກັນ|,|ຕ້ອງ|…"), ("Quels sont les symptômes ?", "ມີ|ອາການ|ແນວໃດ|?"), ("Il y a un vaccin ?", "ມີ|ວັກຊີນ|ບໍ|?")],
  ["Écris une affiche de prévention de 6 phrases."], "Explique à un natif une règle de santé, puis demande ses conseils."),
L(108, "Technologie", "Parler des réseaux sociaux, des emprunts et des néologismes.", "Kèo et son téléphone.",
  [("B", "ແກ້ວ|ຫຼິ້ນ|ໂທລະສັບ|ທັງ|ມື້|!", "Kèo est sur son téléphone toute la journée !"),
   ("K", "ຂ້ອຍ|ໂພສ|ວິດີໂອ|ລົງ|ເຟສບຸກ|.", "Je poste des vidéos sur Facebook."),
   ("C", "ມີ|ຄົນ|ຕິດຕາມ|ຫຼາຍ|ບໍ|?", "Tu as beaucoup d'abonnés ?"),
   ("K", "ສອງ|ພັນ|ຄົນ|ແລ້ວ|!", "Deux mille déjà !")],
  [("Que fait Kèo ?", "Il poste des vidéos sur Facebook."), ("Combien d'abonnés ?", "Deux mille.")],
  [("ໂພສ", "poster"), ("ຕິດຕາມ", "suivre, abonné"), ("ກົດ|ໄລ້", "liker", "[À VÉRIFIER]"), ("ແຊຣ໌", "partager", "[À VÉRIFIER]"), ("ແອັບ", "application"), ("ອິນເຕີເນັດ", "internet"),
   ("ສື່|ສັງຄົມ", "réseaux sociaux")],
  "les emprunts", [("ໂພສ", "« post »"), ("ແອັບ", "« app »"), ("ເຟສບຸກ", "Facebook")],
  [], "Le vocabulaire numérique vient souvent de l'anglais, adapté aux sons lao. Il existe parfois aussi un mot lao officiel moins utilisé.",
  "les mots empruntés à l'anglais.",
  [("Je poste des vidéos.", "ຂ້ອຍ|ໂພສ|ວິດີໂອ|."), ("Tu as beaucoup d'abonnés ?", "ມີ|ຄົນ|ຕິດຕາມ|ຫຼາຍ|ບໍ|?"), ("Les réseaux sociaux.", "ສື່|ສັງຄົມ|.")],
  ["Écris un post de réseau social en lao (5 phrases)."], "Publie (ou écris) un vrai post en lao et fais-le relire par un natif."),
L(109, "Traditions en mouvement", "Discuter des traditions et de leur évolution en nuançant.", "Débat sur les mariages modernes.",
  [("B", "ແຕ່ກ່ອນ|ງານ|ແຕ່ງງານ|ເຮັດ|ຢູ່|ເຮືອນ|.|ດຽວນີ້|ເຮັດ|ຢູ່|ໂຮງແຮມ|.", "Avant, les mariages se faisaient à la maison. Maintenant, à l'hôtel."),
   ("N", "ມັນ|ສະດວກ|ກວ່າ|ແມ່|.", "C'est plus pratique, maman."),
   ("B", "ແຕ່|ສູນເສຍ|ຄວາມ|ອົບອຸ່ນ|.", "Mais on perd la chaleur."),
   ("C", "ບາງ|ປະເພນີ|ປ່ຽນ|,|ແຕ່|ຄຸນຄ່າ|ຍັງ|ຢູ່|.", "Certaines traditions changent, mais les valeurs restent.")],
  [("Où se font les mariages maintenant ?", "À l'hôtel."), ("Que regrette Mme Boua ?", "La chaleur des mariages à la maison.")],
  [("ປະເພນີ", "tradition"), ("ວັດທະນະທຳ", "culture"), ("ຄຸນຄ່າ", "valeur"), ("ສູນເສຍ", "perdre"), ("ອົບອຸ່ນ", "chaleureux"), ("ທັນສະໄໝ", "moderne"), ("ຮັກສາ", "préserver")],
  "nuancer un jugement culturel", [("ບາງ|…|ປ່ຽນ|,|ແຕ່|…", "certains… changent, mais…"), ("ໃນ|ແງ່|ໜຶ່ງ|…", "d'un côté…")],
  [], "Pour nuancer : ໃນແງ່ໜຶ່ງ… ໃນອີກແງ່ໜຶ່ງ… (d'un côté… de l'autre…), ບາງ (certains), ຍັງ (encore).",
  "les nuances.",
  [("D'un côté…", "ໃນ|ແງ່|ໜຶ່ງ|…"), ("Les valeurs restent.", "ຄຸນຄ່າ|ຍັງ|ຢູ່|."), ("Il faut préserver la culture.", "ຕ້ອງ|ຮັກສາ|ວັດທະນະທຳ|.")],
  ["Écris un texte nuancé de 150 mots sur une tradition qui change."], "Discute avec un natif d'une tradition lao et de son évolution."),
L(110, "Lire un texte long", "Comprendre et résumer un article complet.", "Clara lit un long article avec Noy.",
  [("C", "ບົດຄວາມ|ນີ້|ຍາວ|ຫຼາຍ|.", "Cet article est très long."),
   ("N", "ອ່ານ|ຫົວຂໍ້|ກັບ|ຫຍໍ້|ໜ້າ|ທຳອິດ|ກ່ອນ|.", "Lis d'abord le titre et le premier paragraphe."),
   ("N", "ແລ້ວ|ຊອກ|ຫາ|ຄຳ|ເຊື່ອມ|:|ສະນັ້ນ|,|ແຕ່|,|ນອກຈາກນັ້ນ|.", "Puis cherche les connecteurs : donc, mais, de plus.")],
  [("Quelle méthode conseille Noy ?", "Titre, premier paragraphe, puis les connecteurs.")],
  [("ບົດຄວາມ", "article"), ("ຫຍໍ້|ໜ້າ", "paragraphe"), ("ຄຳ|ເຊື່ອມ", "connecteur"), ("ນອກຈາກນັ້ນ", "de plus"), ("ໂດຍ|ລວມ", "globalement"), ("ໃຈຄວາມ|ສຳຄັນ", "idée principale")],
  "les connecteurs écrits", [("ນອກຈາກນັ້ນ", "de plus"), ("ໃນ|ທາງ|ກົງກັນຂ້າມ", "au contraire"), ("ໂດຍ|ລວມ", "globalement")],
  [], "À l'écrit, les connecteurs organisent le texte : ນອກຈາກນັ້ນ (de plus), ໃນທາງກົງກັນຂ້າມ (au contraire), ດັ່ງນັ້ນ (donc), ໂດຍລວມ (globalement).",
  "la structure du texte.",
  [("De plus…", "ນອກຈາກນັ້ນ|…"), ("L'idée principale est…", "ໃຈຄວາມ|ສຳຄັນ|ແມ່ນ|…"), ("Globalement…", "ໂດຍ|ລວມ|…")],
  ["Résume un article lao de 600 mots en 100 mots."], "Lis un article avec un natif et compare vos résumés."),
L(111, "Écrire un texte argumenté", "Rédiger 300 mots sur un sujet de société.", "Clara écrit pour un blog.",
  [("C", "ຂ້ອຍ|ຈະ|ຂຽນ|ກ່ຽວກັບ|ການ|ຮຽນ|ພາສາ|.", "Je vais écrire sur l'apprentissage des langues."),
   ("N", "ວາງ|ໂຄງ|ກ່ອນ|:|ບົດ|ນຳ|,|ເນື້ອ|ເລື່ອງ|,|ບົດ|ສະຫຼຸບ|.", "Fais un plan d'abord : introduction, développement, conclusion."),
   ("C", "ຂອບໃຈ|.|ຊ່ວຍ|ກວດ|ໃຫ້|ແດ່|ເດີ|.", "Merci. Tu me relis, hein.")],
  [("Quel plan conseille Noy ?", "Introduction, développement, conclusion.")],
  [("ວາງ|ໂຄງ", "faire un plan"), ("ບົດ|ນຳ", "introduction"), ("ເນື້ອ|ເລື່ອງ", "développement, contenu"), ("ບົດ|ສະຫຼຸບ", "conclusion"), ("ກວດ", "vérifier, relire"), ("ບົດ|ຄວາມ", "article, texte")],
  "la structure écrite", [("ບົດ|ນຳ|…|ເນື້ອ|ເລື່ອງ|…|ບົດ|ສະຫຼຸບ", "intro… développement… conclusion")],
  [], "Un texte argumenté lao suit le même plan qu'en français. À l'écrit, on évite les particules orales (ເດີ, ເນາະ) et on préfère les connecteurs écrits.",
  "relis ton texte à voix haute.",
  [("Fais un plan d'abord.", "ວາງ|ໂຄງ|ກ່ອນ|."), ("Tu peux me relire ?", "ຊ່ວຍ|ກວດ|ໃຫ້|ແດ່|ໄດ້|ບໍ|?")],
  ["Écris un texte argumenté de 300 mots."], "Fais corriger ton texte par un natif et réécris-le."),
L(112, "Négocier", "Négocier un accord : proposer, concéder, conclure.", "M. Somsak négocie avec un fournisseur.",
  [("S", "ຖ້າ|ຂ້ອຍ|ສັ່ງ|ຫຼາຍ|ຂຶ້ນ|,|ຫຼຸດ|ລາຄາ|ໄດ້|ບໍ|?", "Si je commande plus, vous pouvez baisser le prix ?"),
   ("X", "ໄດ້|ຫ້າ|ເປີເຊັນ|.", "De 5 %."),
   ("S", "ສິບ|ເປີເຊັນ|ແລ້ວ|ຂ້ອຍ|ຈ່າຍ|ເງິນສົດ|.", "10 % et je paie comptant."),
   ("X", "ພົບ|ກັນ|ເຄິ່ງ|ທາງ|,|ເຈັດ|ເປີເຊັນ|.", "Coupons la poire en deux : 7 %."),
   ("S", "ຕົກລົງ|!", "Marché conclu !")],
  [("Quelle remise est finalement accordée ?", "7 %.")],
  [("ສັ່ງ", "commander"), ("ສະເໜີ", "proposer"), ("ຍອມ", "accepter, céder"), ("ພົບ|ກັນ|ເຄິ່ງ|ທາງ", "couper la poire en deux"), ("ເງິນສົດ", "argent liquide"), ("ຕົກລົງ", "conclure, d'accord"),
   ("ເງື່ອນໄຂ", "condition")],
  "la négociation", [("ຖ້າ|…|ໄດ້|ບໍ|?", "si…, est-ce possible ?"), ("ຂ້ອຍ|ຍອມ|…|ຖ້າ|…", "j'accepte… si…")],
  [], "Négocier : proposition conditionnelle (ຖ້າ…ໄດ້ບໍ), contre-proposition, compromis (ພົບກັນເຄິ່ງທາງ), conclusion (ຕົກລົງ).",
  "les chiffres et les conditions.",
  [("Si je commande plus…", "ຖ້າ|ຂ້ອຍ|ສັ່ງ|ຫຼາຍ|ຂຶ້ນ|…"), ("Coupons la poire en deux.", "ພົບ|ກັນ|ເຄິ່ງ|ທາງ|."), ("Marché conclu !", "ຕົກລົງ|!")],
  ["Écris une négociation de 10 répliques."], "Négocie avec un natif (jeu de rôle commercial)."),
L(113, "Présenter en public", "Faire une présentation organisée de 5 minutes.", "Clara présente son projet à l'école.",
  [("C", "ສະບາຍດີ|ທຸກ|ທ່ານ|.|ມື້ນີ້|ຂ້ອຍ|ຈະ|ນຳສະເໜີ|ໂຄງການ|ຂອງ|ຂ້ອຍ|.", "Bonjour à tous. Aujourd'hui, je vais présenter mon projet."),
   ("C", "ຂ້ອຍ|ຈະ|ເວົ້າ|ສາມ|ຫົວຂໍ້|.", "Je vais parler de trois points."),
   ("C", "ຂອບໃຈ|ທີ່|ຮັບຟັງ|.|ມີ|ຄຳຖາມ|ບໍ|?", "Merci de votre attention. Des questions ?")],
  [("Comment Clara commence-t-elle ?", "Elle salue et annonce son sujet."), ("Comment termine-t-elle ?", "Elle remercie et demande s'il y a des questions.")],
  [("ນຳສະເໜີ", "présenter"), ("ທຸກ|ທ່ານ", "à tous (poli)"), ("ຫົວຂໍ້", "point, sujet"), ("ຮັບຟັງ", "écouter (poli)"), ("ຄຳຖາມ", "question"), ("ໂຄງການ", "projet")],
  "les formules de présentation", [("ມື້ນີ້|ຂ້ອຍ|ຈະ|ນຳສະເໜີ|…", "aujourd'hui je vais présenter…"), ("ຂອບໃຈ|ທີ່|ຮັບຟັງ", "merci de votre attention")],
  [], "Ouverture (ສະບາຍດີທຸກທ່ານ), annonce du plan, développement, remerciements (ຂອບໃຈທີ່ຮັບຟັງ), questions.",
  "le rythme d'une présentation.",
  [("Bonjour à tous.", "ສະບາຍດີ|ທຸກ|ທ່ານ|."), ("Merci de votre attention.", "ຂອບໃຈ|ທີ່|ຮັບຟັງ|."), ("Des questions ?", "ມີ|ຄຳຖາມ|ບໍ|?")],
  ["Écris le script d'une présentation de 5 minutes."], "Fais une présentation de 5 minutes devant un ou plusieurs natifs."),
L(114, "Films et séries", "Analyser une scène de film lao, avec langue familière et argot.", "Soirée cinéma lao.",
  [("K", "ຕົວລະຄອນ|ນີ້|ເວົ້າ|ພາສາ|ໄວລຸ້ນ|.", "Ce personnage parle comme les jeunes."),
   ("C", "ຂ້ອຍ|ບໍ່|ເຂົ້າໃຈ|ບາງ|ຄຳ|.", "Je ne comprends pas certains mots."),
   ("K", "ແມ່ນ|ຄຳ|ສະແລງ|.|ຂ້ອຍ|ອະທິບາຍ|ໃຫ້|.", "C'est de l'argot. Je t'explique.")],
  [("Pourquoi Clara ne comprend-elle pas ?", "Le personnage parle en argot de jeunes.")],
  [("ຕົວລະຄອນ", "personnage"), ("ສະແລງ", "argot", "[À VÉRIFIER]"), ("ໄວລຸ້ນ", "adolescent"), ("ສາກ", "scène"), ("ຜູ້|ກຳກັບ", "réalisateur"), ("ນັກສະແດງ", "acteur")],
  "analyser une scène", [("ໃນ|ສາກ|ນີ້|…", "dans cette scène…"), ("ຕົວລະຄອນ|ຮູ້ສຶກ|…", "le personnage ressent…")],
  [], "Pour analyser : qui (ຕົວລະຄອນ), quoi (ສາກ), comment on le dit (registre, argot), pourquoi (intention).",
  "le registre familier.",
  [("Dans cette scène…", "ໃນ|ສາກ|ນີ້|…"), ("C'est de l'argot.", "ແມ່ນ|ຄຳ|ສະແລງ|."), ("Je t'explique.", "ຂ້ອຍ|ອະທິບາຍ|ໃຫ້|.")],
  ["Analyse une scène de film lao en 10 phrases."], "Regarde un film lao avec un natif et commentez une scène ensemble."),
L(115, "Bilan B2", "Faire le point sur les 4 compétences du niveau B2.", "Débat final entre Clara et M. Somsak.",
  [("S", "ເຈົ້າ|ຄິດ|ວ່າ|ລາວ|ຄວນ|ພັດທະນາ|ແນວໃດ|?", "À ton avis, comment le Laos devrait-il se développer ?"),
   ("C", "ເຖິງແມ່ນວ່າ|ການ|ທ່ອງທ່ຽວ|ສຳຄັນ|,|ແຕ່|ການສຶກສາ|ສຳຄັນ|ກວ່າ|.", "Même si le tourisme est important, l'éducation l'est davantage."),
   ("S", "ເຫດຜົນ|ຂອງ|ເຈົ້າ|ໜັກແໜ້ນ|.", "Ton argument est solide.")],
  [("Quelle est la position de Clara ?", "L'éducation est plus importante que le tourisme.")],
  [("ໜັກແໜ້ນ", "solide (argument)"), ("ພັດທະນາ", "développer")],
  "révision B2", [("ເຖິງແມ່ນວ່າ|…|ແຕ່|…", "concession"), ("ດັ່ງນັ້ນ|…|ຈຶ່ງ|…", "conséquence"), ("ອາດຈະ|/|ຄົງຈະ|/|ແນ່ນອນ", "certitude")],
  [], "Bilan B2 : argumentation structurée, nuance, concession, cause et conséquence, registres médiatiques, expressions imagées, implicite. Fais le test /test.",
  "un débat à vitesse réelle.",
  [("Ton argument est solide.", "ເຫດຜົນ|ຂອງ|ເຈົ້າ|ໜັກແໜ້ນ|.")],
  ["Écris un essai argumenté de 400 mots."], "Fais le test de fin de niveau B2 et un débat de 30 minutes avec un natif."),
]
