# Partie D · Raconter et organiser (A2), leçons 41 à 65
def L(n, title, obj, scene, dia, ce, voc, gt, gex, gq, grule, co, ant, ee, task, cult=None):
    d = {"n": n, "title": title, "obj": obj, "scene": scene, "dia": dia, "ce": ce, "voc": voc,
         "gram": {"t": gt, "ex": gex, "q": gq, "rule": grule}, "co": co, "ant": ant, "ee": ee, "task": task}
    if cult:
        d["cult"] = cult
    return d

LESSONS = [
L(41, "Hier", "Raconter ce que tu as fait hier.", "Lundi matin, Noy demande à Clara son week-end.",
  [("N", "ມື້ວານ|ເຈົ້າ|ໄປ|ໃສ|ມາ|?", "Hier, tu es allée où ?"),
   ("C", "ຂ້ອຍ|ໄປ|ວັດ|ກັບ|ແມ່ບົວ|.", "Je suis allée à la pagode avec Mme Boua."),
   ("N", "ແລ້ວ|ໄດ້|ເຮັດ|ຫຍັງ|ອີກ|?", "Et tu as fait quoi d'autre ?"),
   ("C", "ໄດ້|ກິນ|ເຝີ|ແລ້ວ|ກັບ|ເຮືອນ|.", "J'ai mangé une pho puis je suis rentrée."),
   ("N", "ມ່ວນ|ບໍ|?", "C'était bien ?"),
   ("C", "ມ່ວນ|ຫຼາຍ|!", "Super !")],
  [("Où est allée Clara ?", "À la pagode avec Mme Boua."), ("Qu'a-t-elle fait ensuite ?", "Elle a mangé une pho puis est rentrée.")],
  [("ມື້ວານ", "hier"), ("ອາທິດກ່ອນ", "la semaine dernière"), ("ປີກາຍ", "l'année dernière"), ("ໄດ້", "(marque du passé réalisé)"), ("ແລ້ວ", "déjà ; c'est fait"),
   ("ໄປ|…|ມາ", "être allé (et revenu)"), ("ອີກ", "encore, d'autre"), ("ມ່ວນ", "amusant, sympa")],
  "le passé sans conjugaison", [("ມື້ວານ|ຂ້ອຍ|ໄປ|ຕະຫຼາດ", "hier, je suis allée au marché"), ("ຂ້ອຍ|ໄດ້|ກິນ|ເຝີ", "j'ai mangé une pho"), ("ກິນ|ແລ້ວ", "j'ai (déjà) mangé")],
  ["Le verbe change-t-il au passé ?", "Qu'apportent ໄດ້ et ແລ້ວ ?"],
  "Le verbe ne change jamais. Le passé se comprend par un mot de temps (ມື້ວານ), par ໄດ້ devant le verbe (l'action a bien eu lieu) ou par ແລ້ວ après (c'est fait).",
  "les mots de temps en début de phrase.",
  [("Hier, tu es allée où ?", "ມື້ວານ|ເຈົ້າ|ໄປ|ໃສ|ມາ|?"), ("Je suis allée au marché.", "ຂ້ອຍ|ໄປ|ຕະຫຼາດ|ມາ|."), ("J'ai mangé une pho.", "ຂ້ອຍ|ໄດ້|ກິນ|ເຝີ|."), ("C'était super !", "ມ່ວນ|ຫຼາຍ|!")],
  ["Raconte ta journée d'hier en 6 phrases."], "Raconte ton dernier week-end à un natif pendant 2 minutes."),
L(42, "Demain", "Annoncer tes projets pour demain et le week-end.", "Kèo parle de ses projets.",
  [("C", "ມື້ອື່ນ|ເຈົ້າ|ຈະ|ເຮັດ|ຫຍັງ|?", "Demain, tu vas faire quoi ?"),
   ("K", "ຂ້ອຍ|ຈະ|ໄປ|ຫຼິ້ນ|ບານ|ກັບ|ໝູ່|.", "Je vais jouer au foot avec des amis."),
   ("C", "ແລ້ວ|ອາທິດໜ້າ|ເດ|?", "Et la semaine prochaine ?"),
   ("K", "ຈະ|ໄປ|ທ່ຽວ|ຫຼວງພະບາງ|.", "Je vais visiter Luang Prabang."),
   ("C", "ອິດສາ|ແທ້|!", "Je suis jalouse !")],
  [("Que fait Kèo demain ?", "Il joue au foot avec des amis."), ("Et la semaine prochaine ?", "Il va visiter Luang Prabang.")],
  [("ມື້ອື່ນ", "demain"), ("ອາທິດໜ້າ", "la semaine prochaine"), ("ປີໜ້າ", "l'année prochaine"), ("ຈະ", "(futur) aller faire"), ("ຫຼິ້ນ|ບານ", "jouer au foot"),
   ("ໄປທ່ຽວ", "se promener, voyager"), ("ອິດສາ", "jaloux, envieux"), ("ແຜນ", "projet, plan")],
  "le futur avec ຈະ", [("ຂ້ອຍ|ຈະ|ໄປ", "je vais y aller"), ("ມື້ອື່ນ|ຈະ|ຝົນ|ຕົກ", "demain il va pleuvoir"), ("ເຈົ້າ|ຈະ|ເຮັດ|ຫຍັງ|?", "tu vas faire quoi ?")],
  ["Où se place ຈະ ?"], "ຈະ se place juste avant le verbe et marque le futur ou l'intention.",
  "ຈະ avant le verbe.",
  [("Tu vas faire quoi demain ?", "ມື້ອື່ນ|ເຈົ້າ|ຈະ|ເຮັດ|ຫຍັງ|?"), ("Je vais voyager.", "ຂ້ອຍ|ຈະ|ໄປທ່ຽວ|."), ("La semaine prochaine.", "ອາທິດໜ້າ|."), ("Je suis jalouse !", "ອິດສາ|ແທ້|!")],
  ["Écris tes projets pour la semaine prochaine en 5 phrases."], "Parle de tes projets du mois avec un natif."),
L(43, "En ce moment", "Dire ce que tu es en train de faire.", "Noy appelle Clara.",
  [("N", "ເຮັດ|ຫຍັງ|ຢູ່|?", "Tu fais quoi ?"),
   ("C", "ກຳລັງ|ເຮັດກິນ|ຢູ່|.", "Je suis en train de cuisiner."),
   ("N", "ເຮັດ|ຫຍັງ|ກິນ|?", "Tu prépares quoi ?"),
   ("C", "ແກງ|ໜໍ່ໄມ້|.|ມາ|ກິນ|ນຳ|ບໍ|?", "Une soupe de pousses de bambou. Tu viens manger ?"),
   ("N", "ໄປ|ດຽວນີ້|ເລີຍ|!", "J'arrive tout de suite !")],
  [("Que fait Clara ?", "Elle cuisine une soupe de pousses de bambou.")],
  [("ກຳລັງ", "être en train de"), ("…|ຢູ່", "(action en cours)"), ("ເຮັດກິນ", "cuisiner"), ("ແກງ", "soupe"), ("ໜໍ່ໄມ້", "pousse de bambou"), ("ດຽວນີ້", "maintenant, tout de suite")],
  "l'action en cours", [("ກຳລັງ|ກິນ", "je suis en train de manger"), ("ເຮັດ|ຫຍັງ|ຢູ່|?", "tu fais quoi (en ce moment) ?"), ("ກຳລັງ|ອ່ານ|ປຶ້ມ|ຢູ່", "je suis en train de lire")],
  ["Où se placent ກຳລັງ et ຢູ່ ?"], "ກຳລັງ avant le verbe et/ou ຢູ່ en fin de phrase indiquent l'action en cours.",
  "ກຳລັງ et ຢູ່.",
  [("Tu fais quoi ?", "ເຮັດ|ຫຍັງ|ຢູ່|?"), ("Je suis en train de cuisiner.", "ກຳລັງ|ເຮັດກິນ|ຢູ່|."), ("J'arrive tout de suite !", "ໄປ|ດຽວນີ້|ເລີຍ|!")],
  ["Décris ce que font 4 personnes autour de toi en ce moment."], "Fais un appel vidéo et décris ce que tu es en train de faire."),
L(44, "Tu as déjà… ?", "Parler de tes expériences : déjà, jamais.", "Clara et Kèo parlent voyages.",
  [("K", "ເອື້ອຍ|ເຄີຍ|ໄປ|ຫຼວງພະບາງ|ບໍ|?", "Tu es déjà allée à Luang Prabang ?"),
   ("C", "ບໍ່ເຄີຍ|.|ເຈົ້າ|ເດ|?", "Jamais. Et toi ?"),
   ("K", "ເຄີຍ|ໄປ|ສອງ|ເທື່ອ|.", "J'y suis allé deux fois."),
   ("C", "ເຄີຍ|ກິນ|ໄຂ່|ມົດ|ບໍ|?", "Tu as déjà mangé des œufs de fourmi ?"),
   ("K", "ເຄີຍ|.|ແຊບ|ດີ|!", "Oui. C'est bon !")],
  [("Clara connaît-elle Luang Prabang ?", "Non, jamais."), ("Combien de fois Kèo y est-il allé ?", "Deux fois.")],
  [("ເຄີຍ", "avoir déjà (fait)"), ("ບໍ່ເຄີຍ", "ne jamais avoir"), ("ເທື່ອ", "fois"), ("ສອງ|ເທື່ອ", "deux fois"), ("ໄຂ່|ມົດ", "œufs de fourmi")],
  "l'expérience avec ເຄີຍ", [("ເຄີຍ|ໄປ|ບໍ|?", "tu y es déjà allé ?"), ("ບໍ່ເຄີຍ|ກິນ", "je n'en ai jamais mangé"), ("ເຄີຍ|ສາມ|ເທື່ອ", "trois fois déjà")],
  ["Comment répond-on oui et non ?"], "ເຄີຍ + verbe = avoir déjà fait. Réponse : ເຄີຍ (oui) ou ບໍ່ເຄີຍ (jamais).",
  "ເຄີຍ et ບໍ່ເຄີຍ.",
  [("Tu es déjà allé au Laos ?", "ເຄີຍ|ໄປ|ລາວ|ບໍ|?"), ("Jamais.", "ບໍ່ເຄີຍ|."), ("Deux fois.", "ສອງ|ເທື່ອ|.")],
  ["Écris 5 expériences que tu as eues et 3 que tu n'as jamais eues."], "Joue à « Tu as déjà… ? » avec un natif : 5 questions chacun."),
L(45, "Stratégies de survie", "Faire répéter, ralentir, demander un mot, reformuler.", "Clara ne comprend pas M. Somsak.",
  [("S", "…", "(M. Somsak parle très vite)"),
   ("C", "ຂໍໂທດ|,|ບໍ່ເຂົ້າໃຈ|.", "Pardon, je ne comprends pas."),
   ("C", "ເວົ້າ|ຊ້າໆ|ແດ່|.", "Parlez lentement, s'il vous plaît."),
   ("S", "ໄດ້|.|ເຈົ້າ|ກິນ|ເຂົ້າ|ແລ້ວ|ບໍ|?", "D'accord. Tu as mangé ?"),
   ("C", "ໂອ້|,|ເຂົ້າໃຈ|ແລ້ວ|.|ກິນ|ແລ້ວ|.", "Ah, j'ai compris. Oui, j'ai mangé."),
   ("C", "ຄຳ|ນີ້|ແປ|ວ່າ|ແນວໃດ|?", "Ce mot, ça veut dire quoi ?")],
  [("Que fait Clara quand elle ne comprend pas ?", "Elle dit qu'elle ne comprend pas et demande de parler lentement.")],
  [("ບໍ່ເຂົ້າໃຈ", "je ne comprends pas"), ("ເວົ້າ|ຊ້າໆ|ແດ່", "parlez lentement, svp"), ("ເວົ້າ|ອີກເທື່ອໜຶ່ງ", "répétez"), ("ແປ|ວ່າ|ແນວໃດ", "ça veut dire quoi ?"),
   ("ພາສາລາວ|ເອີ້ນ|ວ່າ|ຫຍັງ", "comment dit-on en lao ?"), ("ເຂົ້າໃຈ|ແລ້ວ", "j'ai compris"), ("ຂຽນ|ໃຫ້|ແດ່", "écrivez-le-moi, svp")],
  "les phrases de secours", [("ບໍ່ເຂົ້າໃຈ", "je ne comprends pas"), ("…|ພາສາລາວ|ເອີ້ນ|ວ່າ|ຫຍັງ|?", "… comment on dit en lao ?")],
  [], "Apprends ces phrases par cœur : elles te permettent de rester dans la conversation même quand tu bloques.",
  "les demandes de répétition.",
  [("Je ne comprends pas.", "ບໍ່ເຂົ້າໃຈ|."), ("Parlez lentement, s'il vous plaît.", "ເວົ້າ|ຊ້າໆ|ແດ່|."), ("Répétez, s'il vous plaît.", "ເວົ້າ|ອີກເທື່ອໜຶ່ງ|ແດ່|."), ("Ça veut dire quoi ?", "ແປ|ວ່າ|ແນວໃດ|?")],
  ["Écris les 6 phrases de secours sur un post-it."], "Pendant une conversation avec un natif, utilise au moins 4 phrases de secours."),
L(46, "Inviter et répondre", "Inviter quelqu'un, accepter, refuser poliment.", "Noy invite Clara.",
  [("N", "ວັນເສົາ|ໄປ|ກິນ|ປີ້ງ|ນຳ|ກັນ|ບໍ|?", "Samedi, on va manger un barbecue ensemble ?"),
   ("C", "ຢາກ|ໄປ|ແຕ່|ບໍ່|ຫວ່າງ|.", "J'aimerais bien, mais je ne suis pas libre."),
   ("N", "ວັນອາທິດ|ເດ|?", "Et dimanche ?"),
   ("C", "ວັນອາທິດ|ໄດ້|.|ໄປ|ກັນ|!", "Dimanche, c'est bon. Allons-y !")],
  [("Pourquoi Clara refuse-t-elle samedi ?", "Elle n'est pas libre."), ("Quel jour acceptent-elles ?", "Dimanche.")],
  [("…|ນຳ|ກັນ|ບໍ|?", "on fait… ensemble ?"), ("ໄປ|ກັນ", "allons-y"), ("ບໍ່|ຫວ່າງ", "pas libre"), ("ຢາກ|ໄປ|ແຕ່", "j'aimerais mais…"), ("ເຊີນ", "inviter"), ("ຄັ້ງໜ້າ", "la prochaine fois")],
  "proposer avec ກັນ", [("ໄປ|ກັນ", "allons-y"), ("ກິນ|ນຳ|ກັນ|ບໍ|?", "on mange ensemble ?"), ("ຄັ້ງໜ້າ|ເດີ", "la prochaine fois, hein")],
  ["Comment refuser sans dire « non » directement ?"], "ກັນ = ensemble, l'un l'autre. Pour refuser poliment, on donne une raison (ບໍ່ຫວ່າງ) et on propose une autre fois (ຄັ້ງໜ້າ), sans « non » sec.",
  "les refus adoucis.",
  [("On va manger ensemble ?", "ໄປ|ກິນ|ນຳ|ກັນ|ບໍ|?"), ("J'aimerais, mais je ne suis pas libre.", "ຢາກ|ໄປ|ແຕ່|ບໍ່|ຫວ່າງ|."), ("Allons-y !", "ໄປ|ກັນ|!"), ("La prochaine fois.", "ຄັ້ງໜ້າ|ເດີ|.")],
  ["Écris une invitation et deux réponses (accepter / refuser)."], "Invite vraiment un natif à faire quelque chose avec toi, en lao.",
  cult="Un refus direct est impoli. On adoucit avec une excuse et une promesse vague."),
L(47, "Prendre rendez-vous", "Fixer, déplacer ou annuler un rendez-vous.", "Clara appelle le salon de coiffure.",
  [("C", "ຂ້ອຍ|ຢາກ|ນັດ|ຕັດ|ຜົມ|.", "Je voudrais prendre rendez-vous pour une coupe."),
   ("W", "ມື້|ໃດ|?", "Quel jour ?"),
   ("C", "ວັນພຸດ|ສອງ|ໂມງ|ແລງ|ໄດ້|ບໍ|?", "Mercredi à 14 h, c'est possible ?"),
   ("W", "ໄດ້|.|ຖ້າ|ມາ|ບໍ່|ໄດ້|ກໍ|ໂທ|ບອກ|ເດີ|.", "Oui. Si vous ne pouvez pas venir, appelez-nous."),
   ("C", "ໄດ້|ເຈົ້າ|.|ຂອບໃຈ|.", "D'accord, merci.")],
  [("Pour quoi Clara prend-elle rendez-vous ?", "Une coupe de cheveux."), ("Que faire si elle ne peut pas venir ?", "Appeler pour prévenir.")],
  [("ນັດ", "rendez-vous ; fixer"), ("ຕັດ|ຜົມ", "se faire couper les cheveux"), ("ເລື່ອນ", "reporter"), ("ຍົກເລີກ", "annuler"), ("ຖ້າ|…|ກໍ", "si… alors"), ("ໂທ|ບອກ", "appeler pour prévenir")],
  "la condition ຖ້າ… ກໍ", [("ຖ້າ|ຝົນ|ຕົກ|ກໍ|ບໍ່|ໄປ", "s'il pleut, on n'y va pas"), ("ຖ້າ|ຫວ່າງ|ກໍ|ມາ", "si tu es libre, viens")],
  ["Où se place ກໍ ?"], "ຖ້າ + condition, ກໍ + conséquence. ກໍ se place devant le verbe de la conséquence.",
  "ຖ້າ et ກໍ.",
  [("Je voudrais prendre rendez-vous.", "ຂ້ອຍ|ຢາກ|ນັດ|."), ("Je dois annuler.", "ຂ້ອຍ|ຕ້ອງ|ຍົກເລີກ|."), ("On peut reporter ?", "ເລື່ອນ|ໄດ້|ບໍ|?"), ("S'il pleut, je ne viens pas.", "ຖ້າ|ຝົນ|ຕົກ|ກໍ|ບໍ່|ມາ|.")],
  ["Écris 4 phrases avec ຖ້າ… ກໍ."], "Joue avec un natif une prise de rendez-vous puis un report."),
L(48, "Au téléphone (2)", "Mener un appel complet et rapporter ce qu'on t'a dit.", "Clara rapporte un appel à Noy.",
  [("N", "ແມ່|ໂທ|ມາ|ວ່າ|ແນວໃດ|?", "Maman a appelé, elle a dit quoi ?"),
   ("C", "ລາວ|ບອກ|ວ່າ|ຈະ|ກັບ|ມາ|ຊ້າ|.", "Elle a dit qu'elle rentrerait tard."),
   ("N", "ເປັນ|ຫຍັງ|?", "Pourquoi ?"),
   ("C", "ລາວ|ວ່າ|ລົດ|ຕິດ|ຫຼາຍ|.", "Elle dit qu'il y a beaucoup de bouchons.")],
  [("Que dit Mme Boua ?", "Qu'elle rentrera tard à cause des bouchons.")],
  [("ວ່າ", "que (discours rapporté)"), ("ບອກ|ວ່າ", "dire que"), ("ຖາມ|ວ່າ", "demander si"), ("ລົດ|ຕິດ", "embouteillage"), ("ຊ້າ", "tard, en retard"), ("ຝາກ|ບອກ", "transmettre un message")],
  "le discours rapporté avec ວ່າ", [("ລາວ|ບອກ|ວ່າ|…", "il/elle a dit que…"), ("ຂ້ອຍ|ຄິດ|ວ່າ|…", "je pense que…")],
  ["Que fait ວ່າ dans ces phrases ?"], "ວ່າ introduit ce que quelqu'un dit, pense ou demande, comme « que » en français.",
  "ວ່າ après les verbes de parole.",
  [("Elle a dit qu'elle rentrerait tard.", "ລາວ|ບອກ|ວ່າ|ຈະ|ກັບ|ມາ|ຊ້າ|."), ("Il a demandé si tu viens.", "ລາວ|ຖາມ|ວ່າ|ເຈົ້າ|ມາ|ບໍ|."), ("Il y a des bouchons.", "ລົດ|ຕິດ|.")],
  ["Rapporte en lao 3 choses qu'on t'a dites aujourd'hui."], "Après un appel avec un natif, raconte-le à quelqu'un d'autre en lao."),
L(49, "Au marché", "Marchander, comparer les prix et les produits.", "Clara au marché du matin.",
  [("C", "ໝາກມ່ວງ|ໃສ|ແຊບ|ກວ່າ|?", "Quelles mangues sont les meilleures ?"),
   ("V", "ອັນ|ນີ້|ຫວານ|ທີ່ສຸດ|.", "Celles-ci sont les plus sucrées."),
   ("C", "ແຕ່|ແພງ|ທີ່ສຸດ|ຄືກັນ|!", "Mais aussi les plus chères !"),
   ("V", "ເອົາ|ສອງ|ກິໂລ|ຫຼຸດ|ໃຫ້|.", "Si tu en prends deux kilos, je baisse."),
   ("C", "ຕົກລົງ|!", "Marché conclu !")],
  [("Quelles mangues sont les plus sucrées ?", "Celles que montre la vendeuse."), ("À quelle condition elle baisse le prix ?", "Si Clara en prend deux kilos.")],
  [("ກວ່າ", "plus… (que)"), ("ທີ່ສຸດ", "le plus"), ("ຕົກລົງ", "d'accord, marché conclu"), ("ຫຼຸດ|ໃຫ້", "faire une réduction"), ("ສົດ", "frais"), ("ຜັກ", "légume")],
  "comparatif et superlatif", [("ຫວານ|ກວ່າ", "plus sucré"), ("ຫວານ|ທີ່ສຸດ", "le plus sucré"), ("ແພງ|ກວ່າ|ອັນ|ນັ້ນ", "plus cher que celui-là")],
  ["Quelle différence entre ກວ່າ et ທີ່ສຸດ ?"], "Adjectif + ກວ່າ = plus… ; adjectif + ທີ່ສຸດ = le plus…",
  "ກວ່າ et ທີ່ສຸດ.",
  [("Lesquelles sont les meilleures ?", "ອັນ|ໃດ|ແຊບ|ກວ່າ|?"), ("Les plus sucrées.", "ຫວານ|ທີ່ສຸດ|."), ("Marché conclu !", "ຕົກລົງ|!")],
  ["Compare 3 fruits en lao (prix, goût, taille)."], "Fais tes courses au marché asiatique en lao ou joue la scène avec un natif."),
L(50, "Chez le médecin", "Expliquer tes symptômes et leur durée, comprendre une consigne.", "Clara consulte un médecin.",
  [("M", "ເປັນ|ຫຍັງ|?", "Qu'est-ce qui ne va pas ?"),
   ("C", "ເຈັບ|ຄໍ|ແລະ|ໄອ|.", "J'ai mal à la gorge et je tousse."),
   ("M", "ເປັນ|ມາ|ດົນ|ປານໃດ|ແລ້ວ|?", "Depuis combien de temps ?"),
   ("C", "ສາມ|ມື້|ແລ້ວ|.", "Trois jours."),
   ("M", "ກິນ|ຢາ|ນີ້|ມື້|ລະ|ສາມ|ເທື່ອ|ຫຼັງ|ອາຫານ|.", "Prenez ce médicament trois fois par jour après les repas.")],
  [("Quels sont les symptômes ?", "Mal à la gorge et toux."), ("Depuis quand ?", "Trois jours."), ("Quelle consigne ?", "Le médicament 3 fois par jour après les repas.")],
  [("ເຈັບ|ຄໍ", "mal à la gorge"), ("ໄອ", "tousser"), ("ດົນ|ປານໃດ", "combien de temps ?"), ("…|ມາ|…|ແລ້ວ", "depuis…"), ("ມື້|ລະ|ສາມ|ເທື່ອ", "trois fois par jour"),
   ("ຫຼັງ|ອາຫານ", "après le repas"), ("ກ່ອນ|ອາຫານ", "avant le repas"), ("ໃບສັ່ງຢາ", "ordonnance")],
  "la durée", [("ເປັນ|ມາ|ສາມ|ມື້|ແລ້ວ", "c'est depuis trois jours"), ("ຮຽນ|ມາ|ສອງ|ປີ|ແລ້ວ", "j'étudie depuis deux ans")],
  ["Comment exprime-t-on « depuis » ?"], "Verbe + ມາ + durée + ແລ້ວ = faire quelque chose depuis… ລະ = par (ມື້ລະ = par jour).",
  "les durées et les fréquences.",
  [("J'ai mal à la gorge.", "ຂ້ອຍ|ເຈັບ|ຄໍ|."), ("Depuis trois jours.", "ສາມ|ມື້|ແລ້ວ|."), ("Trois fois par jour.", "ມື້|ລະ|ສາມ|ເທື່ອ|.")],
  ["Écris ce que tu dirais au médecin pour un rhume."], "Joue une consultation complète avec un natif.",
  cult=None),
L(51, "Le logement", "Décrire un logement et poser des questions pour louer.", "Clara visite un appartement.",
  [("C", "ຫ້ອງ|ນີ້|ມີ|ແອ|ບໍ|?", "Cette chambre a la clim ?"),
   ("W", "ມີ|.|ມີ|ຫ້ອງນ້ຳ|ນຳ|.", "Oui. Et une salle de bain."),
   ("C", "ຄ່າ|ເຊົ່າ|ເດືອນ|ລະ|ເທົ່າໃດ|?", "Le loyer est de combien par mois ?"),
   ("W", "ສອງ|ລ້ານ|ກີບ|.", "Deux millions de kips."),
   ("C", "ລວມ|ຄ່າ|ໄຟ|ບໍ|?", "Électricité comprise ?"),
   ("W", "ບໍ່|ລວມ|.", "Non.")],
  [("Que contient la chambre ?", "La clim et une salle de bain."), ("Quel est le loyer ?", "2 millions de kips, électricité non comprise.")],
  [("ເຊົ່າ", "louer"), ("ຄ່າ|ເຊົ່າ", "loyer"), ("ແອ", "climatisation"), ("ຫ້ອງນ້ຳ", "salle de bain"), ("ຫ້ອງນອນ", "chambre"), ("ລວມ", "compris, inclure"),
   ("ຄ່າ|ໄຟ", "électricité (facture)"), ("ຄ່າ|ນ້ຳ", "eau (facture)")],
  "ມີ pour décrire", [("ມີ|ສອງ|ຫ້ອງນອນ", "il y a deux chambres"), ("ບໍ່|ມີ|ແອ", "il n'y a pas de clim")],
  ["Comment décris-tu ce qu'il y a dans un logement ?"], "ມີ + élément (+ nombre + classificateur) décrit ce que contient un lieu.",
  "les nombres et ລວມ.",
  [("Il y a la clim ?", "ມີ|ແອ|ບໍ|?"), ("Le loyer est de combien ?", "ຄ່າ|ເຊົ່າ|ເທົ່າໃດ|?"), ("Électricité comprise ?", "ລວມ|ຄ່າ|ໄຟ|ບໍ|?")],
  ["Décris ton logement idéal en 5 phrases."], "Joue avec un natif la visite d'un logement."),
L(52, "Travail et études", "Parler de ton métier, de tes études et de leur but.", "Clara parle de son travail.",
  [("S", "ເຈົ້າ|ເຮັດວຽກ|ຫຍັງ|?", "Tu fais quoi comme travail ?"),
   ("C", "ຂ້ອຍ|ເປັນ|ຄູ|ສອນ|ພາສາຝຣັ່ງ|.", "Je suis professeure de français."),
   ("S", "ເປັນ|ຫຍັງ|ມາ|ຢູ່|ລາວ|?", "Pourquoi es-tu venue au Laos ?"),
   ("C", "ມາ|ເພື່ອ|ສອນ|ແລະ|ຮຽນ|ພາສາລາວ|.", "Pour enseigner et apprendre le lao.")],
  [("Quel est le métier de Clara ?", "Professeure de français."), ("Pourquoi est-elle au Laos ?", "Pour enseigner et apprendre le lao.")],
  [("ເຮັດວຽກ", "travailler"), ("ເຮັດວຽກ|ຫຍັງ", "quel travail ?"), ("ເປັນ", "être (métier)"), ("ຄູ", "professeur"), ("ທ່ານໝໍ", "médecin"), ("ພະນັກງານ", "employé"),
   ("ນັກສຶກສາ", "étudiant"), ("ເພື່ອ", "pour, afin de"), ("ບໍລິສັດ", "entreprise")],
  "le but avec ເພື່ອ", [("ມາ|ເພື່ອ|ຮຽນ", "venir pour étudier"), ("ຮຽນ|ເພື່ອ|ລົມ|ກັບ|ຄອບຄົວ", "apprendre pour parler avec la famille")],
  ["Que montre ເພື່ອ ?"], "ເພື່ອ + verbe = pour, afin de. ເປັນ + métier = être (tel métier).",
  "ເປັນ devant les métiers.",
  [("Tu fais quoi comme travail ?", "ເຈົ້າ|ເຮັດວຽກ|ຫຍັງ|?"), ("Je suis professeure.", "ຂ້ອຍ|ເປັນ|ຄູ|."), ("J'apprends le lao pour parler avec ma famille.", "ຂ້ອຍ|ຮຽນ|ພາສາລາວ|ເພື່ອ|ລົມ|ກັບ|ຄອບຄົວ|.")],
  ["Écris pourquoi tu apprends le lao, en 3 phrases avec ເພື່ອ."], "Explique ton métier et tes raisons d'apprendre le lao à un natif."),
L(53, "Pourquoi ? Parce que…", "Justifier un choix avec une cause.", "Noy demande pourquoi Clara aime Vientiane.",
  [("N", "ເປັນຫຍັງ|ເຈົ້າ|ມັກ|ວຽງຈັນ|?", "Pourquoi tu aimes Vientiane ?"),
   ("C", "ຍ້ອນວ່າ|ຄົນ|ໃຈດີ|ແລະ|ອາຫານ|ແຊບ|.", "Parce que les gens sont gentils et la nourriture est bonne."),
   ("N", "ບໍ່|ມັກ|ຫຍັງ|ບໍ|?", "Il y a quelque chose que tu n'aimes pas ?"),
   ("C", "ບໍ່|ມັກ|ລະດູຮ້ອນ|ເພາະວ່າ|ຮ້ອນ|ໂພດ|.", "Je n'aime pas la saison chaude, parce qu'il fait trop chaud.")],
  [("Pourquoi Clara aime-t-elle Vientiane ?", "Les gens sont gentils et la nourriture bonne."), ("Qu'est-ce qu'elle n'aime pas ?", "La saison chaude.")],
  [("ເປັນຫຍັງ", "pourquoi ?"), ("ຍ້ອນວ່າ", "parce que"), ("ເພາະວ່າ", "parce que"), ("ສະນັ້ນ", "donc"), ("ລະດູຮ້ອນ", "saison chaude")],
  "la cause", [("ບໍ່|ໄປ|ຍ້ອນວ່າ|ຝົນ|ຕົກ", "je n'y vais pas parce qu'il pleut"), ("ຝົນ|ຕົກ|ສະນັ້ນ|ບໍ່|ໄປ", "il pleut donc je n'y vais pas")],
  ["Quelle différence entre ຍ້ອນວ່າ et ສະນັ້ນ ?"], "ຍ້ອນວ່າ / ເພາະວ່າ introduisent la cause ; ສະນັ້ນ introduit la conséquence.",
  "les connecteurs de cause.",
  [("Pourquoi ?", "ເປັນຫຍັງ|?"), ("Parce qu'il fait trop chaud.", "ຍ້ອນວ່າ|ຮ້ອນ|ໂພດ|."), ("Donc je reste à la maison.", "ສະນັ້ນ|ຢູ່|ເຮືອນ|.")],
  ["Écris 4 phrases avec ຍ້ອນວ່າ et 2 avec ສະນັ້ນ."], "Explique à un natif 3 choix de ta vie avec « parce que »."),
L(54, "Mais, alors, ensuite", "Raconter une petite histoire en 5 phrases liées.", "Kèo raconte sa journée ratée.",
  [("K", "ມື້ວານ|ຂ້ອຍ|ຕື່ນ|ຊ້າ|.", "Hier, je me suis réveillé en retard."),
   ("K", "ແລ້ວ|ລົດຈັກ|ກໍ|ເປ່|.", "Puis ma moto est tombée en panne."),
   ("K", "ແຕ່|ໝູ່|ມາ|ຊ່ວຍ|.", "Mais un ami est venu m'aider."),
   ("K", "ສຸດທ້າຍ|ກໍ|ຮອດ|ໂຮງຮຽນ|ທັນ|.", "Finalement, je suis arrivé à l'heure à l'école."),
   ("C", "ໂຊກດີ|ເນາະ|!", "Quelle chance !")],
  [("Quels problèmes a eus Kèo ?", "Réveil en retard et moto en panne."), ("Comment ça s'est fini ?", "Il est arrivé à l'heure grâce à un ami.")],
  [("ແລ້ວ", "puis"), ("ແຕ່", "mais"), ("ກໍ", "alors (lien)"), ("ສຸດທ້າຍ", "finalement"), ("ທຳອິດ", "d'abord"), ("ເປ່", "tomber en panne", "[À VÉRIFIER]"),
   ("ທັນ", "à temps"), ("ໂຊກດີ", "chance ; bonne chance")],
  "enchaîner un récit", [("ທຳອິດ|…|ແລ້ວ|…|ສຸດທ້າຍ|…", "d'abord… puis… finalement…")],
  ["Quels mots structurent l'histoire ?"], "Pour raconter : ທຳອິດ (d'abord), ແລ້ວ (puis), ແຕ່ (mais), ສຸດທ້າຍ (finalement). ກໍ relie souvent la conséquence.",
  "les mots qui structurent le récit.",
  [("D'abord, je me suis réveillé en retard.", "ທຳອິດ|ຂ້ອຍ|ຕື່ນ|ຊ້າ|."), ("Mais un ami m'a aidé.", "ແຕ່|ໝູ່|ມາ|ຊ່ວຍ|."), ("Quelle chance !", "ໂຊກດີ|ເນາະ|!")],
  ["Raconte une petite mésaventure en 5 phrases liées."], "Raconte une anecdote à un natif en utilisant ທຳອິດ, ແລ້ວ, ແຕ່, ສຸດທ້າຍ."),
L(55, "Les fréquences", "Dire ce que tu fais souvent, parfois, jamais.", "Noy et Clara parlent de leurs habitudes.",
  [("N", "ເຈົ້າ|ເຮັດກິນ|ເອງ|ເລື້ອຍໆ|ບໍ|?", "Tu cuisines souvent toi-même ?"),
   ("C", "ບາງເທື່ອ|.|ສ່ວນຫຼາຍ|ກິນ|ຢູ່|ນອກ|.", "Parfois. La plupart du temps, je mange dehors."),
   ("N", "ຂ້ອຍ|ເຮັດກິນ|ທຸກມື້|.", "Moi, je cuisine tous les jours."),
   ("C", "ຂ້ອຍ|ບໍ່ເຄີຍ|ເຮັດ|ລາບ|.", "Je n'ai jamais fait de larb.")],
  [("Clara cuisine-t-elle souvent ?", "Parfois ; elle mange surtout dehors.")],
  [("ສະເໝີ", "toujours"), ("ເລື້ອຍໆ", "souvent"), ("ບາງເທື່ອ", "parfois"), ("ບໍ່ຄ່ອຍ", "rarement", "[À VÉRIFIER]"), ("ບໍ່ເຄີຍ", "jamais"), ("ທຸກມື້", "tous les jours"),
   ("ສ່ວນຫຼາຍ", "la plupart du temps"), ("ເອງ", "soi-même")],
  "les adverbes de fréquence", [("ກິນ|ຢູ່|ນອກ|ເລື້ອຍໆ", "manger souvent dehors"), ("ບາງເທື່ອ|ເຮັດກິນ", "parfois je cuisine")],
  ["Où se placent ces adverbes ?"], "ເລື້ອຍໆ et ທຸກມື້ se placent souvent en fin de phrase ; ບາງເທື່ອ et ສ່ວນຫຼາຍ plutôt en début.",
  "les adverbes de fréquence.",
  [("Je cuisine parfois.", "ບາງເທື່ອ|ຂ້ອຍ|ເຮັດກິນ|."), ("Je mange souvent dehors.", "ຂ້ອຍ|ກິນ|ຢູ່|ນອກ|ເລື້ອຍໆ|."), ("Tous les jours.", "ທຸກມື້|.")],
  ["Écris 6 habitudes avec des fréquences différentes."], "Compare tes habitudes avec celles d'un natif."),
L(56, "Savoir, pouvoir, devoir", "Dire ce que tu sais faire, peux faire ou dois faire.", "Clara apprend à conduire une moto.",
  [("K", "ເອື້ອຍ|ຂີ່|ລົດຈັກ|ເປັນ|ບໍ|?", "Tu sais conduire une moto ?"),
   ("C", "ຍັງ|ບໍ່|ເປັນ|.", "Pas encore."),
   ("K", "ຕ້ອງ|ຮຽນ|ເດີ|.|ຢູ່|ລາວ|ຕ້ອງ|ຂີ່|ເປັນ|.", "Il faut apprendre. Au Laos, il faut savoir en conduire."),
   ("C", "ມື້ອື່ນ|ສອນ|ຂ້ອຍ|ໄດ້|ບໍ|?", "Tu peux m'apprendre demain ?"),
   ("K", "ໄດ້|ສະບາຍ|!", "Bien sûr, sans problème !")],
  [("Clara sait-elle conduire une moto ?", "Pas encore."), ("Que propose-t-elle ?", "Que Kèo lui apprenne demain.")],
  [("ເປັນ", "savoir (habileté apprise)"), ("ໄດ້", "pouvoir"), ("ຕ້ອງ", "devoir, falloir"), ("ສອນ", "enseigner"), ("ຂີ່|ລົດຈັກ", "conduire une moto"), ("ໄດ້|ສະບາຍ", "sans problème")],
  "ເປັນ, ໄດ້, ຕ້ອງ", [("ລອຍນ້ຳ|ເປັນ", "savoir nager"), ("ມາ|ໄດ້", "pouvoir venir"), ("ຕ້ອງ|ໄປ", "devoir y aller")],
  ["Où se placent ເປັນ et ໄດ້ ? Et ຕ້ອງ ?"], "ເປັນ (savoir faire) et ໄດ້ (pouvoir) se placent APRÈS le verbe ; ຕ້ອງ (devoir) AVANT.",
  "la place de ເປັນ, ໄດ້, ຕ້ອງ.",
  [("Tu sais conduire une moto ?", "ຂີ່|ລົດຈັກ|ເປັນ|ບໍ|?"), ("Je dois y aller.", "ຂ້ອຍ|ຕ້ອງ|ໄປ|."), ("Tu peux venir ?", "ມາ|ໄດ້|ບໍ|?")],
  ["Écris 3 choses que tu sais faire, 3 que tu peux faire cette semaine, 3 que tu dois faire."], "Parle de tes compétences avec un natif."),
L(57, "Voyager au Laos", "Organiser un trajet : billet, horaires, hôtel.", "Clara prépare un voyage à Luang Prabang.",
  [("C", "ລົດເມ|ໄປ|ຫຼວງພະບາງ|ອອກ|ຈັກ|ໂມງ|?", "Le bus pour Luang Prabang part à quelle heure ?"),
   ("W", "ແປດ|ໂມງ|ເຊົ້າ|.", "À 8 h du matin."),
   ("C", "ໃຊ້|ເວລາ|ດົນ|ປານໃດ|?", "Ça prend combien de temps ?"),
   ("W", "ປະມານ|ສີ່|ຊົ່ວໂມງ|ດ້ວຍ|ທາງ|ໃໝ່|.", "Environ 4 heures par la nouvelle route."),
   ("C", "ຂໍ|ປີ້|ໜຶ່ງ|ໃບ|.", "Un billet, s'il vous plaît.")],
  [("À quelle heure part le bus ?", "8 h."), ("Combien de temps dure le trajet ?", "Environ 4 heures.")],
  [("ປີ້", "billet"), ("ອອກ", "partir"), ("ຮອດ", "arriver"), ("ໃຊ້|ເວລາ", "prendre (du temps)"), ("ປະມານ", "environ"), ("ຊົ່ວໂມງ", "heure (durée)"),
   ("ໂຮງແຮມ", "hôtel"), ("ຈອງ", "réserver")],
  "durée et horaires", [("ອອກ|ແປດ|ໂມງ", "part à 8 h"), ("ໃຊ້|ເວລາ|ສີ່|ຊົ່ວໂມງ", "prend 4 heures")],
  ["Quelle différence entre ໂມງ et ຊົ່ວໂມງ ?"], "ໂມງ = l'heure qu'il est ; ຊົ່ວໂມງ = une durée d'une heure.",
  "ໂມງ et ຊົ່ວໂມງ.",
  [("Le bus part à quelle heure ?", "ລົດເມ|ອອກ|ຈັກ|ໂມງ|?"), ("Ça prend combien de temps ?", "ໃຊ້|ເວລາ|ດົນ|ປານໃດ|?"), ("Je voudrais réserver une chambre.", "ຂ້ອຍ|ຢາກ|ຈອງ|ຫ້ອງ|.")],
  ["Écris l'itinéraire d'un voyage de 3 jours au Laos."], "Prépare avec un natif un vrai ou faux voyage au Laos en lao."),
L(58, "Les fêtes", "Souhaiter une bonne fête et participer à un baci.", "C'est le Nouvel An lao.",
  [("B", "ສະບາຍດີ|ປີໃໝ່|!", "Bonne année !"),
   ("C", "ສະບາຍດີ|ປີໃໝ່|ເຈົ້າ|!|ຂໍ|ໃຫ້|ມີ|ສຸຂະພາບ|ແຂງແຮງ|.", "Bonne année ! Je vous souhaite une bonne santé."),
   ("B", "ມື້ນີ້|ມີ|ບາສີ|ຢູ່|ເຮືອນ|.|ມາ|ຜູກແຂນ|ນຳ|ກັນ|.", "Aujourd'hui, il y a un baci à la maison. Viens, on va nouer les fils."),
   ("C", "ຂອບໃຈ|ທີ່|ເຊີນ|ຂ້ອຍ|.", "Merci de m'inviter.")],
  [("Quelle fête est-ce ?", "Le Nouvel An lao (Pi Mai)."), ("Que se passe-t-il à la maison ?", "Un baci, cérémonie des fils de coton.")],
  [("ບຸນປີໃໝ່", "Nouvel An lao (avril)"), ("ສະບາຍດີ|ປີໃໝ່", "bonne année"), ("ບາສີ", "baci (cérémonie)"), ("ຜູກແຂນ", "nouer les fils au poignet"),
   ("ຂໍ|ໃຫ້", "je souhaite que"), ("ສຸຂະພາບ|ແຂງແຮງ", "bonne santé"), ("ໂຊກດີ", "bonne chance"), ("ອວຍພອນ", "souhaiter, bénir")],
  "les vœux avec ຂໍໃຫ້", [("ຂໍ|ໃຫ້|ໂຊກດີ", "bonne chance"), ("ຂໍ|ໃຫ້|ມີ|ຄວາມສຸກ", "sois heureux")],
  ["Comment commencent les vœux ?"], "ຂໍໃຫ້ + souhait = « je souhaite que… ». On l'utilise aux fêtes et pendant le baci en nouant les fils.",
  "les formules de vœux.",
  [("Bonne année !", "ສະບາຍດີ|ປີໃໝ່|!"), ("Bonne chance !", "ຂໍ|ໃຫ້|ໂຊກດີ|!"), ("Merci de m'inviter.", "ຂອບໃຈ|ທີ່|ເຊີນ|ຂ້ອຍ|.")],
  ["Écris 4 vœux pour quelqu'un que tu aimes."], "Souhaite une bonne fête en lao à un natif, oralement ou par message.",
  cult="Pendant le baci (ບາສີ), les invités nouent des fils de coton blanc au poignet de la personne fêtée en prononçant des vœux. On garde les fils au moins trois jours."),
L(59, "Cuisiner", "Expliquer une recette simple étape par étape.", "Mme Boua apprend le larb à Clara.",
  [("B", "ທຳອິດ|ສັບ|ຊີ້ນ|ໃຫ້|ລະອຽດ|.", "D'abord, hache la viande finement."),
   ("B", "ແລ້ວ|ຂົ້ວ|ເຂົ້າ|ໃຫ້|ຫອມ|.", "Puis fais griller le riz pour qu'il sente bon."),
   ("B", "ໃສ່|ນ້ຳປາ|,|ໝາກນາວ|,|ແລະ|ໝາກເຜັດ|.", "Ajoute sauce de poisson, citron vert et piment."),
   ("C", "ໃສ່|ຜັກ|ຫຍັງ|ແດ່|?", "On met quelles herbes ?"),
   ("B", "ຜັກ|ບົ່ວ|ແລະ|ຜັກ|ຫອມ|.", "De l'oignon vert et de la coriandre.")],
  [("Quelle est la première étape ?", "Hacher la viande finement."), ("Quels ingrédients ajoute-t-on ?", "Sauce de poisson, citron vert, piment, herbes.")],
  [("ສັບ", "hacher"), ("ຂົ້ວ", "griller à sec, faire sauter"), ("ໃສ່", "mettre, ajouter"), ("ນ້ຳປາ", "sauce de poisson"), ("ໝາກນາວ", "citron vert"),
   ("ໝາກເຜັດ", "piment"), ("ຫອມ", "parfumé"), ("ລະອຽດ", "fin, minutieux"), ("ຜັກ|ບົ່ວ", "oignon vert")],
  "l'impératif et l'ordre des étapes", [("ໃສ່|ນ້ຳປາ", "mets la sauce de poisson"), ("ສັບ|ໃຫ້|ລະອຽດ", "hache finement")],
  ["Comment donne-t-on un ordre ?"], "L'impératif = le verbe seul. Verbe + ໃຫ້ + adjectif = faire de façon à ce que (ສັບໃຫ້ລະອຽດ = hacher finement).",
  "les verbes de cuisine.",
  [("D'abord, hache la viande.", "ທຳອິດ|ສັບ|ຊີ້ນ|."), ("Ajoute du citron vert.", "ໃສ່|ໝາກນາວ|."), ("C'est parfumé !", "ຫອມ|ແທ້|!")],
  ["Écris la recette de ton plat préféré en 6 étapes."], "Cuisine un plat lao avec un natif en suivant ses consignes en lao."),
L(60, "Les sentiments", "Dire comment tu te sens et pourquoi.", "Clara reçoit des nouvelles de France.",
  [("N", "ເປັນ|ຫຍັງ|?|ເບິ່ງ|ຄື|ເສຍໃຈ|.", "Qu'est-ce qu'il y a ? Tu as l'air triste."),
   ("C", "ຂ້ອຍ|ຄິດຮອດ|ຄອບຄົວ|.", "Ma famille me manque."),
   ("N", "ເຂົ້າໃຈ|.|ແຕ່|ພວກເຮົາ|ກໍ|ແມ່ນ|ຄອບຄົວ|ຂອງ|ເຈົ້າ|.", "Je comprends. Mais nous aussi, on est ta famille."),
   ("C", "ດີໃຈ|ຫຼາຍ|ທີ່|ໄດ້|ຍິນ|ແນວ|ນັ້ນ|.", "Ça me fait très plaisir d'entendre ça.")],
  [("Pourquoi Clara est-elle triste ?", "Sa famille lui manque."), ("Que lui dit Noy ?", "Qu'ils sont aussi sa famille.")],
  [("ດີໃຈ", "content, heureux"), ("ເສຍໃຈ", "triste, désolé"), ("ຄິດຮອດ", "manquer (quelqu'un)"), ("ໃຈຮ້າຍ", "fâché"), ("ເປັນຫ່ວງ", "s'inquiéter"), ("ຢ້ານ", "avoir peur"),
   ("ເບື່ອ", "s'ennuyer, en avoir marre"), ("ຕື່ນເຕັ້ນ", "excité", "[À VÉRIFIER]")],
  "les verbes avec ໃຈ (le cœur)", [("ດີ|ໃຈ", "bon + cœur = content"), ("ເສຍ|ໃຈ", "perdre + cœur = triste"), ("ໃຈ|ຮ້າຍ", "cœur + méchant = fâché")],
  ["Que remarques-tu dans ces mots ?"], "Beaucoup d'émotions se forment avec ໃຈ (cœur) : ດີໃຈ, ເສຍໃຈ, ໃຈຮ້າຍ, ໃຈດີ (gentil)…",
  "les mots en ໃຈ.",
  [("Ma famille me manque.", "ຂ້ອຍ|ຄິດຮອດ|ຄອບຄົວ|."), ("Je suis très contente.", "ຂ້ອຍ|ດີໃຈ|ຫຼາຍ|."), ("Ne t'inquiète pas.", "ບໍ່|ຕ້ອງ|ເປັນຫ່ວງ|.")],
  ["Décris 5 situations et l'émotion qu'elles te font ressentir."], "Parle de tes émotions de la semaine avec un natif."),
L(61, "Familier ou poli ?", "Adapter ton message à un ami ou à un aîné.", "Kèo parle à ses amis, puis à son grand-père.",
  [("K", "ເຮົາ|ໄປ|ກິນ|ເບຍ|ບໍ|?", "(aux amis) On va boire une bière ?"),
   ("K", "ພໍ່ຕູ້|,|ຫຼານ|ຂໍ|ອະນຸຍາດ|ອອກ|ໄປ|ນອກ|ເດີ|.", "(au grand-père) Grand-père, je te demande la permission de sortir."),
   ("X", "ໄປ|ໄດ້|,|ຢ່າ|ກັບ|ມາ|ຊ້າ|.", "Tu peux y aller, ne rentre pas tard."),
   ("K", "ເຈົ້າ|,|ຂອບໃຈ|.", "Oui, merci.")],
  [("Comment Kèo parle-t-il à ses amis ?", "Avec ເຮົາ, simplement."), ("Et à son grand-père ?", "Il se désigne comme ຫຼານ et demande poliment la permission.")],
  [("ເຮົາ", "je/nous (familier)"), ("ຫຼານ", "moi (le petit-enfant, poli)"), ("ຂໍ|ອະນຸຍາດ", "demander la permission"), ("ເຈົ້າ", "oui (poli)"), ("ເອີ", "ouais (familier)"),
   ("ກູ", "je (très familier, vulgaire)", "à comprendre, pas à utiliser"), ("ມຶງ", "tu (très familier, vulgaire)", "à comprendre, pas à utiliser")],
  "les registres", [("ເຈົ້າ", "oui poli"), ("ເອີ", "ouais"), ("ຫຼານ|ຂໍ|…", "moi (petit-enfant) je demande…")],
  ["Comment Kèo se désigne-t-il devant son grand-père ?"], "En lao, on se désigne souvent par sa place dans la relation (ຫຼານ, ລູກ, ນ້ອງ). Plus la personne est âgée ou respectée, plus on utilise ເຈົ້າ, ຂໍ et les formules longues.",
  "le changement de ton de voix et de mots.",
  [("Oui (poli).", "ເຈົ້າ|."), ("Je te demande la permission.", "ຂໍ|ອະນຸຍາດ|."), ("On y va ? (entre amis)", "ໄປ|ບໍ|?")],
  ["Écris la même demande à un ami puis à un grand-parent."], "Demande à un natif de jouer deux scènes : avec un ami et avec un aîné."),
L(62, "Les particules de fin de phrase", "Adoucir, insister ou te plaindre avec les particules.", "Une journée chargée chez Noy.",
  [("N", "ມາ|ຊ່ວຍ|ແດ່|ເດີ|.", "Viens m'aider, s'il te plaît."),
   ("K", "ຖ້າ|ແປັບ|ໜຶ່ງ|ເດີ້|.", "Attends une minute."),
   ("N", "ໄວໆ|ແດ່|ສາ|!", "Dépêche-toi donc !"),
   ("K", "ມາ|ແລ້ວ|ເດ້|!", "J'arrive, voilà !"),
   ("C", "ພວກເຈົ້າ|ມ່ວນ|ເນາະ|.", "Vous êtes drôles, vous.")],
  [("Que demande Noy ?", "De l'aide, rapidement.")],
  [("ເດີ", "(adoucit, « hein »)"), ("ແດ່", "(s'il te plaît)"), ("ເນາະ", "(n'est-ce pas, connivence)"), ("ເດ້", "(insistance)"), ("ສາ", "(impatience)", "[À VÉRIFIER]"), ("ແປັບ|ໜຶ່ງ", "un instant")],
  "les particules", [("ໄປ|ເດີ", "j'y vais, hein"), ("ແຊບ|ເນາະ", "c'est bon, hein ?"), ("ໄວໆ|ແດ່", "vite, s'il te plaît")],
  ["Que change la particule au sens de la phrase ?"], "Les particules de fin de phrase ne changent pas le sens mais le ton : douceur (ເດີ, ແດ່), connivence (ເນາະ), insistance (ເດ້), impatience (ສາ). [À VÉRIFIER : usages exacts avec un natif]",
  "les particules en fin de phrase et l'intonation.",
  [("Viens m'aider, s'il te plaît.", "ມາ|ຊ່ວຍ|ແດ່|ເດີ|."), ("C'est bon, hein ?", "ແຊບ|ເນາະ|."), ("Un instant.", "ແປັບ|ໜຶ່ງ|.")],
  ["Écris 5 phrases et ajoute la particule qui convient."], "Observe un natif parler 10 minutes et note toutes les particules entendues."),
L(63, "Écrire un message", "Écrire un message poli complet (ouverture, contenu, clôture).", "Clara écrit à son professeur.",
  [("C", "ສະບາຍດີ|ອາຈານ|.", "Bonjour professeur."),
   ("C", "ຂ້ອຍ|ຂໍ|ອະນຸຍາດ|ພັກ|ມື້ອື່ນ|ຍ້ອນວ່າ|ບໍ່ສະບາຍ|.", "Je vous demande la permission de m'absenter demain car je suis malade."),
   ("C", "ຂໍ|ອະໄພ|ນຳ|.", "Je vous prie de m'excuser."),
   ("C", "ດ້ວຍ|ຄວາມ|ນັບຖື|,|ຄລາຣາ|.", "Respectueusement, Clara.")],
  [("Pourquoi Clara écrit-elle ?", "Pour s'absenter demain, car elle est malade.")],
  [("ອາຈານ", "professeur (respectueux)"), ("ຂໍ|ອະນຸຍາດ", "demander la permission"), ("ຂໍ|ອະໄພ", "s'excuser (soutenu)"), ("ດ້ວຍ|ຄວາມ|ນັບຖື", "respectueusement"), ("ພັກ", "s'absenter, se reposer")],
  "la structure d'un message poli", [("ສະບາຍດີ|ອາຈານ", "ouverture"), ("ຂໍ|ອະໄພ", "excuse"), ("ດ້ວຍ|ຄວາມ|ນັບຖື", "clôture")],
  [], "Ouverture (ສະບາຍດີ + titre), demande avec ຂໍ, justification avec ຍ້ອນວ່າ, excuse (ຂໍອະໄພ), clôture (ດ້ວຍຄວາມນັບຖື).",
  "les formules écrites.",
  [("Bonjour professeur.", "ສະບາຍດີ|ອາຈານ|."), ("Je vous prie de m'excuser.", "ຂໍ|ອະໄພ|."), ("Respectueusement.", "ດ້ວຍ|ຄວາມ|ນັບຖື|.")],
  ["Écris un message poli pour annuler un rendez-vous."], "Envoie un message poli en lao à un natif et demande-lui son avis."),
L(64, "Lire du vrai", "Lire une affiche, une annonce ou un menu réel.", "Clara lit les panneaux dans la rue.",
  [("C", "ປ້າຍ|ນີ້|ຂຽນ|ວ່າ|ແນວໃດ|?", "Ce panneau, qu'est-ce qu'il dit ?"),
   ("N", "ຫ້າມ|ຈອດ|ລົດ|.", "Interdiction de stationner."),
   ("C", "ແລ້ວ|ອັນ|ນັ້ນ|ເດ|?", "Et celui-là ?"),
   ("N", "ເປີດ|ທຸກມື້|,|ແປດ|ໂມງ|ເຊົ້າ|ຫາ|ຫ້າ|ໂມງ|ແລງ|.", "Ouvert tous les jours de 8 h à 17 h.")],
  [("Que dit le premier panneau ?", "Interdiction de stationner."), ("Quels sont les horaires ?", "Tous les jours de 8 h à 17 h.")],
  [("ປ້າຍ", "panneau"), ("ຫ້າມ", "interdit"), ("ເປີດ", "ouvert, ouvrir"), ("ປິດ", "fermé, fermer"), ("ທາງເຂົ້າ", "entrée"), ("ທາງອອກ", "sortie"), ("ຫ້ອງນ້ຳ", "toilettes"), ("ລາຄາ", "prix")],
  "lire vite", [("ຫ້າມ|ສູບຢາ", "défense de fumer"), ("ທາງອອກ", "sortie")],
  [], "Pour lire vite, repère d'abord les mots connus et les chiffres, puis devine le reste par le contexte.",
  "les mots des panneaux.",
  [("Qu'est-ce qu'il dit, ce panneau ?", "ປ້າຍ|ນີ້|ຂຽນ|ວ່າ|ແນວໃດ|?"), ("Ouvert tous les jours.", "ເປີດ|ທຸກມື້|."), ("Où est la sortie ?", "ທາງອອກ|ຢູ່|ໃສ|?")],
  ["Trouve 5 photos de panneaux lao en ligne et traduis-les."], "Lis un vrai menu ou une affiche lao (photo) et explique-la à un natif."),
L(65, "Bilan A2", "Faire le point sur les 4 compétences du niveau A2.", "Clara raconte ses six mois au Laos.",
  [("S", "ຢູ່|ລາວ|ມາ|ດົນ|ປານໃດ|ແລ້ວ|?", "Tu es au Laos depuis combien de temps ?"),
   ("C", "ຫົກ|ເດືອນ|ແລ້ວ|.|ໄດ້|ຮຽນ|ຫຼາຍ|ຢ່າງ|.", "Six mois. J'ai appris beaucoup de choses."),
   ("S", "ປີໜ້າ|ຈະ|ຢູ່|ຕໍ່|ບໍ|?", "L'année prochaine, tu restes ?"),
   ("C", "ຖ້າ|ໄດ້|ວຽກ|ໃໝ່|ກໍ|ຈະ|ຢູ່|ຕໍ່|.", "Si j'ai un nouveau travail, je resterai.")],
  [("Depuis quand Clara est-elle au Laos ?", "Six mois."), ("Va-t-elle rester ?", "Si elle trouve un nouveau travail.")],
  [("ຕໍ່", "continuer, encore"), ("ຢູ່|ຕໍ່", "rester"), ("ຫຼາຍ|ຢ່າງ", "beaucoup de choses")],
  "révision A2", [("ມື້ວານ|…|ໄດ້", "passé"), ("ຈະ|…", "futur"), ("ກຳລັງ|…|ຢູ່", "en cours"), ("ຖ້າ|…|ກໍ", "condition")],
  ["Rappelle la règle de chaque structure."], "Bilan : temps (ໄດ້, ແລ້ວ, ຈະ, ກຳລັງ, ເຄີຍ), conditions, causes, comparaisons, discours rapporté, registres. Fais le test /test dans le projet.",
  "le dialogue d'une traite.",
  [("Depuis combien de temps ?", "ມາ|ດົນ|ປານໃດ|ແລ້ວ|?"), ("Si j'ai du travail, je resterai.", "ຖ້າ|ໄດ້|ວຽກ|ກໍ|ຈະ|ຢູ່|ຕໍ່|.")],
  ["Écris un texte de 15 phrases sur ton apprentissage du lao (passé, présent, futur)."], "Fais le test de fin de niveau A2 et une conversation de 10 minutes avec un natif."),
]
