# Partie B · Lire et écrire (leçons 6 à 20)
LESSONS = [
{
 "n": 6, "title": "Consonnes de classe moyenne (1)",
 "obj": "Lire et écrire tes 10 premiers mots avec ກ ຈ ດ ຕ et les voyelles າ ີ ູ.",
 "scene": "Clara range la maison avec Noy et lit les étiquettes.",
 "dia": [
  ("N", "ນີ້|ແມ່ນ|ຫຍັງ|?", "C'est quoi, ça ?"),
  ("C", "ນີ້|ແມ່ນ|ຈານ|.", "C'est une assiette."),
  ("N", "ແລ້ວ|ນັ້ນ|ເດ|?", "Et ça ?"),
  ("C", "ນັ້ນ|ແມ່ນ|ກາເຟ|.", "Ça, c'est du café."),
  ("N", "ອ່ານ|ໄດ້|ເກັ່ງ|ເນາະ|!", "Tu lis bien, dis donc !"),
  ("C", "ດີ|ແທ້|!|ຂ້ອຍ|ອ່ານ|ໄດ້|ແລ້ວ|.", "Super ! Je sais lire maintenant."),
 ],
 "ce": [("Quels objets Clara reconnaît-elle ?", "Une assiette (ຈານ) et du café (ກາເຟ)."), ("Que dit Noy ?", "Que Clara lit bien.")],
 "voc": [("ກາ", "corbeau", "ກ + າ"), ("ຕາ", "œil ; grand-père maternel", "ຕ + າ"), ("ດີ", "bien, bon", "ດ + ີ"), ("ຈານ", "assiette", "ຈ + າ + ນ"),
         ("ກາເຟ", "café", ""), ("ຕູ້", "armoire", "[À VÉRIFIER]"), ("ດູ", "regarder (rare)", "[À VÉRIFIER]"), ("ນີ້", "ceci", ""), ("ນັ້ນ", "cela", ""), ("ອ່ານ", "lire", "")],
 "gram": {"t": "les consonnes ກ ຈ ດ ຕ", "ex": [("ກາ", "k + aa"), ("ຈານ", "j + aa + n"), ("ດີ", "d + ii"), ("ຕາ", "t + aa")],
          "q": ["Où s'écrit la voyelle າ par rapport à la consonne ? Et ີ ?", "Ces quatre consonnes sont toutes de classe moyenne : quel ton ont ກາ, ດີ, ຕາ ?"],
          "rule": "La consonne est la base de la syllabe. La voyelle longue າ (aa) se met après, ີ (ii) au-dessus, ູ (uu) en dessous. ກ ຈ ດ ຕ sont de classe moyenne : sans marque et avec une voyelle longue, la syllabe a le ton montant (ǎ). On trace chaque lettre en commençant par la petite boucle."},
 "co": "le son j (entre tch et dj) de ຈ et le d franc de ດ.",
 "ant": [("C'est quoi, ça ?", "ນີ້|ແມ່ນ|ຫຍັງ|?"), ("C'est une assiette.", "ນີ້|ແມ່ນ|ຈານ|."), ("Ça, c'est du café.", "ນັ້ນ|ແມ່ນ|ກາເຟ|."), ("Je sais lire.", "ຂ້ອຍ|ອ່ານ|ໄດ້|.")],
 "ee": ["Recopie 5 fois chaque lettre : ກ ຈ ດ ຕ, en commençant par la boucle.", "Écris en lao : ຕາ, ດີ, ຈານ, ກາ, sans regarder."],
 "task": "Étiquette 5 objets de ta maison avec leur nom en lao.",
},
{
 "n": 7, "title": "Consonnes de classe moyenne (2)",
 "obj": "Lire ບ ປ ຢ ອ, utiliser ອ comme support de voyelle et écrire ton prénom en lao.",
 "scene": "Kèo aide Clara à écrire son prénom.",
 "dia": [
  ("K", "ເອື້ອຍ|ຂຽນ|ຊື່|ເປັນ|ບໍ|?", "Tu sais écrire ton prénom ?"),
  ("C", "ຍັງ|.|ຊ່ວຍ|ແດ່|.", "Pas encore. Aide-moi."),
  ("K", "ຄລາຣາ|ຂຽນ|ແບບ|ນີ້|.", "Clara, ça s'écrit comme ça."),
  ("C", "ຂອບໃຈ|.|ແລ້ວ|ຊື່|ເຈົ້າ|ເດ|?", "Merci. Et ton prénom ?"),
  ("K", "ແກ້ວ|.|ງ່າຍ|ໆ|.", "Kèo. Facile."),
  ("C", "ໂອເຄ|,|ຂ້ອຍ|ຈະ|ລອງ|.", "OK, je vais essayer."),
 ],
 "ce": [("Que demande Clara ?", "De l'aide pour écrire son prénom."), ("Comment Kèo trouve-t-il son prénom ?", "Facile.")],
 "voc": [("ບ້ານ", "village ; maison", "ບ + ້ + າ + ນ"), ("ປາ", "poisson", "ປ + າ"), ("ຢາ", "médicament", "ຢ + າ"), ("ອາ", "tante paternelle (cadette)", "ອ porte la voyelle"),
         ("ຂຽນ", "écrire", ""), ("ຊ່ວຍ", "aider", ""), ("ແດ່", "s'il te plaît (adoucit)", "après le verbe"), ("ແບບນີ້", "comme ça", ""),
         ("ງ່າຍ", "facile", ""), ("ລອງ", "essayer", "")],
 "gram": {"t": "ອ, support de voyelle", "ex": [("ອາ", "aa (voyelle seule)"), ("ອີ", "ii"), ("ອູ", "uu"), ("ປາ", "p + aa")],
          "q": ["Pourquoi écrit-on ອ devant une voyelle seule ?", "Quelle est la différence de son entre ບ et ປ ?"],
          "rule": "Une voyelle ne s'écrit jamais seule : elle a besoin d'une consonne. Pour une syllabe qui commence par une voyelle, on utilise ອ, une consonne muette (un petit coup de glotte). ບ = b sonore, ປ = p sans souffle."},
 "co": "la différence entre ບ (b) et ປ (p).",
 "ant": [("Aide-moi, s'il te plaît.", "ຊ່ວຍ|ແດ່|."), ("Je vais essayer.", "ຂ້ອຍ|ຈະ|ລອງ|."), ("C'est facile.", "ງ່າຍ|."), ("Ça s'écrit comme ça.", "ຂຽນ|ແບບນີ້|.")],
 "ee": ["Recopie ບ ປ ຢ ອ, 5 fois chacune.", "Écris ton prénom en lao avec l'aide d'un natif, puis recopie-le 3 fois."],
 "task": "Écris ton prénom en lao et fais-le lire à un locuteur natif.",
},
{
 "n": 8, "title": "Consonnes de classe haute",
 "obj": "Lire ຂ ສ ຖ ຜ ຝ ຫ et déchiffrer des étiquettes de boissons.",
 "scene": "Au café, Clara lit la carte des boissons.",
 "dia": [
  ("V", "ເອົາ|ຫຍັງ|ເອື້ອຍ|?", "Qu'est-ce que tu prends ?"),
  ("C", "ຂໍ|ກາເຟ|ໜຶ່ງ|ຈອກ|.", "Un café, s'il vous plaît."),
  ("V", "ຮ້ອນ|ຫຼື|ເຢັນ|?", "Chaud ou glacé ?"),
  ("C", "ເຢັນ|.|ບໍ່|ຫວານ|ຫຼາຍ|ເດີ|.", "Glacé. Pas trop sucré, hein."),
  ("V", "ໄດ້|ເຈົ້າ|.", "D'accord."),
  ("C", "ຂອບໃຈ|.", "Merci."),
 ],
 "ce": [("Que commande Clara ?", "Un café glacé, pas trop sucré."), ("Quelle question pose la vendeuse ?", "Chaud ou glacé ?")],
 "voc": [("ຂໍ", "demander ; je voudrais", "pour commander poliment"), ("ສາ", "particule (rare)", "ສ + າ [À VÉRIFIER]"), ("ຖົງ", "sac", "ຖ"), ("ຜັກ", "légume", "ຜ"),
         ("ຝົນ", "pluie", "ຝ"), ("ຫ້າ", "cinq", "ຫ"), ("ຮ້ອນ", "chaud", ""), ("ເຢັນ", "froid, frais", ""), ("ຫວານ", "sucré", ""), ("ຫຼື", "ou", "")],
 "gram": {"t": "la classe haute", "ex": [("ຂາ", "jambe, ton montant"), ("ຖົງ", "sac"), ("ຝົນ", "pluie"), ("ຫ້າ", "cinq")],
          "q": ["Compare ຂາ (classe haute) et ຄາ (classe basse) : même son, ton différent ?"],
          "rule": "Les 6 consonnes de classe haute (ຂ ສ ຖ ຜ ຝ ຫ) donnent, sans marque et en syllabe vivante, le ton montant. Elles ont souvent une « jumelle » en classe basse avec le même son : ຂ/ຄ, ສ/ຊ, ຖ/ທ, ຜ/ພ, ຝ/ຟ, ຫ/ຮ."},
 "co": "la différence de ton entre ຂາ et ຄາ.",
 "ant": [("Un café, s'il vous plaît.", "ຂໍ|ກາເຟ|ໜຶ່ງ|ຈອກ|."), ("Chaud ou glacé ?", "ຮ້ອນ|ຫຼື|ເຢັນ|?"), ("Pas trop sucré.", "ບໍ່|ຫວານ|ຫຼາຍ|."), ("Glacé, s'il vous plaît.", "ຂໍ|ເຢັນ|.")],
 "ee": ["Recopie les 6 consonnes hautes.", "Écris ta commande préférée au café en lao."],
 "task": "Commande une boisson en lao (dans un café lao ou en jeu de rôle avec un natif).",
},
{
 "n": 9, "title": "Consonnes de classe basse (1)",
 "obj": "Lire ຄ ງ ຊ ຍ ທ ນ ພ et reconnaître des noms de plats.",
 "scene": "Noy montre le menu d'un restaurant à Clara.",
 "dia": [
  ("N", "ມື້ນີ້|ກິນ|ຫຍັງ|ດີ|?", "On mange quoi aujourd'hui ?"),
  ("C", "ຂ້ອຍ|ຢາກ|ກິນ|ລາບ|.", "J'ai envie de larb."),
  ("N", "ລາບ|ຊີ້ນງົວ|ຫຼື|ລາບ|ໄກ່|?", "Larb de bœuf ou de poulet ?"),
  ("C", "ລາບ|ໄກ່|.|ແລ້ວ|ເຂົ້າໜຽວ|ນຳ|.", "Poulet. Et du riz gluant avec."),
  ("N", "ດີ|.|ຂ້ອຍ|ເອົາ|ຕຳໝາກຫຸ່ງ|.", "OK. Moi, je prends une salade de papaye."),
  ("C", "ເຜັດ|ບໍ|?", "C'est pimenté ?"),
  ("N", "ເຜັດ|ຫຼາຍ|!", "Très !"),
 ],
 "ce": [("Que choisit Clara ?", "Un larb de poulet avec du riz gluant."), ("Et Noy ?", "Une salade de papaye, très pimentée.")],
 "voc": [("ລາບ", "larb (salade de viande hachée)", "plat national"), ("ຊີ້ນງົວ", "viande de bœuf", ""), ("ໄກ່", "poulet", ""), ("ຕຳໝາກຫຸ່ງ", "salade de papaye", ""),
         ("ຢາກ", "avoir envie de, vouloir", "+ verbe"), ("ເອົາ", "prendre", "pour commander"), ("ຄົນ", "personne", "ຄ"), ("ງົວ", "bœuf, vache", "ງ"),
         ("ທາງ", "chemin", "ທ"), ("ພໍ່", "père", "ພ")],
 "cult": "Au Laos, on partage tous les plats au centre de la table et on mange le riz gluant avec les doigts.",
 "gram": {"t": "la classe basse", "ex": [("ຄາ", "coincé, ton haut"), ("ງາມ", "beau"), ("ນາ", "rizière"), ("ພູ", "montagne")],
          "q": ["Quel ton ont ces mots sans marque ?"],
          "rule": "Les consonnes de classe basse (ຄ ງ ຊ ຍ ທ ນ ພ ຟ ມ ຣ ລ ວ ຮ) donnent, sans marque et en syllabe vivante, le ton haut (á). [À VÉRIFIER avec un natif]"},
 "co": "les sons ng (ງ) et ny (ຍ) en début de mot.",
 "ant": [("J'ai envie de larb.", "ຂ້ອຍ|ຢາກ|ກິນ|ລາບ|."), ("Je prends une salade de papaye.", "ຂ້ອຍ|ເອົາ|ຕຳໝາກຫຸ່ງ|."), ("C'est pimenté ?", "ເຜັດ|ບໍ|?"), ("On mange quoi ?", "ກິນ|ຫຍັງ|ດີ|?")],
 "ee": ["Recopie les 7 consonnes de la leçon.", "Écris un mini-menu de 4 plats lao."],
 "task": "Lis à voix haute le menu d'un restaurant lao (photo ou vrai menu) et choisis ton plat.",
},
{
 "n": 10, "title": "Consonnes de classe basse (2)",
 "obj": "Lire ຟ ມ ຣ ລ ວ ຮ et reconnaître des noms de lieux en ville.",
 "scene": "Clara cherche des lieux sur une carte avec Kèo.",
 "dia": [
  ("C", "ຕະຫຼາດ|ຢູ່|ໃສ|?", "Où est le marché ?"),
  ("K", "ຢູ່|ໃກ້|ວັດ|.", "Près du temple."),
  ("C", "ແລ້ວ|ໂຮງໝໍ|ເດ|?", "Et l'hôpital ?"),
  ("K", "ໂຮງໝໍ|ຢູ່|ໄກ|.|ຕ້ອງ|ຂີ່|ລົດ|.", "L'hôpital est loin. Il faut prendre un véhicule."),
  ("C", "ຮ້ານອາຫານ|ລາວ|ມີ|ບໍ|?", "Il y a un restaurant lao ?"),
  ("K", "ມີ|ຫຼາຍ|ເລີຍ|!", "Plein !"),
 ],
 "ce": [("Où est le marché ?", "Près du temple."), ("Comment aller à l'hôpital ?", "Il faut un véhicule, c'est loin.")],
 "voc": [("ຕະຫຼາດ", "marché", ""), ("ວັດ", "temple, pagode", "ວ"), ("ໂຮງໝໍ", "hôpital", "ຮ"), ("ຮ້ານອາຫານ", "restaurant", ""), ("ໃກ້", "près", ""),
         ("ໄກ", "loin", ""), ("ມີ", "il y a ; avoir", "ມ"), ("ລົດ", "véhicule, voiture", "ລ"), ("ໄຟ", "feu ; électricité", "ຟ"), ("ເມືອງ", "ville", "")],
 "gram": {"t": "ມີ, « il y a »", "ex": [("ມີ|ຮ້ານອາຫານ|ບໍ|?", "il y a un restaurant ?"), ("ມີ|ຫຼາຍ", "il y en a plein"), ("ບໍ່ມີ", "il n'y en a pas")],
          "q": ["Comment dit-on « il n'y a pas » ?"],
          "rule": "ມີ veut dire « avoir » et « il y a ». Négation : ບໍ່ມີ. Question : ມີ…ບໍ ?"},
 "co": "la différence entre ລ (l) et ຣ, que beaucoup de Lao prononcent aussi « l ».",
 "ant": [("Où est le marché ?", "ຕະຫຼາດ|ຢູ່|ໃສ|?"), ("C'est près du temple.", "ຢູ່|ໃກ້|ວັດ|."), ("C'est loin.", "ຢູ່|ໄກ|."), ("Il y a un restaurant ?", "ມີ|ຮ້ານອາຫານ|ບໍ|?"), ("Il n'y en a pas.", "ບໍ່ມີ|.")],
 "ee": ["Recopie ຟ ມ ຣ ລ ວ ຮ.", "Écris 4 phrases avec ມີ ou ບໍ່ມີ sur ton quartier."],
 "task": "Décris ton quartier à un natif : ce qu'il y a et ce qu'il n'y a pas.",
},
{
 "n": 11, "title": "Syllabes vivantes et mortes",
 "obj": "Reconnaître si une syllabe est vivante ou morte, pour pouvoir en déduire le ton.",
 "scene": "Clara et Noy jouent à nommer des animaux.",
 "dia": [
  ("N", "ໂຕ|ນີ້|ແມ່ນ|ຫຍັງ|?", "C'est quoi, cet animal ?"),
  ("C", "ແມ່ນ|ນົກ|.", "C'est un oiseau."),
  ("N", "ແລ້ວ|ໂຕ|ນັ້ນ|ເດ|?", "Et celui-là ?"),
  ("C", "ແມ່ນ|ໝາ|.|ໝາ|ຂອງ|ໃຜ|?", "C'est un chien. À qui est ce chien ?"),
  ("N", "ໝາ|ຂອງ|ແກ້ວ|.", "C'est le chien de Kèo."),
  ("C", "ງາມ|ຫຼາຍ|!", "Il est très beau !"),
 ],
 "ce": [("Quels animaux voient-elles ?", "Un oiseau et un chien."), ("À qui est le chien ?", "À Kèo.")],
 "voc": [("ນົກ", "oiseau", "syllabe morte (finale k)"), ("ໝາ", "chien", "syllabe vivante"), ("ແມວ", "chat", "vivante (finale w)"), ("ງົວ", "bœuf", ""),
         ("ໄກ່", "poulet, poule", ""), ("ປາ", "poisson", ""), ("ຊ້າງ", "éléphant", ""), ("ໂຕ", "classificateur des animaux", "ໂຕນີ້ = cet animal"),
         ("ໃຜ", "qui ?", ""), ("ງາມ", "beau", "")],
 "gram": {"t": "vivante ou morte ?", "ex": [("ປາ", "vivante : voyelle longue, pas de finale"), ("ຈານ", "vivante : finale n"), ("ນົກ", "morte : finale k"), ("ເດັກ", "morte : finale k")],
          "q": ["Quelles finales rendent une syllabe « morte » ?", "Une voyelle courte sans finale, c'est vivant ou mort ?"],
          "rule": "Une syllabe est vivante si elle finit par une voyelle longue ou par une consonne sonore (m, n, ng, w, y). Elle est morte si elle finit par une voyelle courte ou par k, t, p. Ce type de syllabe, avec la classe de la consonne, donne le ton."},
 "co": "l'arrêt net à la fin des syllabes mortes (ນົກ, ເດັກ).",
 "ant": [("C'est quoi, cet animal ?", "ໂຕ|ນີ້|ແມ່ນ|ຫຍັງ|?"), ("C'est un oiseau.", "ແມ່ນ|ນົກ|."), ("À qui est ce chien ?", "ໝາ|ຂອງ|ໃຜ|?"), ("Il est très beau !", "ງາມ|ຫຼາຍ|!")],
 "ee": ["Classe ces mots en vivants ou morts : ນົກ, ປາ, ແມວ, ເດັກ, ຈານ, ໄກ່.", "Écris le nom de 5 animaux."],
 "task": "Nomme 8 animaux en lao devant un natif et demande-lui de corriger tes tons.",
},
{
 "n": 12, "title": "Le ton sans marque",
 "obj": "Déduire le ton d'un mot inconnu sans marque de ton, à partir de la classe et du type de syllabe.",
 "scene": "Noy teste Clara avec les couleurs.",
 "dia": [
  ("N", "ສີ|ນີ້|ແມ່ນ|ສີ|ຫຍັງ|?", "C'est quelle couleur, ça ?"),
  ("C", "ສີ|ແດງ|.", "Rouge."),
  ("N", "ຖືກ|ແລ້ວ|!|ແລ້ວ|ອັນ|ນີ້|ເດ|?", "Exact ! Et ça ?"),
  ("C", "ສີ|ຂຽວ|.", "Vert."),
  ("N", "ເຈົ້າ|ມັກ|ສີ|ຫຍັງ|?", "Tu aimes quelle couleur ?"),
  ("C", "ຂ້ອຍ|ມັກ|ສີ|ຟ້າ|.", "J'aime le bleu."),
 ],
 "ce": [("Quelles couleurs Clara reconnaît-elle ?", "Rouge et vert."), ("Quelle est sa couleur préférée ?", "Le bleu (ສີຟ້າ).")],
 "voc": [("ສີ", "couleur", "se met devant la couleur"), ("ແດງ", "rouge", ""), ("ຂຽວ", "vert", ""), ("ເຫຼືອງ", "jaune", ""), ("ຂາວ", "blanc", ""), ("ດຳ", "noir", ""),
         ("ສີຟ້າ", "bleu (ciel)", ""), ("ມັກ", "aimer", ""), ("ຖືກ|ແລ້ວ", "c'est juste", ""), ("ອັນ", "classificateur des objets", "")],
 "gram": {"t": "le tableau des tons sans marque", "ex": [("ດຳ", "classe moyenne, vivante → montant"), ("ຂາວ", "classe haute, vivante → montant"), ("ແດງ", "classe moyenne, vivante → montant"), ("ມັກ", "classe basse, morte courte → moyen")],
          "q": ["Avec le tableau, devine le ton de ງາມ et de ສີ."],
          "rule": "Sans marque : syllabe vivante → classe haute ou moyenne = montant (ǎ), classe basse = haut (á). Syllabe morte courte → haute = moyen (ā), moyenne = haut (á), basse = moyen (ā). Syllabe morte longue → haute ou moyenne = bas descendant (ȁ), basse = haut descendant (â). [Table à valider avec un natif]"},
 "co": "applique la règle à chaque couleur entendue, puis vérifie.",
 "ant": [("C'est quelle couleur ?", "ສີ|ຫຍັງ|?"), ("C'est rouge.", "ສີ|ແດງ|."), ("J'aime le bleu.", "ຂ້ອຍ|ມັກ|ສີຟ້າ|."), ("C'est juste !", "ຖືກ|ແລ້ວ|!")],
 "ee": ["Pour 6 mots nouveaux du dictionnaire, devine le ton avec la règle, puis vérifie avec l'audio ou un natif.", "Écris les 6 couleurs de la leçon."],
 "task": "Décris en lao la couleur de 5 objets autour de toi.",
},
{
 "n": 13, "title": "La marque ່",
 "obj": "Lire les mots avec la marque ່ et des phrases du quotidien.",
 "scene": "Le matin chez Noy.",
 "dia": [
  ("B", "ແກ້ວ|,|ຕື່ນ|ແລ້ວ|ບໍ|?", "Kèo, tu es réveillé ?"),
  ("K", "ຕື່ນ|ແລ້ວ|ແມ່|.", "Oui, maman."),
  ("B", "ອາບນ້ຳ|ແລ້ວ|ໄປ|ໂຮງຮຽນ|.", "Douche-toi et va à l'école."),
  ("K", "ຂ້ອຍ|ຍັງ|ເມື່ອຍ|ຢູ່|.", "Je suis encore fatigué."),
  ("B", "ບໍ່|ໄດ້|!|ໄປ|ໄວ|ໆ|.", "Pas question ! Vite."),
  ("K", "ໂອເຄ|,|ແມ່|.", "D'accord, maman."),
 ],
 "ce": [("Que demande Mme Boua ?", "Si Kèo est réveillé, puis qu'il se douche et aille à l'école."), ("Comment se sent Kèo ?", "Fatigué.")],
 "voc": [("ຕື່ນ", "se réveiller", "marque ່"), ("ອາບນ້ຳ", "se doucher", ""), ("ໂຮງຮຽນ", "école", ""), ("ເມື່ອຍ", "fatigué", "marque ່"), ("ແມ່", "maman", "marque ່"),
         ("ພໍ່", "papa", "marque ່"), ("ບໍ່", "ne… pas", "marque ່"), ("ໄວ", "vite", ""), ("ຍັງ|…|ຢູ່", "encore (en cours)", ""), ("ກ່ອນ", "avant", "marque ່")],
 "gram": {"t": "l'effet de ່", "ex": [("ຂ່າ", "classe haute + ່ → bas"), ("ກ່ອນ", "classe moyenne + ່ → bas"), ("ແມ່", "classe basse + ່ → moyen"), ("ພໍ່", "classe basse + ່ → moyen")],
          "q": ["Le ton change-t-il de la même façon pour toutes les classes ?"],
          "rule": "La marque ່ donne le ton bas (à) aux consonnes hautes et moyennes, et le ton moyen (ā) aux consonnes basses. [À VÉRIFIER avec un natif]"},
 "co": "les mots avec ່ : ແມ່, ພໍ່, ບໍ່.",
 "ant": [("Tu es réveillé ?", "ຕື່ນ|ແລ້ວ|ບໍ|?"), ("Je suis fatigué.", "ຂ້ອຍ|ເມື່ອຍ|."), ("Va à l'école.", "ໄປ|ໂຮງຮຽນ|."), ("Vite !", "ໄວ|ໆ|!")],
 "ee": ["Recopie 6 mots avec ່ et indique leur ton.", "Écris ta routine du matin en 3 phrases."],
 "task": "Raconte ta routine du matin à un natif en 4 phrases.",
},
{
 "n": 14, "title": "La marque ້",
 "obj": "Lire les mots avec ້ et les marques rares, et lire un court message.",
 "scene": "Clara reçoit un message de Noy.",
 "dia": [
  ("N", "ຄລາຣາ|,|ມື້ນີ້|ຫວ່າງ|ບໍ|?", "Clara, tu es libre aujourd'hui ?"),
  ("C", "ຫວ່າງ|.|ມີ|ຫຍັງ|?", "Oui. Il y a quoi ?"),
  ("N", "ໄປ|ກິນ|ເຝີ|ນຳ|ກັນ|ບໍ|?", "On va manger une soupe pho ensemble ?"),
  ("C", "ດີ|ໃຈ|ຫຼາຍ|!|ຈັກ|ໂມງ|?", "Avec plaisir ! À quelle heure ?"),
  ("N", "ສິບ|ໂມງ|ເຊົ້າ|.", "À dix heures du matin."),
  ("C", "ໄດ້|ເລີຍ|!", "Parfait !"),
 ],
 "ce": [("Que propose Noy ?", "D'aller manger une soupe pho ensemble."), ("À quelle heure ?", "Dix heures du matin.")],
 "voc": [("ຫວ່າງ", "libre, disponible", ""), ("ເຝີ", "soupe pho", ""), ("ດີໃຈ", "content", ""), ("ຈັກ|ໂມງ", "à quelle heure ?", ""), ("ສິບ", "dix", ""),
         ("ໂມງເຊົ້າ", "heure du matin", ""), ("ແລ້ວ", "déjà ; puis", "marque ້"), ("ເຂົ້າ", "riz", "marque ້"), ("ຫ້ອງ", "pièce, chambre", "marque ້"), ("ນ້ຳ", "eau", "marque ້")],
 "gram": {"t": "l'effet de ້", "ex": [("ຂ້າ", "classe haute + ້ → haut descendant"), ("ເຈົ້າ", "classe moyenne + ້ → haut descendant"), ("ນ້ຳ", "classe basse + ້ → bas descendant"), ("ແລ້ວ", "classe basse + ້ → bas descendant")],
          "q": ["Compare l'effet de ້ sur ຂ et sur ນ."],
          "rule": "La marque ້ donne le ton haut descendant (â) aux consonnes hautes et moyennes, et le ton bas descendant (ȁ) aux consonnes basses. Les marques ໊ et ໋ sont rares (mots empruntés, onomatopées). [À VÉRIFIER avec un natif]"},
 "co": "les mots avec ້ : ນ້ຳ, ແລ້ວ, ເຈົ້າ.",
 "ant": [("Tu es libre aujourd'hui ?", "ມື້ນີ້|ຫວ່າງ|ບໍ|?"), ("On va manger ensemble ?", "ໄປ|ກິນ|ນຳ|ກັນ|ບໍ|?"), ("À quelle heure ?", "ຈັກ|ໂມງ|?"), ("Parfait !", "ໄດ້|ເລີຍ|!")],
 "ee": ["Lis le dialogue à voix haute et souligne tous les ້.", "Écris un message de 3 phrases pour inviter quelqu'un à manger."],
 "task": "Envoie un vrai message en lao à un ami ou à un membre de ta famille pour l'inviter.",
},
{
 "n": 15, "title": "Le ຫ muet et les lettres jointes",
 "obj": "Lire les mots où ຫ change la classe d'une consonne basse et parler de la famille.",
 "scene": "Mme Boua montre des photos de famille.",
 "dia": [
  ("B", "ນີ້|ແມ່ນ|ຫຼານ|ຂອງ|ຂ້ອຍ|.", "Voici mon petit-enfant."),
  ("C", "ໜ້າຮັກ|ຫຼາຍ|!|ອາຍຸ|ຈັກ|ປີ|?", "Il est trop mignon ! Il a quel âge ?"),
  ("B", "ສອງ|ປີ|.", "Deux ans."),
  ("C", "ແລ້ວ|ນີ້|ແມ່ນ|ໃຜ|?", "Et lui, c'est qui ?"),
  ("B", "ນັ້ນ|ແມ່ນ|ຜົວ|ຂອງ|ຂ້ອຍ|ຕອນ|ໜຸ່ມ|.", "C'est mon mari quand il était jeune."),
  ("C", "ໂອ້ຍ|,|ງາມ|ແທ້|!", "Oh, il était beau !"),
 ],
 "ce": [("Qui est sur la première photo ?", "Le petit-enfant de Mme Boua, 2 ans."), ("Et sur la deuxième ?", "Son mari, jeune.")],
 "voc": [("ຫຼານ", "petit-enfant ; neveu, nièce", "ຫຼ"), ("ໜ້າຮັກ", "mignon", "ໜ"), ("ອາຍຸ", "âge", ""), ("ຈັກ|ປີ", "combien d'années ?", ""), ("ສອງ", "deux", ""),
         ("ຜົວ", "mari", ""), ("ເມຍ", "épouse", ""), ("ໜຸ່ມ", "jeune", "ໜ"), ("ໝາ", "chien", "ໝ"), ("ຫຍັງ", "quoi", "ຫຍ")],
 "gram": {"t": "ຫ qui change la classe", "ex": [("ໝາ", "ຫ + ມ → classe haute"), ("ໜຸ່ມ", "ຫ + ນ"), ("ຫຼານ", "ຫ + ລ"), ("ຫວານ", "ຫ + ວ")],
          "q": ["ໝາ s'écrit avec ມ (classe basse). Pourquoi a-t-il le ton montant ?"],
          "rule": "Placé devant une consonne basse sonore (ງ ຍ ນ ມ ລ ວ), un ຫ muet la fait passer en classe haute. ຫນ et ຫມ s'écrivent souvent en une seule lettre : ໜ et ໝ. ຫລ s'écrit souvent ຫຼ."},
 "co": "le ton montant de ໝາ, ໜ້າ, ຫຼານ.",
 "ant": [("Il est trop mignon !", "ໜ້າຮັກ|ຫຼາຍ|!"), ("Il a quel âge ?", "ອາຍຸ|ຈັກ|ປີ|?"), ("Deux ans.", "ສອງ|ປີ|."), ("C'est qui ?", "ແມ່ນ|ໃຜ|?")],
 "ee": ["Recopie ໜ ໝ ຫຼ ຫງ ຫຍ ຫວ dans un mot chacun.", "Décris une photo de famille en 3 phrases."],
 "task": "Montre une photo de famille à un natif et présente 3 personnes.",
},
{
 "n": 16, "title": "Voyelles composées",
 "obj": "Lire les voyelles ເ-ຍ, ເ-ືອ, -ົວ et parler de fruits.",
 "scene": "Au marché, Clara achète des fruits.",
 "dia": [
  ("V", "ຊື້|ຫຍັງ|ເອື້ອຍ|?", "Qu'est-ce que tu achètes ?"),
  ("C", "ໝາກມ່ວງ|ກິໂລ|ລະ|ເທົ່າໃດ|?", "Combien le kilo de mangues ?"),
  ("V", "ຊາວ|ພັນ|ກີບ|.", "Vingt mille kips."),
  ("C", "ແລ້ວ|ໝາກກ້ວຍ|ເດ|?", "Et les bananes ?"),
  ("V", "ສິບ|ພັນ|.", "Dix mille."),
  ("C", "ເອົາ|ທັງ|ສອງ|ຢ່າງ|.", "Je prends les deux."),
 ],
 "ce": [("Combien coûtent les mangues ?", "20 000 kips le kilo."), ("Que prend Clara ?", "Les mangues et les bananes.")],
 "voc": [("ໝາກໄມ້", "fruit", ""), ("ໝາກມ່ວງ", "mangue", ""), ("ໝາກກ້ວຍ", "banane", "-ົວ (ua)"), ("ໝາກພ້າວ", "noix de coco", ""), ("ກິໂລ", "kilo", ""),
         ("ເທົ່າໃດ", "combien ?", ""), ("ພັນ", "mille", ""), ("ກີບ", "kip (monnaie)", ""), ("ເມຍ", "épouse", "ເ-ຍ (ia)"), ("ເຮືອ", "bateau", "ເ-ືອ (ʉa)")],
 "gram": {"t": "les voyelles composées", "ex": [("ເມຍ", "ia"), ("ເຮືອ", "ʉa"), ("ງົວ", "ua"), ("ໝາກກ້ວຍ", "ua devant une finale")],
          "q": ["Comment s'écrit ua quand il y a une consonne finale ?"],
          "rule": "Trois diphtongues : ເ-ຍ (ia), ເ-ືອ (ʉa), -ົວ (ua). Devant une consonne finale, -ົວ s'écrit -ວ- (ກ້ວຍ) et ເ-ຍ s'écrit -ຽ- (ຮຽນ)."},
 "co": "le glissement de la voyelle dans ເຮືອ et ງົວ.",
 "ant": [("Combien le kilo ?", "ກິໂລ|ລະ|ເທົ່າໃດ|?"), ("Vingt mille kips.", "ຊາວ|ພັນ|ກີບ|."), ("Je prends les deux.", "ເອົາ|ທັງ|ສອງ|ຢ່າງ|."), ("Et les bananes ?", "ແລ້ວ|ໝາກກ້ວຍ|ເດ|?")],
 "ee": ["Écris le nom de 5 fruits et souligne les diphtongues.", "Écris ta liste de courses de fruits."],
 "task": "Achète des fruits en lao (au marché asiatique ou en jeu de rôle avec un natif).",
},
{
 "n": 17, "title": "Voyelles spéciales et signes",
 "obj": "Lire ໄ ໃ ເ-ົາ -ຳ, les signes ໆ et ຯ, et commander au restaurant.",
 "scene": "Au restaurant avec la famille.",
 "dia": [
  ("S", "ກິນ|ໃຫ້|ອີ່ມ|ເດີ|!", "Mangez bien !"),
  ("C", "ອາຫານ|ແຊບ|ຫຼາຍໆ|.", "La nourriture est vraiment bonne."),
  ("S", "ເອົາ|ນ້ຳ|ເພີ່ມ|ບໍ|?", "Tu veux plus d'eau ?"),
  ("C", "ບໍ່|ເປັນ|ຫຍັງ|,|ອີ່ມ|ແລ້ວ|.", "Non merci, je suis rassasiée."),
  ("S", "ນ້ອງ|,|ໄລ່ເງິນ|ແດ່|!", "S'il vous plaît, l'addition !"),
  ("C", "ຂອບໃຈ|ຫຼາຍໆ|ພໍ່|.", "Merci beaucoup, monsieur."),
 ],
 "ce": [("Que dit M. Somsak au début ?", "Mangez bien (jusqu'à être rassasiés)."), ("Comment demande-t-il l'addition ?", "ນ້ອງ, ໄລ່ເງິນແດ່ !")],
 "voc": [("ໃຫ້", "donner ; pour que", "ໃ"), ("ໄປ", "aller", "ໄ"), ("ເອົາ", "prendre", "ເ-ົາ"), ("ນ້ຳ", "eau", "-ຳ"), ("ອີ່ມ", "rassasié", ""),
         ("ເພີ່ມ", "ajouter, plus", "[À VÉRIFIER]"), ("ໄລ່ເງິນ", "l'addition (payer)", ""), ("ນ້ອງ", "(appeler le serveur)", "on l'appelle « petit frère/sœur »"), ("ຫຼາຍໆ", "très, beaucoup", "ໆ = répétition"), ("ຯລຯ", "etc.", "ຯ = abréviation")],
 "cult": "Pour appeler le serveur, on dit ນ້ອງ (s'il est plus jeune) ou ເອື້ອຍ / ອ້າຍ (s'il est plus âgé), jamais un « monsieur » distant.",
 "gram": {"t": "ໄ ໃ ເ-ົາ -ຳ et ໆ", "ex": [("ໄປ", "ay"), ("ໃຫ້", "ay (même son)"), ("ເອົາ", "ao"), ("ນ້ຳ", "am"), ("ຫຼາຍໆ", "lǎay-lǎay : le mot répété")],
          "q": ["ໄ et ໃ ont-ils le même son ?"],
          "rule": "ໄ et ໃ se prononcent tous deux « ay » : ໃ ne s'écrit que dans une vingtaine de mots à apprendre par cœur. ເ-ົາ = ao, -ຳ = am. ໆ répète le mot précédent ; ຯ abrège (ຯລຯ = etc.)."},
 "co": "« ay » dans ໄປ et ໃຫ້ : même son.",
 "ant": [("L'addition, s'il vous plaît !", "ໄລ່ເງິນ|ແດ່|!"), ("Je suis rassasiée.", "ອີ່ມ|ແລ້ວ|."), ("C'est vraiment bon.", "ແຊບ|ຫຼາຍໆ|."), ("Tu veux de l'eau ?", "ເອົາ|ນ້ຳ|ບໍ|?")],
 "ee": ["Recopie 5 mots avec ໃ.", "Écris un mini-dialogue au restaurant de 4 répliques."],
 "task": "Joue avec un natif une scène complète au restaurant : commander, commenter, demander l'addition.",
},
{
 "n": 18, "title": "Les consonnes finales",
 "obj": "Lire les 8 consonnes finales et écrire une liste de courses.",
 "scene": "Clara prépare ses courses avec Noy.",
 "dia": [
  ("N", "ຕ້ອງ|ຊື້|ຫຍັງ|ແດ່|?", "Il faut acheter quoi ?"),
  ("C", "ເຂົ້າໜຽວ|,|ໄຂ່|,|ຜັກ|,|ແລະ|ນົມ|.", "Du riz gluant, des œufs, des légumes et du lait."),
  ("N", "ຊີ້ນ|ເດ|?", "Et de la viande ?"),
  ("C", "ຊີ້ນໝູ|ໜຶ່ງ|ກິໂລ|.", "Un kilo de porc."),
  ("N", "ໄປ|ຕະຫຼາດ|ນຳ|ກັນ|ບໍ|?", "On va au marché ensemble ?"),
  ("C", "ໄປ|!", "On y va !"),
 ],
 "ce": [("Que doit acheter Clara ?", "Riz gluant, œufs, légumes, lait, et un kilo de porc.")],
 "voc": [("ຊື້", "acheter", ""), ("ໄຂ່", "œuf", ""), ("ຜັກ", "légume", "finale k"), ("ນົມ", "lait", "finale m"), ("ຊີ້ນ", "viande", "finale n"),
         ("ໝູ", "porc", ""), ("ແລະ", "et", ""), ("ກິໂລ", "kilo", ""), ("ເກືອ", "sel", ""), ("ນ້ຳປາ", "sauce de poisson", "")],
 "gram": {"t": "les 8 finales", "ex": [("ຜັກ", "-k (ກ)"), ("ເດັກ", "-k"), ("ຊີ້ນ", "-n (ນ)"), ("ນົມ", "-m (ມ)"), ("ເມືອງ", "-ng (ງ)")],
          "q": ["Quelles finales sont « sourdes » (syllabe morte) ?"],
          "rule": "Le lao n'a que 8 sons en fin de syllabe : -k (ກ), -ng (ງ), -t (ດ), -n (ນ), -p (ບ), -m (ມ), -y (ຍ), -w (ວ). -k, -t, -p ne sont pas relâchés : la bouche se ferme sans bruit."},
 "co": "les finales -k, -t, -p non relâchées.",
 "ant": [("Il faut acheter quoi ?", "ຕ້ອງ|ຊື້|ຫຍັງ|ແດ່|?"), ("Un kilo de porc.", "ຊີ້ນໝູ|ໜຶ່ງ|ກິໂລ|."), ("On va au marché ?", "ໄປ|ຕະຫຼາດ|ບໍ|?"), ("On y va !", "ໄປ|!")],
 "ee": ["Écris ta vraie liste de courses de la semaine en lao.", "Classe les mots selon leur finale."],
 "task": "Fais ta liste de courses en lao et lis-la à un natif.",
},
{
 "n": 19, "title": "Taper en lao",
 "obj": "Installer et utiliser un clavier lao, ponctuer, et écrire un SMS.",
 "scene": "Kèo apprend à Clara à écrire des messages.",
 "dia": [
  ("K", "ເອື້ອຍ|ມີ|ແປ້ນພິມ|ລາວ|ບໍ|?", "Tu as un clavier lao ?"),
  ("C", "ບໍ່|ມີ|.|ເຮັດ|ແນວໃດ|?", "Non. On fait comment ?"),
  ("K", "ເຂົ້າ|ໄປ|ຕັ້ງຄ່າ|ແລ້ວ|ເພີ່ມ|ພາສາລາວ|.", "Va dans les réglages et ajoute le lao."),
  ("C", "ໄດ້|ແລ້ວ|!|ສົ່ງ|ຂໍ້ຄວາມ|ໃຫ້|ເຈົ້າ|ເດີ|.", "Ça y est ! Je t'envoie un message."),
  ("K", "ໄດ້ຮັບ|ແລ້ວ|.|ເກັ່ງ|!", "Bien reçu. Bravo !"),
 ],
 "ce": [("Que doit faire Clara pour taper en lao ?", "Aller dans les réglages et ajouter le lao.")],
 "voc": [("ແປ້ນພິມ", "clavier", "[À VÉRIFIER]"), ("ຕັ້ງຄ່າ", "réglages", "[À VÉRIFIER]"), ("ເພີ່ມ", "ajouter", ""), ("ສົ່ງ", "envoyer", ""), ("ຂໍ້ຄວາມ", "message", ""),
         ("ໄດ້ຮັບ", "recevoir", ""), ("ແນວໃດ", "comment ?", ""), ("ໂທລະສັບ", "téléphone", "")],
 "gram": {"t": "les espaces en lao", "ex": [("ສະບາຍດີ|.|ເຈົ້າ|ສະບາຍດີ|ບໍ|?", "deux phrases : un espace entre elles"), ("ຂ້ອຍ|ຊື່|ຄລາຣາ", "pas d'espace entre les mots")],
          "q": ["Où mets-tu les espaces dans un SMS lao ?"],
          "rule": "On n'écrit pas d'espace entre les mots, seulement entre les phrases ou les propositions. Le point est rare ; ? et ! s'utilisent comme en français. Sur clavier, les voyelles et marques se tapent après la consonne."},
 "co": "relis tes SMS à voix haute pour vérifier.",
 "ant": [("Tu as un clavier lao ?", "ມີ|ແປ້ນພິມ|ລາວ|ບໍ|?"), ("On fait comment ?", "ເຮັດ|ແນວໃດ|?"), ("Je t'envoie un message.", "ສົ່ງ|ຂໍ້ຄວາມ|ໃຫ້|ເຈົ້າ|."), ("Bien reçu.", "ໄດ້ຮັບ|ແລ້ວ|.")],
 "ee": ["Installe le clavier lao sur ton téléphone.", "Écris 3 SMS en lao : un bonjour, une invitation, un merci."],
 "task": "Envoie 3 SMS en lao à un natif et demande-lui de corriger.",
},
{
 "n": 20, "title": "Bilan lecture et écriture",
 "obj": "Lire un court texte à voix haute sans romanisation et en expliquer les tons.",
 "scene": "Clara lit à voix haute la présentation qu'elle a écrite.",
 "dia": [
  ("C", "ສະບາຍດີ|.|ຂ້ອຍ|ຊື່|ຄລາຣາ|.", "Bonjour. Je m'appelle Clara."),
  ("C", "ຂ້ອຍ|ແມ່ນ|ຄົນຝຣັ່ງ|,|ມາແຕ່|ປາຣີ|.", "Je suis française, je viens de Paris."),
  ("C", "ຕອນນີ້|ຂ້ອຍ|ຢູ່|ວຽງຈັນ|.", "Maintenant, j'habite à Vientiane."),
  ("C", "ຂ້ອຍ|ມັກ|ກິນ|ລາບ|ແລະ|ເຂົ້າໜຽວ|.", "J'aime manger du larb et du riz gluant."),
  ("N", "ອ່ານ|ໄດ້|ດີ|ຫຼາຍ|!", "Tu lis très bien !"),
 ],
 "ce": [("Que raconte Clara ?", "Son prénom, son origine, où elle habite et ce qu'elle aime manger.")],
 "voc": [("ອ່ານ", "lire", ""), ("ຂຽນ", "écrire", ""), ("ຕົວໜັງສື", "lettre, caractère", ""), ("ປະໂຫຍກ", "phrase", ""), ("ຄຳ", "mot", ""), ("ສຽງ", "son ; ton", "")],
 "gram": {"t": "révision : classe + syllabe + marque = ton", "ex": [("ຂ້ອຍ", "haute + ້ → haut descendant"), ("ຊື່", "basse + ່ → moyen"), ("ມັກ", "basse, morte courte → moyen"), ("ລາບ", "basse, morte longue → haut descendant")],
          "q": ["Explique le ton de chaque mot de la première phrase du dialogue."],
          "rule": "Pour trouver le ton : 1) la classe de la consonne (haute, moyenne, basse, ou haute grâce au ຫ muet) ; 2) le type de syllabe (vivante, morte courte, morte longue) ; 3) la marque (aucune, ່, ້). Le tableau complet est dans les leçons 12 à 14."},
 "co": "écoute le texte, puis lis-le en même temps que la voix.",
 "ant": [("Je m'appelle Clara.", "ຂ້ອຍ|ຊື່|ຄລາຣາ|."), ("Je suis française.", "ຂ້ອຍ|ແມ່ນ|ຄົນຝຣັ່ງ|."), ("J'habite à Vientiane.", "ຂ້ອຍ|ຢູ່|ວຽງຈັນ|."), ("J'aime le larb.", "ຂ້ອຍ|ມັກ|ລາບ|.")],
 "ee": ["Écris ta propre présentation de 6 phrases en lao, sans romanisation.", "Pour chaque mot, note son ton et explique pourquoi."],
 "task": "Lis ta présentation à voix haute à un natif, sans romanisation.",
},
]
