# Partie A · Fondations (leçons 1 à 5). La leçon 0 (alphabet) est écrite à la main dans l00.json.
LESSONS = [
{
 "n": 1, "title": "Les 6 tons · Saluer",
 "obj": "Saluer, demander comment ça va, remercier, s'excuser et prendre congé, avec les bons tons.",
 "intro": "Personnages du cours : Clara, une Française qui vient de s'installer à Vientiane, et la famille de Noy, sa voisine : sa mère Mme Boua, son père M. Somsak et son petit frère Kèo.",
 "scene": "Clara croise Noy devant chez elle, le matin.",
 "dia": [
  ("C", "ສະບາຍດີ|!", "Bonjour !"),
  ("N", "ສະບາຍດີ|ເຈົ້າ|!|ສະບາຍດີ|ບໍ|?", "Bonjour ! Ça va ?"),
  ("C", "ສະບາຍດີ|,|ຂອບໃຈ|.|ເຈົ້າ|ເດ|?", "Ça va, merci. Et toi ?"),
  ("N", "ສະບາຍດີ|ຄືກັນ|.", "Ça va aussi."),
  ("C", "ໂອ້ຍ|!|ຂໍໂທດ|!", "Oh ! Pardon !"),
  ("N", "ບໍ່ເປັນຫຍັງ|.", "Pas grave."),
  ("C", "ຂອບໃຈ|ຫຼາຍໆ|.|ໄປກ່ອນ|ເດີ|!", "Merci beaucoup. J'y vais !"),
  ("N", "ພົບກັນໃໝ່|!", "À bientôt !"),
 ],
 "ce": [("Que demande Noy après « bonjour » ?", "Si ça va : ສະບາຍດີບໍ ?"),
        ("Comment Clara renvoie-t-elle la question ?", "ເຈົ້າເດ ? — « et toi ? »"),
        ("Que répond Noy quand Clara s'excuse ?", "ບໍ່ເປັນຫຍັງ — pas grave.")],
 "voc": [("ສະບາຍດີ", "bonjour ; ça va", "salutation de base, à toute heure"),
         ("ສະບາຍດີ|ບໍ", "ça va ?", "la question se fait avec ບໍ à la fin"),
         ("ຂອບໃຈ", "merci", ""), ("ຂອບໃຈ|ຫຼາຍໆ", "merci beaucoup", "ໆ = répéter le mot"),
         ("ຂໍໂທດ", "pardon, excusez-moi", "s'excuser ou attirer l'attention"),
         ("ບໍ່ເປັນຫຍັງ", "pas grave ; de rien", "réponse à merci et à pardon"),
         ("ເຈົ້າ", "oui (poli) ; toi, vous", "très fréquent, poli"),
         ("ຄືກັນ", "pareillement, aussi", ""),
         ("ໄປກ່ອນ|ເດີ", "j'y vais (au revoir familier)", "litt. « je pars avant »"),
         ("ພົບກັນໃໝ່", "à bientôt", "litt. « se revoir de nouveau »"),
         ("ລາກ່ອນ", "au revoir (soutenu)", "rare à l'oral, utile à reconnaître")],
 "cult": "On salue en joignant les mains (ນົບ) devant un aîné ou une personne respectée. Entre amis, on dit souvent juste ໄປໃສ ? « tu vas où ? » ou ກິນເຂົ້າແລ້ວບໍ ? « tu as mangé ? » au lieu de ສະບາຍດີ.",
 "gram": {"t": "les 6 tons", "ex": [("ຂາ", "jambe"), ("ຄາ", "coincé"), ("ຄ່າ", "prix, valeur"), ("ຂ່າ", "galanga"), ("ຂ້າ", "tuer"), ("ຄ້າ", "commerce")],
          "q": ["Les six mots ont les mêmes sons. Qu'est-ce qui change ?", "Repère les deux petits signes au-dessus des lettres : ່ et ້. Où les vois-tu ?"],
          "rule": "Le lao de Vientiane a 6 tons. La mélodie de la syllabe change le sens : montant (ǎ), haut (á), moyen (ā), bas (à), haut descendant (â), bas descendant (ȁ). À l'écrit, le ton se déduit de la classe de la consonne, du type de syllabe et des marques ່ et ້ : tu apprendras ces règles en Partie B. [À VÉRIFIER : description des tons avec un natif]"},
 "co": "seulement la mélodie : est-ce que ça monte, ça descend, ou ça reste plat ?",
 "tones": [("ຂາ", "Montant", "jambe"), ("ຄາ", "Haut", "coincé"), ("ຄ່າ", "Moyen", "prix"), ("ຂ່າ", "Bas", "galanga"), ("ຂ້າ", "Haut descendant", "tuer"), ("ຄ້າ", "Bas descendant", "commerce")],
 "ant": [("Bonjour ! Ça va ?", "ສະບາຍດີ|!|ສະບາຍດີ|ບໍ|?"), ("Ça va, merci.", "ສະບາຍດີ|,|ຂອບໃຈ|."), ("Et toi ?", "ເຈົ້າ|ເດ|?"),
         ("Pardon !", "ຂໍໂທດ|!"), ("Merci beaucoup.", "ຂອບໃຈ|ຫຼາຍໆ|."), ("À bientôt !", "ພົບກັນໃໝ່|!")],
 "rp": ("N", "ສະບາຍດີ|ເຈົ້າ|!|ສະບາຍດີ|ບໍ|?", "Bonjour ! Ça va ?"),
 "ee": ["Écris de mémoire, en romanisation avec les tons : bonjour, merci, pardon, pas grave.", "Écris un échange de 4 répliques : tu salues quelqu'un, tu demandes comment il va, tu le remercies, tu prends congé."],
 "task": "Salue un locuteur lao (en vrai ou en appel), demande-lui comment il va, remercie-le et prends congé, sans regarder tes notes.",
},
{
 "n": 2, "title": "Voyelles courtes et longues · Se présenter",
 "obj": "Dire comment tu t'appelles, demander le prénom de l'autre et dire que tu es enchantée.",
 "scene": "Noy présente Clara à sa mère, Mme Boua.",
 "dia": [
  ("N", "ແມ່|,|ນີ້|ແມ່ນ|ໝູ່|ຂອງ|ຂ້ອຍ|.", "Maman, voici mon amie."),
  ("B", "ສະບາຍດີ|ລູກ|.|ເຈົ້າ|ຊື່|ຫຍັງ|?", "Bonjour ma fille. Comment tu t'appelles ?"),
  ("C", "ສະບາຍດີ|ເຈົ້າ|.|ຂ້ອຍ|ຊື່|ຄລາຣາ|.", "Bonjour madame. Je m'appelle Clara."),
  ("B", "ຍິນດີທີ່ໄດ້ຮູ້ຈັກ|.", "Enchantée."),
  ("C", "ຍິນດີທີ່ໄດ້ຮູ້ຈັກ|ຄືກັນ|.", "Enchantée aussi."),
  ("B", "ຄລາຣາ|ມີ|ຊື່ຫຼິ້ນ|ບໍ|?", "Clara, tu as un surnom ?"),
  ("C", "ບໍ່|ມີ|.|ຊື່ຫຼິ້ນ|ຂອງ|ເຈົ້າ|ແມ່ນ|ຫຍັງ|?", "Non. Et quel est ton surnom à toi ?"),
  ("B", "ຊື່ຫຼິ້ນ|ຂອງ|ຂ້ອຍ|ແມ່ນ|ບົວ|.", "Mon surnom, c'est Boua."),
 ],
 "ce": [("Comment Noy présente-t-elle Clara ?", "ນີ້ແມ່ນໝູ່ຂອງຂ້ອຍ — voici mon amie."),
        ("Quelle question pose Mme Boua en premier ?", "ເຈົ້າຊື່ຫຍັງ ? — comment tu t'appelles ?"),
        ("Qu'est-ce qu'un ຊື່ຫຼິ້ນ ?", "Un surnom : presque tous les Lao en ont un, utilisé au quotidien.")],
 "voc": [("ຂ້ອຍ", "je, moi", "neutre, le plus courant"), ("ເຈົ້າ", "tu, vous", "poli"), ("ຊື່", "s'appeler ; nom", ""),
         ("ຫຍັງ", "quoi ?", "se place là où serait la réponse"), ("ເຈົ້າ|ຊື່|ຫຍັງ|?", "comment tu t'appelles ?", ""),
         ("ຂ້ອຍ|ຊື່", "je m'appelle…", ""), ("ຍິນດີທີ່ໄດ້ຮູ້ຈັກ", "enchanté(e)", "litt. « content d'avoir fait connaissance »"),
         ("ນີ້", "ceci, voici", ""), ("ແມ່ນ", "être (c'est)", "relie deux noms"), ("ໝູ່", "ami(e)", "familier ; ເພື່ອນ est plus neutre"),
         ("ຂອງ", "de (possession)", "ໝູ່ຂອງຂ້ອຍ = mon ami"), ("ຊື່ຫຼິ້ນ", "surnom", "litt. « nom pour jouer »")],
 "cult": "Au Laos, on s'appelle presque toujours par le surnom (ຊື່ຫຼິ້ນ), précédé d'un terme d'âge : ເອື້ອຍນ້ອຍ « grande sœur Noy », ນ້ອງແກ້ວ « petit Kèo ».",
 "gram": {"t": "la question reste dans l'ordre de la réponse", "ex": [("ເຈົ້າ|ຊື່|ຫຍັງ|?", "tu t'appelles comment ?"), ("ຂ້ອຍ|ຊື່|ຄລາຣາ", "je m'appelle Clara"), ("ນີ້|ແມ່ນ|ຫຍັງ|?", "c'est quoi, ça ?"), ("ນີ້|ແມ່ນ|ໝູ່|ຂອງ|ຂ້ອຍ", "c'est mon ami")],
          "q": ["Compare la question et la réponse : où se trouve ຫຍັງ ?", "Le verbe change-t-il de forme selon la personne ?"],
          "rule": "En lao, le mot interrogatif (ຫຍັງ « quoi », ໃຜ « qui », ໃສ « où ») prend la place de l'information demandée : on ne déplace rien. Et les verbes ne se conjuguent jamais : ຂ້ອຍຊື່, ເຈົ້າຊື່, ລາວຊື່."},
 "co": "la différence entre voyelles courtes et longues : ຊື່ (sʉ̄ʉ, long) contre ຫຼິ້ນ (lîn, court).",
 "ant": [("Comment tu t'appelles ?", "ເຈົ້າ|ຊື່|ຫຍັງ|?"), ("Je m'appelle Clara.", "ຂ້ອຍ|ຊື່|ຄລາຣາ|."), ("Enchantée.", "ຍິນດີທີ່ໄດ້ຮູ້ຈັກ|."),
         ("Voici mon amie.", "ນີ້|ແມ່ນ|ໝູ່|ຂອງ|ຂ້ອຍ|."), ("C'est quoi, ça ?", "ນີ້|ແມ່ນ|ຫຍັງ|?"), ("Quel est ton surnom ?", "ຊື່ຫຼິ້ນ|ຂອງ|ເຈົ້າ|ແມ່ນ|ຫຍັງ|?")],
 "rp": ("B", "ສະບາຍດີ|ລູກ|.|ເຈົ້າ|ຊື່|ຫຍັງ|?", "Bonjour. Comment tu t'appelles ?"),
 "ee": ["Écris ta présentation en 3 phrases (prénom, surnom si tu en as un, « enchantée »).", "Transforme : ຂ້ອຍຊື່ຄລາຣາ → pose la question correspondante."],
 "task": "Présente-toi à un locuteur lao et demande-lui son prénom et son surnom.",
},
{
 "n": 3, "title": "Consonnes aspirées · D'où viens-tu ?",
 "obj": "Dire d'où tu viens, ta nationalité et où tu habites, et poser les mêmes questions.",
 "scene": "M. Somsak rentre et rencontre Clara.",
 "dia": [
  ("S", "ສະບາຍດີ|.|ເຈົ້າ|ແມ່ນ|ຄົນ|ປະເທດ|ໃດ|?", "Bonjour. Tu es de quel pays ?"),
  ("C", "ຂ້ອຍ|ແມ່ນ|ຄົນຝຣັ່ງ|.", "Je suis française."),
  ("S", "ມາແຕ່|ປາຣີ|ບໍ|?", "Tu viens de Paris ?"),
  ("C", "ແມ່ນ|ແລ້ວ|.|ຂ້ອຍ|ມາແຕ່|ປາຣີ|.", "Oui, je viens de Paris."),
  ("S", "ຕອນນີ້|ເຈົ້າ|ຢູ່|ໃສ|?", "Et maintenant, tu habites où ?"),
  ("C", "ຂ້ອຍ|ຢູ່|ວຽງຈັນ|,|ໃກ້|ເຮືອນ|ນ້ອຍ|.", "J'habite à Vientiane, près de chez Noy."),
  ("S", "ເວົ້າລາວ|ເກັ່ງ|ເນາະ|!", "Tu parles bien lao, dis donc !"),
  ("C", "ໜ້ອຍ|ໜຶ່ງ|ເຈົ້າ|.|ຂອບໃຈ|.", "Un petit peu. Merci."),
 ],
 "ce": [("De quel pays vient Clara ?", "De France : ຄົນຝຣັ່ງ."), ("Où habite-t-elle ?", "À Vientiane, près de chez Noy."), ("Comment répond-elle au compliment ?", "ໜ້ອຍໜຶ່ງ — un petit peu (modestie attendue).")],
 "voc": [("ຄົນ", "personne", "ຄົນ + pays = nationalité"), ("ຄົນລາວ", "Lao (personne)", ""), ("ຄົນຝຣັ່ງ", "Français(e)", "ຝຣັ່ງ désigne aussi les Occidentaux en général"),
         ("ປະເທດ", "pays", ""), ("ປະເທດ|ໃດ", "quel pays ?", ""), ("ມາແຕ່", "venir de", ""), ("ຢູ່", "habiter ; se trouver", ""),
         ("ໃສ", "où ?", ""), ("ຢູ່|ໃສ|?", "tu habites où ?", ""), ("ຕອນນີ້", "maintenant", ""), ("ເວົ້າລາວ", "parler lao", ""),
         ("ເກັ່ງ", "doué, fort", "compliment très courant")],
 "cult": "Réponds toujours aux compliments avec modestie : ໜ້ອຍໜຶ່ງ « un petit peu » ou ບໍ່ເກັ່ງ « pas douée ».",
 "gram": {"t": "k / kh, t / th, p / ph", "ex": [("ກິນ", "manger (k sans souffle)"), ("ຄົນ", "personne (kh avec souffle)"), ("ຕາ", "œil (t)"), ("ທາງ", "chemin (th)"), ("ປາ", "poisson (p)"), ("ພູ", "montagne (ph)")],
          "q": ["Mets ta main devant la bouche : où sens-tu un souffle ?", "Pourquoi ph et th ne se prononcent-ils pas comme en français ou en anglais ?"],
          "rule": "Le lao oppose des consonnes sans souffle (k, t, p, comme en français) et avec souffle (kh, th, ph : on ajoute un petit « h »). Ce souffle change le sens. ph n'est jamais « f » et th n'est jamais le « th » anglais."},
 "co": "le souffle au début des mots ຄົນ, ທາງ, ພູ.",
 "ant": [("Tu es de quel pays ?", "ເຈົ້າ|ແມ່ນ|ຄົນ|ປະເທດ|ໃດ|?"), ("Je suis française.", "ຂ້ອຍ|ແມ່ນ|ຄົນຝຣັ່ງ|."), ("Je viens de Paris.", "ຂ້ອຍ|ມາແຕ່|ປາຣີ|."),
         ("Tu habites où ?", "ເຈົ້າ|ຢູ່|ໃສ|?"), ("J'habite à Vientiane.", "ຂ້ອຍ|ຢູ່|ວຽງຈັນ|."), ("Un petit peu.", "ໜ້ອຍ|ໜຶ່ງ|.")],
 "rp": ("S", "ເຈົ້າ|ແມ່ນ|ຄົນ|ປະເທດ|ໃດ|?", "Tu es de quel pays ?"),
 "ee": ["Écris 3 phrases sur toi : nationalité, ville d'origine, ville où tu habites.", "Écris les questions qui correspondent à ces 3 phrases."],
 "task": "Présente-toi complètement (prénom, nationalité, origine, lieu de vie) à un locuteur lao.",
},
{
 "n": 4, "title": "ng, ny et les pronoms",
 "obj": "Parler de toi, de l'autre et d'un tiers en choisissant le bon pronom selon la personne.",
 "scene": "Kèo, le petit frère de Noy, arrive.",
 "dia": [
  ("N", "ຄລາຣາ|,|ນີ້|ແມ່ນ|ນ້ອງຊາຍ|ຂອງ|ຂ້ອຍ|.", "Clara, voici mon petit frère."),
  ("K", "ສະບາຍດີ|ເອື້ອຍ|!", "Salut grande sœur !"),
  ("C", "ສະບາຍດີ|ນ້ອງ|.|ນ້ອງ|ຊື່|ຫຍັງ|?", "Salut. Comment tu t'appelles ?"),
  ("K", "ຂ້ອຍ|ຊື່|ແກ້ວ|.|ເອື້ອຍ|ເວົ້າລາວ|ໄດ້|ບໍ|?", "Je m'appelle Kèo. Tu parles lao ?"),
  ("C", "ໄດ້|ໜ້ອຍ|ໜຶ່ງ|.|ພວກເຈົ້າ|ເວົ້າ|ພາສາຝຣັ່ງ|ໄດ້|ບໍ|?", "Un peu. Et vous, vous parlez français ?"),
  ("N", "ຂ້ອຍ|ໄດ້|ໜ້ອຍ|ໜຶ່ງ|.|ແກ້ວ|ບໍ່|ໄດ້|.", "Moi un peu. Kèo, non."),
  ("K", "ແຕ່|ເຮົາ|ເວົ້າ|ພາສາອັງກິດ|ໄດ້|ເດີ|!", "Mais moi, je parle anglais, hein !"),
  ("C", "ເກັ່ງ|ແທ້|!", "Bravo !"),
 ],
 "ce": [("Qui est Kèo pour Noy ?", "Son petit frère : ນ້ອງຊາຍ."), ("Comment Kèo appelle-t-il Clara ?", "ເອື້ອຍ — grande sœur, car elle est plus âgée."), ("Quelle langue parle Kèo ?", "L'anglais.")],
 "voc": [("ຂ້ອຍ", "je", "neutre"), ("ເຈົ້າ", "tu, vous", "poli"), ("ລາວ", "il, elle", "neutre"), ("ພວກເຮົາ", "nous", ""), ("ເຮົາ", "je, nous", "familier, entre proches"),
         ("ພວກເຈົ້າ", "vous (pluriel)", ""), ("ພວກລາວ", "ils, elles", ""), ("ເອື້ອຍ", "grande sœur ; toi (femme plus âgée)", "terme d'adresse"),
         ("ນ້ອງ", "cadet(te) ; toi (plus jeune)", "terme d'adresse"), ("ອ້າຍ", "grand frère ; toi (homme plus âgé)", "terme d'adresse"),
         ("ນ້ອງຊາຍ", "petit frère", ""), ("ໄດ້", "pouvoir, savoir faire", "après le verbe : ເວົ້າລາວໄດ້")],
 "cult": "Au lieu de « tu », on utilise très souvent un terme de parenté selon l'âge : ອ້າຍ, ເອື້ອຍ pour quelqu'un de plus âgé, ນ້ອງ pour quelqu'un de plus jeune. Les pronoms ກູ et ມຶງ existent mais sont très familiers, voire vulgaires : à comprendre, pas à utiliser.",
 "gram": {"t": "pronoms et termes d'adresse", "ex": [("ເອື້ອຍ|ເວົ້າລາວ|ໄດ້|ບໍ|?", "tu (grande sœur) parles lao ?"), ("ນ້ອງ|ຊື່|ຫຍັງ|?", "tu (le petit) t'appelles comment ?"), ("ລາວ|ແມ່ນ|ຄົນລາວ", "il est lao"), ("ພວກເຮົາ|ຢູ່|ວຽງຈັນ", "nous habitons à Vientiane")],
          "q": ["Comment Clara dit-elle « tu » à Kèo ? Pourquoi ?", "Le verbe change-t-il avec le pronom ?"],
          "rule": "Les pronoms lao dépendent de la relation et de l'âge. Le plus naturel est souvent un terme de parenté (ອ້າຍ, ເອື້ອຍ, ນ້ອງ) utilisé comme « tu » ou « je ». ເຈົ້າ est poli et neutre. Le verbe ne change jamais."},
 "co": "le son ng en début de mot et le son ny (comme « gn » d'agneau) dans ນ້ອງ et ຫຍັງ.",
 "ant": [("Tu parles lao ? (à un aîné, homme)", "ອ້າຍ|ເວົ້າລາວ|ໄດ້|ບໍ|?"), ("Je parle un peu lao.", "ຂ້ອຍ|ເວົ້າລາວ|ໄດ້|ໜ້ອຍ|ໜຶ່ງ|."),
         ("Il est lao.", "ລາວ|ແມ່ນ|ຄົນລາວ|."), ("Nous habitons à Vientiane.", "ພວກເຮົາ|ຢູ່|ວຽງຈັນ|."), ("Voici mon petit frère.", "ນີ້|ແມ່ນ|ນ້ອງຊາຍ|ຂອງ|ຂ້ອຍ|."), ("Bravo !", "ເກັ່ງ|ແທ້|!")],
 "rp": ("K", "ເອື້ອຍ|ເວົ້າລາວ|ໄດ້|ບໍ|?", "Tu parles lao ?"),
 "ee": ["Pour chaque personne, choisis le bon terme d'adresse : un homme de 40 ans, une fille de 10 ans, une femme de 30 ans.", "Écris 4 phrases avec ຂ້ອຍ, ລາວ, ພວກເຮົາ, ພວກເຂົາ."],
 "task": "Présente un membre de ta famille ou un ami à un locuteur lao, en utilisant le bon terme d'adresse.",
},
{
 "n": 5, "title": "Bilan sons et tons · Questions oui/non",
 "obj": "Poser et répondre à des questions fermées (oui/non, déjà/pas encore) et tenir un petit échange.",
 "scene": "Mme Boua accueille Clara à midi.",
 "dia": [
  ("B", "ຄລາຣາ|ກິນເຂົ້າ|ແລ້ວ|ບໍ|?", "Clara, tu as mangé ?"),
  ("C", "ຍັງ|ເທື່ອ|ເຈົ້າ|.", "Pas encore."),
  ("B", "ມາ|ກິນເຂົ້າ|ນຳ|ກັນ|ເດີ|!", "Viens manger avec nous !"),
  ("C", "ໄດ້|ບໍ|?|ຂອບໃຈ|ຫຼາຍໆ|.", "C'est vrai ? Merci beaucoup."),
  ("B", "ກິນ|ເຂົ້າໜຽວ|ເປັນ|ບໍ|?", "Tu sais manger le riz gluant ?"),
  ("C", "ເປັນ|ເຈົ້າ|.|ແຊບ|ຫຼາຍ|!", "Oui. C'est très bon !"),
  ("B", "ເຜັດ|ບໍ|?", "C'est trop pimenté ?"),
  ("C", "ບໍ່|ເຜັດ|.|ພໍດີ|.", "Non, c'est parfait."),
 ],
 "ce": [("Clara a-t-elle déjà mangé ?", "Non : ຍັງ « pas encore »."), ("Que propose Mme Boua ?", "De manger avec eux."), ("Que pense Clara du repas ?", "ແຊບຫຼາຍ — très bon, et pas trop pimenté.")],
 "voc": [("ບໍ", "? (question oui/non)", "en fin de phrase, ton montant"), ("ບໍ່", "ne… pas", "devant le verbe, ton bas"), ("ແລ້ວ|ບໍ", "déjà ? (c'est fait ?)", ""),
         ("ຍັງ", "pas encore ; encore", ""), ("ແມ່ນ|ບໍ", "c'est vrai ? n'est-ce pas ?", ""), ("ກິນເຂົ້າ", "manger (litt. manger du riz)", ""),
         ("ເຂົ້າໜຽວ", "riz gluant", "le riz de base au Laos"), ("ແຊບ", "bon (au goût)", ""), ("ເຜັດ", "pimenté", ""), ("ພໍດີ", "juste bien, parfait", ""),
         ("ເປັນ", "savoir faire (une habileté)", "ກິນເຂົ້າໜຽວເປັນ = savoir en manger"), ("ນຳກັນ", "ensemble", "[À VÉRIFIER]")],
 "gram": {"t": "les questions fermées", "ex": [("ກິນເຂົ້າ|ແລ້ວ|ບໍ|?", "tu as (déjà) mangé ?"), ("ກິນ|ແລ້ວ", "oui, j'ai mangé"), ("ຍັງ", "pas encore"), ("ແຊບ|ບໍ|?", "c'est bon ?"), ("ບໍ່|ເຜັດ", "ce n'est pas pimenté")],
          "q": ["Comment répond-on « oui » à une question ? Y a-t-il un mot « oui » ?", "Quelle différence entre ບໍ et ບໍ່ ?"],
          "rule": "Pour poser une question oui/non, on ajoute ບໍ (ton montant) en fin de phrase. Pour répondre oui, on répète le verbe (ແຊບ, ກິນແລ້ວ) ; pour répondre non, on met ບໍ່ (ton bas) devant le verbe. ແລ້ວບໍ demande si c'est déjà fait, et on répond ແລ້ວ ou ຍັງ."},
 "co": "la différence entre ບໍ (montant, question) et ບໍ່ (bas, négation).",
 "ant": [("Tu as mangé ?", "ກິນເຂົ້າ|ແລ້ວ|ບໍ|?"), ("Pas encore.", "ຍັງ|ເທື່ອ|."), ("C'est bon ?", "ແຊບ|ບໍ|?"), ("C'est très bon !", "ແຊບ|ຫຼາຍ|!"),
         ("Ce n'est pas pimenté.", "ບໍ່|ເຜັດ|."), ("C'est vrai ?", "ແມ່ນ|ບໍ|?")],
 "rp": ("B", "ຄລາຣາ|ກິນເຂົ້າ|ແລ້ວ|ບໍ|?", "Clara, tu as mangé ?"),
 "ee": ["Transforme en question : ລາວແມ່ນຄົນລາວ / ເຈົ້າກິນເຂົ້າແລ້ວ / ອາຫານແຊບ.", "Réponds non à chaque question."],
 "task": "Tiens un échange de 2 minutes avec un locuteur lao : salutations, présentation, et au moins 3 questions oui/non.",
},
]
