# Partie G · Maîtriser (C1), leçons 116 à 140. Partie la plus sensible : tout est à valider par un enseignant natif.
def L(n, title, obj, scene, dia, ce, voc, gt, gex, gq, grule, co, ant, ee, task, cult=None):
    d = {"n": n, "title": title, "obj": obj, "scene": scene, "dia": dia, "ce": ce, "voc": voc,
         "gram": {"t": gt, "ex": gex, "q": gq, "rule": grule}, "co": co, "ant": ant, "ee": ee, "task": task}
    if cult:
        d["cult"] = cult
    return d

LESSONS = [
L(116, "Le registre soutenu", "Transformer un message familier en message officiel.", "Clara doit écrire au directeur.",
  [("C", "ຂ້ອຍ|ຢາກ|ພັກ|ມື້ອື່ນ|.", "(familier) Je veux prendre congé demain."),
   ("N", "ຂຽນ|ໃຫ້|ສຸພາບ|ກວ່າ|ນີ້|.", "Écris-le plus poliment."),
   ("C", "ຂ້າພະເຈົ້າ|ຂໍ|ອະນຸຍາດ|ລາພັກ|ໃນ|ວັນ|ພະຫັດ|.", "(soutenu) Je sollicite l'autorisation de m'absenter jeudi."),
   ("N", "ດີ|ຫຼາຍ|.|ແບບ|ນີ້|ຖືກຕ້ອງ|.", "Très bien. Comme ça, c'est correct.")],
  [("Quelle différence entre les deux phrases ?", "Le registre : ຂ້ອຍ → ຂ້າພະເຈົ້າ, ຢາກພັກ → ຂໍອະນຸຍາດລາພັກ.")],
  [("ຂ້າພະເຈົ້າ", "je (soutenu)"), ("ທ່ານ", "vous (soutenu)"), ("ລາພັກ", "prendre congé (soutenu)"), ("ສຸພາບ", "poli"), ("ຖືກຕ້ອງ", "correct"), ("ຄຳ|ສັບ|ສູງ", "vocabulaire soutenu"),
   ("ພາສາ|ປາກ", "langue parlée"), ("ພາສາ|ຂຽນ", "langue écrite")],
  "passer du familier au soutenu", [("ຂ້ອຍ|→|ຂ້າພະເຈົ້າ", "je"), ("ເຈົ້າ|→|ທ່ານ", "vous"), ("ກິນ|→|ຮັບປະທານ", "manger (soutenu)")],
  [], "Le registre soutenu remplace les mots courants par des équivalents savants, souvent d'origine pali-sanskrite. [Toute la leçon À VÉRIFIER avec un enseignant]",
  "les mots soutenus.",
  [("Je sollicite l'autorisation…", "ຂ້າພະເຈົ້າ|ຂໍ|ອະນຸຍາດ|…"), ("Écris-le plus poliment.", "ຂຽນ|ໃຫ້|ສຸພາບ|ກວ່າ|ນີ້|.")],
  ["Réécris 5 phrases familières en registre soutenu."], "Fais corriger tes transformations par un enseignant natif."),
L(117, "Le registre religieux", "Comprendre le vocabulaire d'une cérémonie bouddhiste.", "Une cérémonie au temple.",
  [("B", "ມື້ນີ້|ມີ|ພິທີ|ທຳບຸນ|ທີ່|ວັດ|.", "Aujourd'hui, il y a une cérémonie de mérites au temple."),
   ("B", "ພະສົງ|ຈະ|ສູດ|ມົນ|.", "Les moines vont réciter des prières."),
   ("C", "ຂ້ອຍ|ຕ້ອງ|ເຮັດ|ແນວໃດ|?", "Que dois-je faire ?"),
   ("B", "ນັ່ງ|ພະນົມມື|ແລະ|ຟັງ|ຢ່າງ|ສະຫງົບ|.", "Assieds-toi les mains jointes et écoute calmement.")],
  [("Que font les moines ?", "Ils récitent des prières."), ("Que doit faire Clara ?", "S'asseoir mains jointes et écouter.")],
  [("ພິທີ", "cérémonie"), ("ສູດ|ມົນ", "réciter des prières"), ("ພະນົມມື", "joindre les mains"), ("ສະຫງົບ", "calme, paisible"), ("ສິນ", "préceptes"), ("ທຳ", "dharma"),
   ("ກຳ", "karma"), ("ບຸນ", "mérite")],
  "le vocabulaire du bouddhisme", [("ທຳບຸນ", "faire des mérites"), ("ຮັກສາ|ສິນ", "observer les préceptes")],
  [], "Le vocabulaire religieux emprunte au pali. Certains verbes changent quand le sujet est un moine. [À VÉRIFIER entièrement avec un pratiquant]",
  "le rythme des prières.",
  [("Que dois-je faire ?", "ຂ້ອຍ|ຕ້ອງ|ເຮັດ|ແນວໃດ|?"), ("Les moines récitent.", "ພະສົງ|ສູດ|ມົນ|.")],
  ["Explique les mots ບຸນ, ກຳ, ທຳ, ສິນ en lao simple."], "Assiste à une cérémonie (temple lao en France) et note 10 mots entendus."),
L(118, "Le baci (discours)", "Prononcer des vœux lors d'un baci.", "Baci pour le départ de Clara en France.",
  [("S", "ມື້ນີ້|ພວກເຮົາ|ມາ|ຮ່ວມ|ກັນ|ສູ່ຂວັນ|ໃຫ້|ຄລາຣາ|.", "Aujourd'hui, nous sommes réunis pour le baci de Clara."),
   ("B", "ຂໍ|ໃຫ້|ເດີນທາງ|ປອດໄພ|,|ມີ|ສຸຂະພາບ|ແຂງແຮງ|.", "Que ton voyage soit sûr, que tu sois en bonne santé."),
   ("C", "ຂອບໃຈ|ທຸກ|ຄົນ|ທີ່|ອວຍພອນ|ໃຫ້|ຂ້ອຍ|.", "Merci à tous pour vos bénédictions.")],
  [("Pourquoi ce baci ?", "Le départ de Clara."), ("Quels vœux fait Mme Boua ?", "Un voyage sûr et une bonne santé.")],
  [("ສູ່ຂວັນ", "cérémonie d'appel des âmes (baci)"), ("ຂວັນ", "âme vitale"), ("ເດີນທາງ", "voyager"), ("ປອດໄພ", "en sécurité"), ("ອວຍພອນ", "bénir, souhaiter"), ("ຜູກແຂນ", "nouer les fils")],
  "les vœux cérémoniels", [("ຂໍ|ໃຫ້|…", "que…"), ("ຂໍ|ໃຫ້|ຂວັນ|ມາ|ຢູ່|ກັບ|ເນື້ອ|ກັບ|ໂຕ", "que les âmes reviennent dans le corps [À VÉRIFIER]")],
  [], "Le baci rappelle les ຂວັນ (âmes vitales) dans le corps. On noue un fil au poignet en formulant un vœu avec ຂໍໃຫ້. [Formules À VÉRIFIER]",
  "les formules répétées.",
  [("Que ton voyage soit sûr.", "ຂໍ|ໃຫ້|ເດີນທາງ|ປອດໄພ|."), ("Merci pour vos bénédictions.", "ຂອບໃຈ|ທີ່|ອວຍພອນ|.")],
  ["Écris 5 vœux de baci pour des occasions différentes."], "Participe à un baci et formule un vœu en lao."),
L(119, "Mariages", "Comprendre et participer à un mariage lao.", "Mariage de Noy.",
  [("C", "ຍິນດີ|ນຳ|ເຈົ້າບ່າວ|ເຈົ້າສາວ|!", "Félicitations aux mariés !"),
   ("N", "ຂອບໃຈ|ຫຼາຍໆ|ທີ່|ມາ|ຮ່ວມ|ງານ|.", "Merci beaucoup d'être venue."),
   ("C", "ຂໍ|ໃຫ້|ຮັກ|ກັນ|ຕະຫຼອດ|ໄປ|.", "Que vous vous aimiez pour toujours.")],
  [("Que souhaite Clara ?", "Qu'ils s'aiment pour toujours.")],
  [("ງານ|ແຕ່ງງານ", "mariage (fête)"), ("ເຈົ້າບ່າວ", "marié"), ("ເຈົ້າສາວ", "mariée"), ("ຍິນດີ|ນຳ", "félicitations"), ("ຕະຫຼອດ|ໄປ", "pour toujours"), ("ຂອງຂວັນ", "cadeau"),
   ("ສິນສອດ", "dot", "[À VÉRIFIER]")],
  "féliciter", [("ຍິນດີ|ນຳ|…", "félicitations à…"), ("ຂໍ|ໃຫ້|…|ຕະຫຼອດ|ໄປ", "que… pour toujours")],
  [], "ຍິນດີນຳ = félicitations. Au mariage, on offre souvent de l'argent dans une enveloppe. [Usages À VÉRIFIER]",
  "les formules de félicitations.",
  [("Félicitations aux mariés !", "ຍິນດີ|ນຳ|ເຈົ້າບ່າວ|ເຈົ້າສາວ|!"), ("Pour toujours.", "ຕະຫຼອດ|ໄປ|.")],
  ["Écris un message de félicitations pour un mariage."], "Demande à un natif comment se passe un mariage lao, étape par étape."),
L(120, "Funérailles", "Présenter tes condoléances avec tact.", "Le grand-père d'un collègue est décédé.",
  [("C", "ຂໍ|ສະແດງ|ຄວາມ|ເສຍໃຈ|ນຳ|.", "Je vous présente mes condoléances."),
   ("X", "ຂອບໃຈ|ທີ່|ມາ|.", "Merci d'être venue."),
   ("C", "ຂໍ|ໃຫ້|ດວງ|ວິນຍານ|ໄປ|ສູ່|ສຸຄະຕິ|.", "Que son âme repose en paix. [À VÉRIFIER]")],
  [("Quelle formule utilise Clara ?", "ຂໍສະແດງຄວາມເສຍໃຈນຳ.")],
  [("ຂໍ|ສະແດງ|ຄວາມ|ເສຍໃຈ|ນຳ", "mes condoléances"), ("ເສຍຊີວິດ", "décéder"), ("ງານ|ສົບ", "funérailles", "[À VÉRIFIER]"), ("ດວງ|ວິນຍານ", "âme"), ("ສຸຄະຕິ", "le paradis (bonne destinée)", "[À VÉRIFIER]")],
  "le langage du deuil", [("ເສຍຊີວິດ", "décéder (respectueux)"), ("ຂໍ|ສະແດງ|ຄວາມ|ເສຍໃຈ", "condoléances")],
  [], "On évite ຕາຍ (mourir) pour une personne : on dit ເສຍຊີວິດ. Les funérailles durent plusieurs jours, avec des moines. [À VÉRIFIER]",
  "le ton grave et lent.",
  [("Mes condoléances.", "ຂໍ|ສະແດງ|ຄວາມ|ເສຍໃຈ|ນຳ|."), ("Merci d'être venu.", "ຂອບໃຈ|ທີ່|ມາ|.")],
  ["Écris un message de condoléances court et sobre."], "Demande à un natif les usages lors des funérailles."),
L(121, "Les proverbes (1)", "Comprendre et utiliser quelques proverbes.", "M. Somsak cite un proverbe.",
  [("S", "ນ້ຳ|ຂຶ້ນ|ໃຫ້|ຮີບ|ຕັກ|.", "Quand l'eau monte, dépêche-toi de puiser. [À VÉRIFIER]"),
   ("C", "ໝາຍ|ຄວາມ|ວ່າ|ແນວໃດ|?", "Ça veut dire quoi ?"),
   ("S", "ໝາຍ|ຄວາມ|ວ່າ|ຕ້ອງ|ຮູ້ຈັກ|ໃຊ້|ໂອກາດ|.", "Ça veut dire qu'il faut saisir les occasions."),
   ("C", "ພາສາຝຣັ່ງ|ກໍ|ມີ|ຄຳ|ຄ້າຍ|ກັນ|.", "En français, il y a une expression proche.")],
  [("Que signifie le proverbe ?", "Il faut saisir les occasions (battre le fer tant qu'il est chaud).")],
  [("ສຸພາສິດ", "proverbe"), ("ຄຳ|ສຸພາສິດ", "proverbe"), ("ໂອກາດ", "occasion"), ("ຮີບ", "se dépêcher"), ("ຕັກ", "puiser"), ("ຄຳ|ສອນ", "enseignement")],
  "comprendre un proverbe", [("ໝາຍ|ຄວາມ|ວ່າ|…", "ça veut dire que…"), ("ຄ້າຍ|ກັບ|…|ໃນ|ພາສາຝຣັ່ງ", "ça ressemble à… en français")],
  [], "Les proverbes lao reposent sur des images de la nature et de la vie rurale. [Les proverbes de cette leçon sont À VÉRIFIER : collecte-les auprès d'un natif]",
  "le rythme des proverbes.",
  [("Ça veut dire quoi ?", "ໝາຍ|ຄວາມ|ວ່າ|ແນວໃດ|?"), ("Il faut saisir les occasions.", "ຕ້ອງ|ໃຊ້|ໂອກາດ|.")],
  ["Collecte 10 proverbes auprès d'un natif et explique-les en lao."], "Demande à un aîné lao ses 5 proverbes préférés."),
L(122, "Les proverbes (2)", "Placer un proverbe au bon moment dans une conversation.", "Kèo se décourage.",
  [("K", "ຂ້ອຍ|ຮຽນ|ບໍ່|ເກັ່ງ|ຈັກ|ເທື່ອ|.", "Je n'arrive jamais à être bon."),
   ("S", "ຄ່ອຍ|ໆ|ເປັນ|ຄ່ອຍ|ໆ|ໄປ|.", "Petit à petit, ça vient."),
   ("K", "ແມ່ນ|ແລ້ວ|ພໍ່|.", "Tu as raison, papa.")],
  [("Quel conseil donne M. Somsak ?", "Avancer petit à petit.")],
  [("ຄ່ອຍ|ໆ", "petit à petit, doucement"), ("ທໍ້ໃຈ", "se décourager"), ("ອົດທົນ", "patienter, persévérer"), ("ຄວາມ|ພະຍາຍາມ", "l'effort")],
  "glisser une sagesse", [("ຄ່ອຍ|ໆ|ເປັນ|ຄ່ອຍ|ໆ|ໄປ", "petit à petit [À VÉRIFIER]")],
  [], "On place un proverbe pour conclure, consoler ou conseiller, souvent avec un ton calme. Évite de les enchaîner.",
  "le moment où le proverbe arrive.",
  [("Petit à petit.", "ຄ່ອຍ|ໆ|."), ("Ne te décourage pas.", "ຢ່າ|ທໍ້ໃຈ|.")],
  ["Écris 3 mini-dialogues qui finissent par un proverbe."], "Utilise un proverbe à bon escient dans une vraie conversation."),
L(123, "Les contes", "Raconter un conte traditionnel.", "Mme Boua raconte un conte à son petit-enfant.",
  [("B", "ໃນ|ສະໄໝ|ກ່ອນ|,|ມີ|ຊາວນາ|ຜູ້|ໜຶ່ງ|…", "Il était une fois un paysan…"),
   ("B", "ມື້|ໜຶ່ງ|ລາວ|ພົບ|ກະຕ່າຍ|ໂຕ|ໜຶ່ງ|.", "Un jour, il rencontra un lièvre."),
   ("B", "ນິທານ|ເລື່ອງ|ນີ້|ສອນ|ໃຫ້|ຮູ້|ວ່າ|…", "Ce conte nous apprend que…")],
  [("Comment commence le conte ?", "ໃນສະໄໝກ່ອນ… — il était une fois.")],
  [("ນິທານ", "conte"), ("ໃນ|ສະໄໝ|ກ່ອນ", "il était une fois"), ("ຜູ້|ໜຶ່ງ", "un (personnage)"), ("ກະຕ່າຍ", "lièvre"), ("ສອນ|ໃຫ້|ຮູ້|ວ່າ", "nous apprend que"), ("ຊຽງໝ້ຽງ", "Xieng Mieng (héros rusé)", "[À VÉRIFIER]")],
  "la langue du conte", [("ໃນ|ສະໄໝ|ກ່ອນ|…", "il était une fois…"), ("ນິທານ|ເລື່ອງ|ນີ້|ສອນ|ໃຫ້|ຮູ້|ວ່າ|…", "la morale est…")],
  [], "Les contes ont une ouverture (ໃນສະໄໝກ່ອນ), des personnages types (le rusé Xieng Mieng, les animaux) et une morale finale.",
  "les formules d'ouverture et de morale.",
  [("Il était une fois…", "ໃນ|ສະໄໝ|ກ່ອນ|…"), ("Ce conte nous apprend que…", "ນິທານ|ເລື່ອງ|ນີ້|ສອນ|ໃຫ້|ຮູ້|ວ່າ|…")],
  ["Raconte un conte français en lao (15 phrases)."], "Demande à un aîné de te raconter un conte de Xieng Mieng, puis raconte-le à ton tour."),
L(124, "La poésie", "Lire et comprendre un poème court.", "Clara découvre un poème lao.",
  [("C", "ກອນ|ລາວ|ມີ|ສຳຜັດ|ບໍ|?", "La poésie lao a des rimes ?"),
   ("N", "ມີ|.|ສຳຜັດ|ລະຫວ່າງ|ວັກ|.", "Oui. Des rimes entre les vers."),
   ("C", "ອ່ານ|ໃຫ້|ຟັງ|ແດ່|.", "Lis-le-moi.")],
  [("Y a-t-il des rimes en poésie lao ?", "Oui, entre les vers.")],
  [("ກອນ", "poème, vers"), ("ສຳຜັດ", "rime", "[À VÉRIFIER]"), ("ວັກ", "vers, syllabe", "[À VÉRIFIER]"), ("ນັກ|ກະວີ", "poète"), ("ຈັງຫວະ", "rythme")],
  "rimes et rythme", [("ສຳຜັດ", "rime"), ("ຈັງຫວະ", "rythme")],
  [], "La poésie lao repose sur des rimes internes et un rythme syllabique précis. [Règles À VÉRIFIER avec un enseignant]",
  "le rythme des vers.",
  [("Lis-le-moi.", "ອ່ານ|ໃຫ້|ຟັງ|ແດ່|."), ("C'est très beau.", "ງາມ|ຫຼາຍ|.")],
  ["Recopie et traduis un poème lao court."], "Lis un poème lao à voix haute devant un natif."),
L(125, "Les chants traditionnels", "Comprendre le lam, chant alterné accompagné au khène.", "Fête de village avec un mo lam.",
  [("S", "ໝໍລຳ|ກຳລັງ|ລຳ|ໂຕ້|ຕອບ|ກັນ|.", "Les chanteurs de lam se répondent."),
   ("C", "ເຂົາ|ຮ້ອງ|ກ່ຽວກັບ|ຫຍັງ|?", "Ils chantent sur quoi ?"),
   ("S", "ກ່ຽວກັບ|ຄວາມ|ຮັກ|,|ແຊວ|ກັນ|ມ່ວນ|ໆ|.", "L'amour, ils se taquinent gentiment.")],
  [("Comment chantent les mo lam ?", "Ils se répondent (chant alterné).")],
  [("ລຳ", "lam (chant)"), ("ໝໍລຳ", "chanteur de lam"), ("ແຄນ", "khène (orgue à bouche)"), ("ໂຕ້|ຕອບ", "se répondre"), ("ແຊວ", "taquiner")],
  "le chant alterné", [("ລຳ|ໂຕ້|ຕອບ", "chant en réponse")],
  [], "Le lam est un chant improvisé accompagné au khène, souvent en joute entre un homme et une femme. La langue y est imagée et pleine de double sens.",
  "la mélodie du lam qui suit les tons.",
  [("Ils se répondent.", "ໂຕ້|ຕອບ|ກັນ|."), ("Ils chantent sur quoi ?", "ຮ້ອງ|ກ່ຽວກັບ|ຫຍັງ|?")],
  ["Écoute un lam et transcris 4 vers."], "Écoute un lam avec un natif et fais-toi expliquer les images."),
L(126, "La littérature moderne", "Commenter un extrait de roman ou de nouvelle.", "Club de lecture.",
  [("N", "ເຈົ້າ|ອ່ານ|ນະວະນິຍາຍ|ເລື່ອງ|ນີ້|ຈົບ|ແລ້ວ|ບໍ|?", "Tu as fini ce roman ?"),
   ("C", "ຈົບ|ແລ້ວ|.|ຕົວລະຄອນ|ຫຼັກ|ເລິກ|ຫຼາຍ|.", "Oui. Le personnage principal est très profond."),
   ("N", "ຜູ້|ຂຽນ|ຕ້ອງການ|ສື່|ຫຍັງ|?", "Que veut transmettre l'auteur ?")],
  [("Que pense Clara du personnage ?", "Il est très profond.")],
  [("ນະວະນິຍາຍ", "roman"), ("ເລື່ອງ|ສັ້ນ", "nouvelle"), ("ຜູ້|ຂຽນ", "auteur"), ("ເລິກ", "profond"), ("ສື່", "transmettre"), ("ແນວ|ຄິດ", "idée, pensée")],
  "commenter un texte", [("ຜູ້|ຂຽນ|ຕ້ອງການ|ສື່|…", "l'auteur veut transmettre…")],
  [], "Commenter : thème, personnages, intention de l'auteur (ຜູ້ຂຽນຕ້ອງການສື່), ton avis argumenté.",
  "le vocabulaire littéraire.",
  [("Que veut transmettre l'auteur ?", "ຜູ້|ຂຽນ|ຕ້ອງການ|ສື່|ຫຍັງ|?"), ("Le personnage est profond.", "ຕົວລະຄອນ|ເລິກ|.")],
  ["Commente un extrait de littérature lao en 200 mots."], "Lis une nouvelle lao et discutes-en avec un natif."),
L(127, "L'écrit administratif", "Rédiger une lettre officielle complète.", "Clara écrit à un ministère.",
  [("C", "ສາທາລະນະລັດ|ປະຊາທິປະໄຕ|ປະຊາຊົນ|ລາວ|…", "République démocratique populaire lao… (en-tête)"),
   ("C", "ເລື່ອງ|:|ຂໍ|ອະນຸຍາດ|ເຮັດ|ການ|ຄົ້ນຄວ້າ|.", "Objet : demande d'autorisation de recherche."),
   ("C", "ຈຶ່ງ|ຮຽນ|ມາ|ເພື່ອ|ພິຈາລະນາ|.", "Je vous soumets donc cette demande pour examen.")],
  [("Quel est l'objet de la lettre ?", "Une demande d'autorisation de recherche.")],
  [("ສາທາລະນະລັດ", "république"), ("ເລື່ອງ", "objet (lettre)"), ("ພິຈາລະນາ", "examiner"), ("ຄົ້ນຄວ້າ", "recherche"), ("ຈຶ່ງ|ຮຽນ|ມາ", "je vous soumets donc")],
  "les conventions officielles", [("ເລື່ອງ|:|…", "objet :"), ("ຈຶ່ງ|ຮຽນ|ມາ|ເພື່ອ|ພິຈາລະນາ", "formule finale")],
  [], "Une lettre officielle lao a un en-tête fixe (nom du pays, devise), un objet (ເລື່ອງ), et des formules finales figées. [À VÉRIFIER avec un modèle officiel]",
  "les formules figées.",
  [("Objet : demande d'autorisation.", "ເລື່ອງ|:|ຂໍ|ອະນຸຍາດ|."), ("Pour examen.", "ເພື່ອ|ພິຈາລະນາ|.")],
  ["Rédige une lettre officielle complète."], "Fais relire ta lettre officielle par un natif ayant travaillé dans l'administration."),
L(128, "Le discours public", "Prononcer un discours de 10 minutes.", "Clara fait un discours de remerciement.",
  [("C", "ຮຽນ|ທ່ານ|ປະທານ|,|ທ່ານ|ແຂກ|ທີ່|ນັບຖື|.", "Monsieur le président, chers invités."),
   ("C", "ຂ້າພະເຈົ້າ|ມີ|ຄວາມ|ຍິນດີ|ເປັນ|ຢ່າງ|ຍິ່ງ|ທີ່|ໄດ້|ມາ|ຢູ່|ນີ້|.", "C'est un très grand plaisir pour moi d'être ici."),
   ("C", "ສຸດທ້າຍ|ນີ້|,|ຂໍ|ຂອບໃຈ|ທຸກ|ທ່ານ|.", "Pour finir, je remercie chacun d'entre vous.")],
  [("Comment commence le discours ?", "Par les salutations protocolaires.")],
  [("ທ່ານ|ປະທານ", "monsieur le président"), ("ແຂກ", "invité"), ("ເປັນ|ຢ່າງ|ຍິ່ງ", "extrêmement"), ("ສຸດທ້າຍ|ນີ້", "pour finir"), ("ກ່າວ|ຄຳ|ປາໄສ", "prononcer un discours")],
  "la rhétorique", [("ຮຽນ|ທ່ານ|…", "salutation protocolaire"), ("…|ເປັນ|ຢ່າງ|ຍິ່ງ", "intensif soutenu")],
  [], "Un discours public suit un protocole : saluer par rang, remercier, développer, conclure. Les intensifs soutenus (ເປັນຢ່າງຍິ່ງ) remplacent ຫຼາຍ.",
  "le rythme lent et posé.",
  [("Chers invités.", "ທ່ານ|ແຂກ|ທີ່|ນັບຖື|."), ("Pour finir, merci à tous.", "ສຸດທ້າຍ|ນີ້|,|ຂໍ|ຂອບໃຈ|ທຸກ|ທ່ານ|.")],
  ["Écris un discours de 10 minutes pour une occasion de ton choix."], "Prononce un discours devant un groupe de natifs."),
L(129, "Interpréter", "Traduire à l'oral entre français et lao.", "Clara interprète pour un touriste français.",
  [("C", "ລາວ|ຖາມ|ວ່າ|ກິນ|ລາບ|ແຊບ|ຢູ່|ໃສ|.", "(Après la question du touriste en français) Il demande où manger un bon larb."),
   ("N", "ບອກ|ລາວ|ໃຫ້|ໄປ|ຮ້ານ|ຂ້າງ|ຕະຫຼາດ|.", "Dis-lui d'aller au restaurant à côté du marché.")],
  [("Que demande le touriste ?", "Où manger un bon larb.")],
  [("ແປ", "traduire"), ("ນາຍ|ແປ", "interprète"), ("ແປ|ພາສາ", "traduire une langue"), ("ຖ່າຍທອດ", "transmettre"), ("ຄວາມ|ໝາຍ", "sens")],
  "rapporter pour traduire", [("ລາວ|ຖາມ|ວ່າ|…", "il demande…"), ("ລາວ|ບອກ|ວ່າ|…", "il dit…")],
  [], "En interprétation, on traduit le sens, pas les mots : on reformule souvent au discours rapporté (ລາວຖາມວ່າ…).",
  "le passage d'une langue à l'autre.",
  [("Il demande où…", "ລາວ|ຖາມ|ວ່າ|…|ຢູ່|ໃສ|."), ("Je traduis.", "ຂ້ອຍ|ແປ|ໃຫ້|.")],
  ["Traduis à l'oral 10 phrases françaises en lao, chronométré."], "Sers d'interprète pendant 10 minutes entre un francophone et un natif lao."),
L(130, "Parler aux enfants", "Adapter ta langue à un jeune enfant.", "Clara garde le petit-enfant de Mme Boua.",
  [("C", "ນ້ອງ|ຫິວ|ບໍ|?|ກິນ|ໜົມ|ບໍ|?", "Tu as faim, mon petit ? Tu veux un goûter ?"),
   ("X", "ກິນ|!", "Oui !"),
   ("C", "ເກັ່ງ|ຫຼາຍ|ລູກ|!|ລ້າງ|ມື|ກ່ອນ|ເດີ|.", "Bravo ! Lave-toi les mains d'abord.")],
  [("Que propose Clara ?", "Un goûter, après s'être lavé les mains.")],
  [("ໜົມ", "goûter, gâteau"), ("ນ້ອງ", "toi (à un enfant)"), ("ລູກ", "mon enfant (affectueux)"), ("ເກັ່ງ", "bravo, doué"), ("ນອນ|ສາ", "dodo", "[À VÉRIFIER]")],
  "le registre enfantin", [("ນ້ອງ|ຫິວ|ບໍ|?", "tu as faim, petit ?"), ("ເກັ່ງ|ຫຼາຍ", "bravo")],
  [], "Avec un enfant : phrases courtes, termes affectueux (ນ້ອງ, ລູກ), répétitions et voix douce.",
  "la voix douce et les répétitions.",
  [("Tu as faim, mon petit ?", "ນ້ອງ|ຫິວ|ບໍ|?"), ("Lave-toi les mains.", "ລ້າງ|ມື|ເດີ|.")],
  ["Écris 10 phrases pour s'occuper d'un enfant."], "Parle lao avec un enfant de ta famille pendant 15 minutes."),
L(131, "Parler aux anciens", "Parler avec un grand-parent de l'histoire familiale.", "Clara interroge le grand-père de Noy.",
  [("C", "ພໍ່ຕູ້|,|ເລົ່າ|ເລື່ອງ|ສະໄໝ|ກ່ອນ|ໃຫ້|ຫຼານ|ຟັງ|ແດ່|.", "Grand-père, raconte-moi le temps d'avant."),
   ("X", "ສະໄໝ|ນັ້ນ|ລຳບາກ|ຫຼາຍ|ລູກ|.", "À cette époque, c'était très dur, mon enfant."),
   ("C", "ພໍ່ຕູ້|ເກີດ|ຢູ່|ໃສ|?", "Où es-tu né, grand-père ?")],
  [("Comment Clara se désigne-t-elle ?", "ຫຼານ (le petit-enfant), par respect.")],
  [("ສະໄໝ|ກ່ອນ", "autrefois"), ("ລຳບາກ", "difficile, dur"), ("ເກີດ", "naître"), ("ບັນພະບຸລຸດ", "ancêtres"), ("ຄວາມ|ຊົງ|ຈຳ", "souvenir, mémoire")],
  "la déférence", [("ຫຼານ|ຂໍ|ຖາມ|…", "puis-je (petit-enfant) demander…"), ("ເລົ່າ|ໃຫ້|ຫຼານ|ຟັງ|ແດ່", "raconte-moi")],
  [], "Avec les anciens : se désigner par un terme de parenté inférieur (ຫຼານ, ລູກ), utiliser ເຈົ້າ, ແດ່, et écouter sans interrompre.",
  "le vocabulaire ancien.",
  [("Raconte-moi le temps d'avant.", "ເລົ່າ|ເລື່ອງ|ສະໄໝ|ກ່ອນ|ໃຫ້|ຫຼານ|ຟັງ|ແດ່|."), ("Où es-tu né ?", "ເກີດ|ຢູ່|ໃສ|?")],
  ["Prépare 10 questions pour interviewer un aîné sur sa vie."], "Interviewe un aîné de ta famille en lao pendant 30 minutes et enregistre-le (avec son accord)."),
L(132, "Argot et langue des jeunes", "Comprendre une conversation de jeunes et les réseaux sociaux.", "Kèo et ses amis.",
  [("K", "ມື້ນີ້|ມ່ວນ|ຫຼາຍ|ໂພດ|!", "Aujourd'hui c'était trop bien !"),
   ("X", "ແມ່ນ|ບໍ|,|ຊິ|ໄປ|ອີກ|ບໍ|?", "Grave, on y retourne ?"),
   ("C", "ຂ້ອຍ|ແກ່|ແລ້ວ|ບໍ|?|ບໍ່|ເຂົ້າໃຈ|ຫຍັງ|ເລີຍ|!", "Je suis devenue vieille ? Je ne comprends rien !")],
  [("Pourquoi Clara ne comprend-elle pas ?", "Les jeunes parlent avec leurs propres expressions.")],
  [("ຄຳ|ສະແລງ", "argot [À VÉRIFIER]"), ("ໄວລຸ້ນ", "ados"), ("ແກ່", "vieux"), ("ຊິ", "(futur familier) on va"), ("ຫຼາຍ|ໂພດ", "trop (intensif jeune)", "[À VÉRIFIER]")],
  "le parler jeune", [("ມ່ວນ|ຫຼາຍ|ໂພດ", "trop bien [À VÉRIFIER]"), ("ຊິ|ໄປ|ບໍ|?", "on y va ?")],
  [], "L'argot change vite et varie selon les régions et les réseaux. Cette leçon est forcément À VÉRIFIER avec de jeunes natifs.",
  "les expressions des jeunes.",
  [("Je ne comprends rien !", "ບໍ່|ເຂົ້າໃຈ|ຫຍັງ|ເລີຍ|!"), ("On y va ?", "ຊິ|ໄປ|ບໍ|?")],
  ["Collecte 10 expressions de jeunes Lao sur les réseaux et fais-les expliquer."], "Discute avec de jeunes natifs et note leurs expressions."),
L(133, "Les sciences", "Expliquer un phénomène scientifique simple.", "Kèo prépare un exposé.",
  [("K", "ເປັນຫຍັງ|ຝົນ|ຈຶ່ງ|ຕົກ|?", "Pourquoi pleut-il ?"),
   ("C", "ນ້ຳ|ລະເຫີຍ|ຂຶ້ນ|ໄປ|,|ກາຍ|ເປັນ|ເມກ|,|ແລ້ວ|ກໍ|ຕົກ|ລົງ|ມາ|.", "L'eau s'évapore, devient des nuages, puis retombe."),
   ("K", "ເອີ້ນ|ວ່າ|ວົງຈອນ|ຂອງ|ນ້ຳ|.", "On appelle ça le cycle de l'eau.")],
  [("Comment se forme la pluie ?", "Évaporation, nuages, puis chute.")],
  [("ວິທະຍາສາດ", "science"), ("ລະເຫີຍ", "s'évaporer"), ("ກາຍ|ເປັນ", "devenir"), ("ເມກ", "nuage"), ("ວົງຈອນ", "cycle"), ("ທົດລອງ", "expérimenter")],
  "expliquer un processus", [("…|ກາຍ|ເປັນ|…", "… devient…"), ("ເອີ້ນ|ວ່າ|…", "on appelle cela…")],
  [], "Pour expliquer : étapes (ແລ້ວ, ຈາກນັ້ນ), transformation (ກາຍເປັນ), définition (ເອີ້ນວ່າ).",
  "les étapes du processus.",
  [("L'eau devient des nuages.", "ນ້ຳ|ກາຍ|ເປັນ|ເມກ|."), ("On appelle ça…", "ເອີ້ນ|ວ່າ|…")],
  ["Explique un phénomène scientifique en 10 phrases."], "Explique un phénomène naturel à un natif comme à un enfant."),
L(134, "Le droit et la politique", "Comprendre un texte institutionnel.", "Clara lit un règlement.",
  [("C", "ມາດຕາ|ນີ້|ໝາຍ|ຄວາມ|ວ່າ|ແນວໃດ|?", "Que veut dire cet article ?"),
   ("S", "ມັນ|ກຳນົດ|ສິດ|ແລະ|ໜ້າທີ່|ຂອງ|ພົນລະເມືອງ|.", "Il définit les droits et devoirs des citoyens."),
   ("C", "ພາສາ|ກົດໝາຍ|ຍາກ|ແທ້|.", "Le langage juridique est vraiment difficile.")],
  [("Que définit l'article ?", "Les droits et devoirs des citoyens.")],
  [("ມາດຕາ", "article (de loi)"), ("ກຳນົດ", "définir, fixer"), ("ສິດ", "droit"), ("ໜ້າທີ່", "devoir, fonction"), ("ພົນລະເມືອງ", "citoyen"), ("ກົດໝາຍ", "loi")],
  "le style juridique", [("ກຳນົດ|…", "définit…"), ("ຕ້ອງ|ປະຕິບັດ|ຕາມ", "doit se conformer à")],
  [], "Le style institutionnel est impersonnel et utilise des mots savants. Repère les verbes clés : ກຳນົດ, ປະຕິບັດ, ຫ້າມ, ອະນຸຍາດ.",
  "les mots savants.",
  [("Que veut dire cet article ?", "ມາດຕາ|ນີ້|ໝາຍ|ຄວາມ|ວ່າ|ແນວໃດ|?"), ("Les droits et devoirs.", "ສິດ|ແລະ|ໜ້າທີ່|.")],
  ["Résume un texte institutionnel lao en langage simple."], "Fais-toi expliquer un texte officiel par un natif."),
L(135, "Les affaires", "Mener une réunion de travail.", "Réunion d'équipe dans l'école de Clara.",
  [("C", "ເລີ່ມ|ກອງປະຊຸມ|ເລີຍ|ເດີ|.|ວາລະ|ທຳອິດ|ແມ່ນ|…", "Commençons la réunion. Le premier point est…"),
   ("X", "ຂ້ອຍ|ຂໍ|ສະເໜີ|ຄວາມ|ຄິດເຫັນ|.", "Je voudrais faire une proposition."),
   ("C", "ເຊີນ|.|ສະຫຼຸບ|ແລ້ວ|ເຮົາ|ຕົກລົງ|ກັນ|ວ່າ|…", "Allez-y. En résumé, nous convenons que…")],
  [("Qui dirige la réunion ?", "Clara.")],
  [("ກອງປະຊຸມ", "réunion"), ("ວາລະ", "point de l'ordre du jour"), ("ສະເໜີ", "proposer"), ("ຕົກລົງ|ກັນ", "convenir ensemble"), ("ມອບໝາຍ", "confier une tâche"), ("ກຳນົດ|ເວລາ", "échéance")],
  "animer une réunion", [("ວາລະ|ທຳອິດ|…", "premier point…"), ("ສະຫຼຸບ|ແລ້ວ|…", "en résumé…")],
  [], "Animer : ouvrir, annoncer les points (ວາລະ), donner la parole (ເຊີນ), résumer et attribuer les tâches (ມອບໝາຍ).",
  "les formules de réunion.",
  [("Commençons la réunion.", "ເລີ່ມ|ກອງປະຊຸມ|ເລີຍ|."), ("Allez-y.", "ເຊີນ|."), ("En résumé…", "ສະຫຼຸບ|ແລ້ວ|…")],
  ["Écris l'ordre du jour et le compte rendu d'une réunion."], "Anime une réunion fictive de 20 minutes avec des natifs."),
L(136, "Improvisation (1)", "Parler 15 minutes sur un sujet tiré au hasard.", "Jeu de prise de parole.",
  [("N", "ຫົວຂໍ້|ແມ່ນ|«|ຄອບຄົວ|»|.|ເລີ່ມ|ເລີຍ|!", "Le sujet : « la famille ». Vas-y !"),
   ("C", "ສຳລັບ|ຂ້ອຍ|,|ຄອບຄົວ|ແມ່ນ|ສິ່ງ|ທີ່|ສຳຄັນ|ທີ່ສຸດ|…", "Pour moi, la famille, c'est le plus important…")],
  [("Quel est le sujet ?", "La famille.")],
  [("ຫົວຂໍ້", "sujet"), ("ສຳລັບ|ຂ້ອຍ", "pour moi"), ("ຍົກ|ຕົວຢ່າງ", "donner un exemple"), ("ອີກ|ຢ່າງ|ໜຶ່ງ", "autre chose"), ("ກັບ|ມາ|ທີ່", "pour revenir à")],
  "tenir la parole", [("ຍົກ|ຕົວຢ່າງ|…", "par exemple…"), ("ກັບ|ມາ|ທີ່|…", "pour revenir à…")],
  [], "Pour tenir longtemps : annoncer, illustrer (ຍົກຕົວຢ່າງ), digresser puis revenir (ກັບມາທີ່), conclure.",
  "la fluidité, sans t'arrêter.",
  [("Par exemple…", "ຍົກ|ຕົວຢ່າງ|…"), ("Pour revenir à…", "ກັບ|ມາ|ທີ່|…")],
  ["Enregistre-toi 15 minutes sur un sujet et réécoute."], "Parle 15 minutes sans préparation devant un natif."),
L(137, "Improvisation (2)", "Débattre sans préparation.", "Débat surprise au dîner.",
  [("S", "ໃຜ|ເຫັນດີ|ວ່າ|ຄວນ|ຫ້າມ|ໂທລະສັບ|ໃນ|ໂຮງຮຽນ|?", "Qui pense qu'il faut interdire les téléphones à l'école ?"),
   ("C", "ຂ້ອຍ|ເຫັນດີ|ສ່ວນ|ໜຶ່ງ|,|ແຕ່|…", "Je suis en partie d'accord, mais…"),
   ("K", "ຂ້ອຍ|ບໍ່|ເຫັນດີ|ເລີຍ|!", "Je ne suis pas du tout d'accord !")],
  [("Quel est le sujet ?", "Interdire les téléphones à l'école.")],
  [("ເຫັນດີ|ສ່ວນ|ໜຶ່ງ", "en partie d'accord"), ("ບໍ່|ເຫັນດີ|ເລີຍ", "pas du tout d'accord"), ("ໂຕ້|ແຍ້ງ", "contredire", "[À VÉRIFIER]"), ("ຍອມຮັບ", "admettre")],
  "réagir vite", [("ເຫັນດີ|ສ່ວນ|ໜຶ່ງ|,|ແຕ່|…", "en partie d'accord, mais…"), ("ຂ້ອຍ|ຍອມຮັບ|ວ່າ|…", "j'admets que…")],
  [], "En débat improvisé : se positionner vite, nuancer, reprendre l'argument de l'autre (ຍອມຮັບວ່າ…) avant de le contester.",
  "les réactions rapides.",
  [("Je suis en partie d'accord.", "ຂ້ອຍ|ເຫັນດີ|ສ່ວນ|ໜຶ່ງ|."), ("J'admets que…", "ຂ້ອຍ|ຍອມຮັບ|ວ່າ|…")],
  ["Prépare des arguments pour et contre sur 5 sujets."], "Débats 20 minutes sans préparation avec un natif."),
L(138, "S'adapter à l'interlocuteur", "Passer d'un registre à l'autre dans une même scène.", "Une journée de Clara : un moine, un ami, un ministre.",
  [("C", "ສາທຸ|.", "(au moine) Sathou."),
   ("C", "ໄປ|ກິນ|ເບຍ|ບໍ|?", "(à un ami) On va boire une bière ?"),
   ("C", "ຂ້າພະເຈົ້າ|ຂໍ|ຂອບໃຈ|ທ່ານ|ເປັນ|ຢ່າງ|ຍິ່ງ|.", "(au ministre) Je vous remercie infiniment.")],
  [("Combien de registres utilise Clara ?", "Trois : religieux, familier, officiel.")],
  [("ລະດັບ|ພາສາ", "registre de langue"), ("ປັບ|ຕົວ", "s'adapter"), ("ສະຖານະການ", "situation")],
  "synthèse des registres", [("ກິນ|/|ຮັບປະທານ|/|ຈັງຫັນ", "manger : courant / soutenu / moine [À VÉRIFIER]"), ("ຂ້ອຍ|/|ຂ້າພະເຈົ້າ", "je : courant / soutenu")],
  [], "Maîtriser le lao, c'est choisir pour chaque interlocuteur les pronoms, les verbes, les particules et le ton de voix adaptés.",
  "les changements de registre.",
  [("Je vous remercie infiniment.", "ຂ້າພະເຈົ້າ|ຂໍ|ຂອບໃຈ|ທ່ານ|ເປັນ|ຢ່າງ|ຍິ່ງ|."), ("On va boire une bière ?", "ໄປ|ກິນ|ເບຍ|ບໍ|?")],
  ["Écris la même demande dans 4 registres différents."], "Joue avec un natif une scène où tu changes 3 fois d'interlocuteur."),
L(139, "Projet final", "Produire un contenu complet en lao (vidéo, texte ou podcast).", "Clara prépare une vidéo sur son année au Laos.",
  [("C", "ຂ້ອຍ|ຈະ|ເຮັດ|ວິດີໂອ|ກ່ຽວກັບ|ຊີວິດ|ຢູ່|ລາວ|.", "Je vais faire une vidéo sur ma vie au Laos."),
   ("N", "ຂ້ອຍ|ຊ່ວຍ|ກວດ|ພາສາ|ໃຫ້|.", "Je t'aide à vérifier la langue."),
   ("C", "ຂອບໃຈ|.|ຈະ|ໂພສ|ອາທິດໜ້າ|.", "Merci. Je la poste la semaine prochaine.")],
  [("Quel est le projet de Clara ?", "Une vidéo sur sa vie au Laos.")],
  [("ໂຄງການ", "projet"), ("ເນື້ອຫາ", "contenu"), ("ກວດ", "vérifier"), ("ເຜີຍແຜ່", "publier, diffuser")],
  "planifier un contenu", [("ຈະ|ເຮັດ|…|ກ່ຽວກັບ|…", "je vais faire… sur…")],
  [], "Projet final : choisir un format, écrire le script, le faire relire, l'enregistrer, le publier.",
  "ta propre production.",
  [("Je vais faire une vidéo.", "ຂ້ອຍ|ຈະ|ເຮັດ|ວິດີໂອ|."), ("Tu peux vérifier ?", "ກວດ|ໃຫ້|ແດ່|ໄດ້|ບໍ|?")],
  ["Écris le script complet de ton projet."], "Publie un contenu en lao (vidéo, texte ou podcast) relu par un natif."),
L(140, "Bilan C1", "Faire le bilan final sur les 4 compétences.", "Dernier jour de cours.",
  [("A", "ເຈົ້າ|ຮຽນ|ມາ|ຮອດ|ບົດ|ສຸດທ້າຍ|ແລ້ວ|.", "Tu es arrivée à la dernière leçon."),
   ("C", "ຂອບໃຈ|ອາຈານ|ຫຼາຍໆ|.|ຂ້ອຍ|ຈະ|ຮຽນ|ຕໍ່|ໄປ|.", "Merci beaucoup, professeur. Je vais continuer à apprendre."),
   ("A", "ພາສາ|ບໍ່|ມີ|ວັນ|ຈົບ|.", "Une langue ne finit jamais.")],
  [("Que dit le professeur à la fin ?", "Une langue ne finit jamais.")],
  [("ບົດ|ສຸດທ້າຍ", "dernière leçon"), ("ຮຽນ|ຕໍ່", "continuer à étudier"), ("ຄ່ອງແຄ້ວ", "fluide, aisé", "[À VÉRIFIER]")],
  "bilan du parcours", [("ຂ້ອຍ|ຮຽນ|ມາ|…|ປີ|ແລ້ວ", "j'étudie depuis… ans")],
  [], "Bilan C1 : registres, expressions, improvisation, écrit formel et littéraire. Fais le test final et une longue conversation avec un natif.",
  "une conversation sans préparation.",
  [("Je vais continuer à apprendre.", "ຂ້ອຍ|ຈະ|ຮຽນ|ຕໍ່|ໄປ|."), ("Merci beaucoup, professeur.", "ຂອບໃຈ|ອາຈານ|ຫຼາຍໆ|.")],
  ["Écris une lettre de 500 mots à ton toi du début du parcours, en lao."], "Fais le test final C1 et une conversation d'une heure avec un natif."),
]
